// ============================================================
// CNN Exam Study - Content Bank
// Edit this file to add questions/flashcards from any source.
// Each entry: {topic, q, opts:[4], ans:index, expl}
// ============================================================

const QUESTIONS = [
  // ---------- Concepts of Kidney Disease ----------
  {topic:"Kidney Disease", q:"What are the three categories of acute kidney injury (AKI), based on cause?",
   opts:["Prerenal, intrarenal, postrenal","Glomerular, tubular, interstitial","Acute, chronic, terminal","Hepatic, cardiac, renal"],
   ans:0, expl:"AKI is divided into prerenal (decreased blood flow before the kidney), intrarenal (damage within the kidney, often from drugs), and postrenal (urine flow obstruction after the kidney)."},
  {topic:"Kidney Disease", q:"A patient has AKI with high urine specific gravity, low urinary sodium, and oliguria. This most likely represents:",
   opts:["Acute tubular necrosis (ATN)","Prerenal injury","Postrenal obstruction","Glomerulonephritis"],
   ans:1, expl:"Prerenal injury shows high urine specific gravity and low urinary sodium. In ATN, urine specific gravity is low and urinary sodium is high (>20 mEq/L)."},
  {topic:"Kidney Disease", q:"Which urine sodium finding is characteristic of acute tubular necrosis (ATN)?",
   opts:["Low (<20 mEq/L)","High (>20 mEq/L)","Undetectable","Normal"],
   ans:1, expl:"In ATN, urinary sodium is high (>20 mEq/L) because tubular reabsorption fails. Prerenal injury shows low urinary sodium."},
  {topic:"Kidney Disease", q:"Which enzyme is released from damaged muscle cells and is a hallmark of rhabdomyolysis?",
   opts:["Creatine phosphokinase (CK)","Troponin","Amylase","Alkaline phosphatase"],
   ans:0, expl:"Rhabdomyolysis releases creatine phosphokinase (CK) from damaged muscle. Higher levels suggest more severe injury."},
  {topic:"Kidney Disease", q:"What is the recommended IV fluid rate for rhabdomyolysis-associated AKI to flush out myoglobin?",
   opts:["50-100 mL/hr","200-300 mL/hr of isotonic saline","500 mL/hr","10 mL/kg/hr"],
   ans:1, expl:"Aggressive fluids at 200-300 mL/hr of isotonic saline aim for urine output of 1-2 mL/kg/hr to flush out myoglobin."},
  {topic:"Kidney Disease", q:"Acute interstitial nephritis (AIN) is most commonly caused by:",
   opts:["Bacterial infection","Drugs, especially NSAIDs and antibiotics","Autoimmune disease","Obstruction"],
   ans:1, expl:"AIN is most commonly caused by drugs, with NSAIDs and antibiotics being the most common source. >75% are drug hypersensitivity reactions."},
  {topic:"Kidney Disease", q:"The most important treatment for acute interstitial nephritis (AIN) is:",
   opts:["Corticosteroids","Discontinuing the offending agent","Antibiotics","Dialysis"],
   ans:1, expl:"Discontinuing the offending agent is the most important treatment of AIN. Hydration and avoiding nephrotoxins are also key."},
  {topic:"Kidney Disease", q:"HELLP syndrome is characterized by:",
   opts:["Hemolysis, elevated liver enzymes, low platelets","Hypotension, edema, low platelets","Heart failure, lung edema, proteinuria","Hematuria, elevated LFTs, low urine"],
   ans:0, expl:"HELLP = Hemolysis, Elevated Liver enzymes, Low Platelets. It is a severe form of preeclampsia."},
  {topic:"Kidney Disease", q:"Which dialysis treatment is indicated for salicylate toxicity when the level exceeds 100 mg/dL?",
   opts:["Peritoneal dialysis","Hemodialysis","CRRT only","No dialysis needed"],
   ans:1, expl:"HD is indicated for salicylate levels >100 mg/dL, severe acidosis, altered mental status, or pulmonary edema."},
  {topic:"Kidney Disease", q:"The preferred antidote for ethylene glycol and methanol intoxication is:",
   opts:["Ethanol","Fomepizole","Naloxone","Sodium bicarbonate alone"],
   ans:1, expl:"Fomepizole is the preferred antidote for ethylene glycol and methanol. Ethanol is used only if fomepizole is unavailable."},
  {topic:"Kidney Disease", q:"The normal therapeutic serum level for salicylates is:",
   opts:["10-30 mg/dL","40-80 mg/dL","80-100 mg/dL",">100 mg/dL"],
   ans:0, expl:"The therapeutic salicylate level is 10-30 mg/dL. Toxicity begins at higher levels."},
  {topic:"Kidney Disease", q:"Chronic kidney disease (CKD) is distinguished from AKI by a duration of kidney abnormality greater than:",
   opts:["1 month","3 months","6 months","1 year"],
   ans:1, expl:"CKD is an abnormality present for >3 months. The 3-month timeline distinguishes CKD from AKI."},
  {topic:"Kidney Disease", q:"What is the most common cause of death in CKD patients?",
   opts:["Infection","Cardiovascular disease","Malnutrition","Cancer"],
   ans:1, expl:"Cardiovascular disease is the leading cause of death for CKD patients."},
  {topic:"Kidney Disease", q:"At what GFR does the kidney begin to lose its ability to maintain fluid and electrolyte homeostasis?",
   opts:["Below 90","Below 60","Below 20","Below 5"],
   ans:2, expl:"When GFR drops below 20 mL/min, the remaining nephrons can no longer maintain homeostasis, leading to fluid overload."},

  // ---------- Hemodialysis ----------
  {topic:"Hemodialysis", q:"Which potassium-restricted diet consideration is typical for a patient on hemodialysis?",
   opts:["No restriction","Limit to 2000 mg/day","Limit to 3000 mg/day","Unlimited"],
   ans:1, expl:"Hyperkalemic HD patients typically need potassium restriction, often ~2000 mg/day. Fluid and sodium are also restricted."},
  {topic:"Hemodialysis", q:"The medication class that must often be held before hemodialysis to prevent hypotension is:",
   opts:["Antibiotics","Antihypertensives","Anticoagulants","Antiemetics"],
   ans:1, expl:"Some blood pressure medications may need to be held before HD to prevent hypotension from the combination of medication and fluid loss during dialysis."},
  {topic:"Hemodialysis", q:"After how long does ischemic damage to the kidney usually become irreversible?",
   opts:["15-30 minutes","60-90 minutes","4 hours","24 hours"],
   ans:1, expl:"After 60-90 minutes of decreased blood flow, ischemic damage is usually irreversible, reducing blood flow as much as 50%."},
  {topic:"Hemodialysis", q:"Which type of RRT is preferred for a hemodynamically unstable patient?",
   opts:["Intermittent HD","CRRT","Standard HD","Hemofiltration"],
   ans:1, expl:"CRRT is often preferable to HD for hemodynamically unstable patients because it provides slower, more gradual fluid removal."},

  // ---------- Peritoneal Dialysis ----------
  {topic:"Peritoneal Dialysis", q:"For a patient on peritoneal dialysis, what protein intake is recommended?",
   opts:["0.8 g/kg","1.2-1.5 g/kg","2.5 g/kg","3.0 g/kg"],
   ans:1, expl:"Patients on PD require 1.2-1.5 g/kg protein. Up to 2 g/kg may be needed with severe peritonitis."},
  {topic:"Peritoneal Dialysis", q:"During peritoneal dialysis, which fluid is used to flush out the peritoneal cavity?",
   opts:["Isotonic saline","Dialysate with glucose","Sterile water","Lactated ringers"],
   ans:1, expl:"PD uses glucose-containing dialysate instilled into the peritoneal cavity, which allows diffusion and ultrafiltration."},
  {topic:"Peritoneal Dialysis", q:"Continuous ambulatory peritoneal dialysis (CAPD) exchanges are typically performed:",
   opts:["Once daily","Multiple times daily","Weekly","Every other week"],
   ans:1, expl:"CAPD requires multiple exchanges daily (typically 3-5 exchanges, 4-6 hours dwell each)."},

  // ---------- Transplant ----------
  {topic:"Transplant", q:"Which replacement fluid is recommended during plasmapheresis for anti-GBM disease?",
   opts:["Normal saline","Albumin","Lactated ringers","Dextran"],
   ans:1, expl:"Albumin is the recommended replacement fluid during plasmapheresis. FFP is used for pulmonary hemorrhage to replace clotting factors."},
  {topic:"Transplant", q:"In anti-GBM disease, immunosuppressive therapy commonly includes:",
   opts:["IV methylprednisolone with cyclophosphamide","Prednisone alone","IVIG alone","Tacrolimus"],
   ans:0, expl:"IV methylprednisolone combined with cyclophosphamide prevents further antibody formation."},

  // ---------- Acute Therapies ----------
  {topic:"Acute Therapies", q:"KDIGO recommends initiation of renal replacement therapy at which stage of AKI?",
   opts:["Stage 1","Stage 2","Stage 3","Any stage"],
   ans:1, expl:"KDIGO recommends RRT initiation at stage 2 AKI, defined by doubled creatinine and urine output <0.5 mL/kg/hr over 12 hours."},
  {topic:"Acute Therapies", q:"Which nutrition is preferred in AKI patients when possible?",
   opts:["Parenteral","Enteral","Total parenteral only","IV fluids only"],
   ans:1, expl:"Enteral nutrition is preferred over parenteral because it results in fewer infectious and noninfectious complications."},
  {topic:"Acute Therapies", q:"For a patient with AKI on CRRT, what protein intake is recommended?",
   opts:["0.8 g/kg","1.2-1.5 g/kg","1.8-2.5 g/kg","3.0 g/kg"],
   ans:2, expl:"Patients on CRRT require the highest protein, 1.8-2.5 g/kg, due to losses during continuous therapy."},
  {topic:"Acute Therapies", q:"RRT is indicated in AKI for which condition?",
   opts:["Hyperkalemia","Mild dehydration","Normal creatinine","Stable fluid status"],
   ans:0, expl:"RRT is indicated for hyperkalemia, metabolic acidosis, fluid overload, uremic pericarditis, and severe oliguria/anuria."},
  {topic:"Acute Therapies", q:"For ethylene glycol toxicity, HD should use a blood flow rate of at least:",
   opts:["100 mL/min","200 mL/min","300 mL/min","500 mL/min"],
   ans:2, expl:"HD for ethylene glycol requires blood flow of at least 300 mL/min with a large-surface-area dialyzer."},
  {topic:"Acute Therapies", q:"In AKI, the multivitamin dosage added to daily parenteral nutrition is:",
   opts:["2 mL IV","5 mL IV","10 mL IV","20 mL IV"],
   ans:2, expl:"A multivitamin of 10 mL IV is added to the daily parenteral formula in AKI."},
  {topic:"Acute Therapies", q:"Vitamin C (ascorbic acid) should be limited in AKI to avoid accumulation of which metabolite?",
   opts:["Oxalate","Urea","Creatinine","Ammonia"],
   ans:0, expl:"Oxalate can collect in the renal tubules when GFR is low, worsening AKI. Limit ascorbic acid to 200 mg/day."}
];

// ============================================================
// FLASHCARDS
// ============================================================
const FLASHCARDS = [
  {topic:"Kidney Disease", front:"Three categories of AKI", back:"Prerenal (low blood flow before kidney), Intrarenal (within kidney, drug/toxic), Postrenal (urine flow obstruction)"},
  {topic:"Kidney Disease", front:"Prerenal AKI urine findings", back:"High specific gravity, low urinary sodium, oliguria, high osmolality"},
  {topic:"Kidney Disease", front:"ATN urine findings", back:"Low specific gravity, high urinary sodium (>20 mEq/L), low osmolality"},
  {topic:"Kidney Disease", front:"Rhabdomyolysis hallmark enzyme", back:"Creatine phosphokinase (CPK) rises from damaged muscle"},
  {topic:"Kidney Disease", front:"Rhabdomyolysis fluids", back:"200-300 mL/hr isotonic saline to target 1-2 mL/kg/hr urine"},
  {topic:"Kidney Disease", front:"Most common cause of AIN", back:"Drugs (NSAIDs, antibiotics) >75% drug hypersensitivity"},
  {topic:"Kidney Disease", front:"AIN most important treatment", back:"Discontinue the offending drug"},
  {topic:"Kidney Disease", front:"HELLP syndrome", back:"Hemolysis, Elevated Liver enzymes, Low Platelets; severe preeclampsia"},
  {topic:"Kidney Disease", front:"HD indication in salicylate toxicity", back:"Levels >100 mg/dL, severe acidosis, altered mentation, pulmonary edema"},
  {topic:"Kidney Disease", front:"CKD duration definition", back:">3 months of kidney abnormality (vs AKI)"},
  {topic:"Kidney Disease", front:"Leading cause of death in CKD", back:"Cardiovascular disease"},
  {topic:"Kidney Disease", front:"GFR threshold for homeostasis loss", back:"Below 20 mL/min fluid/electrolyte homeostasis fails"},
  {topic:"Hemodialysis", front:"Hold before HD to prevent hypotension", back:"Some antihypertensive medications (hold with nephrologist's order)"},
  {topic:"Hemodialysis", front:"Hemodialysis protein need", back:"1.2-1.5 g/kg for HD patients"},
  {topic:"Peritoneal Dialysis", front:"PD protein need", back:"1.2-1.5 g/kg (up to 2 g/kg with severe peritonitis)"},
  {topic:"Transplant", front:"Anti-GBM plasmapheresis replacement fluid", back:"Albumin (FFP for pulmonary hemorrhage)"},
  {topic:"Transplant", front:"Anti-GBM immunosuppressive therapy", back:"IV methylprednisolone + cyclophosphamide"},
  {topic:"Acute Therapies", front:"KDIGO RRT initiation stage", back:"Stage 2 AKI (creatinine doubled, urine <0.5 mL/kg/hr over 12h)"},
  {topic:"Acute Therapies", front:"RRT protein need", back:"1.8-2.5 g/kg (highest of all modalities)"},
  {topic:"Acute Therapies", front:"Preferred nutrition in AKI", back:"Enteral nutrition (fewer complications than parenteral)"},
  {topic:"Acute Therapies", front:"Ascorbic acid limit in AKI", back:"200 mg/day to avoid oxalate accumulation"},
  {topic:"Acute Therapies", front:"Ethylene glycol HD blood flow", back:"At least 300 mL/min, large surface area dialyzer"},
  {topic:"Acute Therapies", front:"RRT indication - hyperkalemia", back:"Yes, hyperkalemia is a key indication for RRT in AKI"}
];

// ============================================================
// ADDITIONAL Kidney Disease questions (from Mometrix guide)
// ============================================================
const EXTRA_KIDNEY_QUESTIONS = [
  {topic:"Kidney Disease", q:"In postrenal AKI, common causes include which of the following?",
   opts:["Renal calculi and urinary tract obstruction","Decreased renal perfusion","NSAID use","Glomerular basement membrane damage"],
   ans:0, expl:"Postrenal AKI is caused by interruption of urine flow, usually from obstruction such as renal calculi, strictures, neoplasms, or blood clots."},
  {topic:"Kidney Disease", q:"Which imaging study is commonly ordered to locate a urinary obstruction in postrenal AKI?",
   opts:["KUB (kidneys, ureters, bladder) x-ray","Chest x-ray","Echocardiogram","Bone scan"],
   ans:0, expl:"A KUB and imaging such as ultrasound, CT, or MRI are used to determine the location of the obstruction."},
  {topic:"Kidney Disease", q:"What serum finding is elevated in rhabdomyolysis-associated AKI?",
   opts:["Creatine kinase (CK)","Amylase","Lipase","Alkaline phosphatase"],
   ans:0, expl:"Serum myoglobin >15,000 μg/L and creatinine kinase >5,000 IU/L are bloodwork findings in rhabdomyolysis-associated AKI."},
  {topic:"Kidney Disease", q:"Which urine appearance is classic for rhabdomyolysis-associated AKI?",
   opts:["Tea-colored urine","Clear urine","Green urine","Foamy urine"],
   ans:0, expl:"The nurse may expect urine that appears tea colored in rhabdomyolysis-associated AKI."},
  {topic:"Kidney Disease", q:"Sodium bicarbonate may be given in rhabdomyolysis to keep urine pH above:",
   opts:["6.5","5.0","4.0","8.0"],
   ans:0, expl:"Sodium bicarbonate may be administered IV to keep the pH of the urine >6.5 to prevent myoglobin cast formation."},
  {topic:"Kidney Disease", q:"Which syndrome is a severe form of preeclampsia that affects the kidneys?",
   opts:["HELLP syndrome","Goodpasture syndrome","Hepatorenal syndrome","Nephrotic syndrome"],
   ans:0, expl:"HELLP syndrome is a severe form of preeclampsia characterized by hemolysis, elevated liver enzymes, and low platelets."},
  {topic:"Kidney Disease", q:"In HELLP syndrome Class I, delivery of the fetus is recommended within:",
   opts:["48 hours","1 week","24 hours of admission","12 hours"],
   ans:0, expl:"Class I HELLP (platelets <50,000) requires delivery of the fetus within 48 hours."},
  {topic:"Kidney Disease", q:"The most common cause of death in salicylate toxicity is:",
   opts:["Acute noncardiac pulmonary edema","Hyperkalemia","Septic shock","Pulmonary embolism"],
   ans:0, expl:"Acute pulmonary edema is the most common cause of death in salicylate toxicity."},
  {topic:"Kidney Disease", q:"What is the urine output goal during salicylate toxicity treatment?",
   opts:["2-3 mL/kg/hr","0.5 mL/kg/hr","5 mL/kg/hr","10 mL/kg/hr"],
   ans:0, expl:"The urine output goal in salicylate toxicity is 2-3 mL/kg/hr."},
  {topic:"Kidney Disease", q:"For salicylate toxicity, blood samples for drug levels should NOT be drawn through the dialysis catheter because:",
   opts:["It may cause recirculation and alter drug levels","It causes hemolysis","It increases the risk of clotting","It is too painful for the patient"],
   ans:0, expl:"Serum salicylate samples drawn via the dialysis catheter may cause recirculation of blood, which alters drug levels."},
  {topic:"Kidney Disease", q:"A serum glycol level denoting ethylene glycol toxicity is:",
   opts:[">20 mg/dL",">100 mg/dL",">5 mg/dL",">50 mg/dL"],
   ans:0, expl:"A serum glycol level >20 mg/dL denotes ethylene glycol toxicity."},
  {topic:"Kidney Disease", q:"Which antidote is preferred for ethylene glycol and methanol intoxication?",
   opts:["Fomepizole","Ethanol","Naloxone","Flumazenil"],
   ans:0, expl:"Fomepizole is the preferred antidote for ethylene glycol and methanol intoxication."},
  {topic:"Kidney Disease", q:"Hepatorenal syndrome type 1 is characterized by a rise in serum creatinine greater than:",
   opts:["0.3 mg/dL within 48 hours","1.0 mg/dL within 24 hours","2.0 mg/dL within 1 week","0.5 mg/dL within 72 hours"],
   ans:0, expl:"HRS-1 is defined by an increase in serum creatinine >0.3 mg/dL within 48 hours or a 1.5x increase within 7 days."},
  {topic:"Kidney Disease", q:"For hepatorenal syndrome, which vasopressor is recommended?",
   opts:["Norepinephrine","Nitroprusside","Dobutamine","Atenolol"],
   ans:0, expl:"Norepinephrine is recommended to avoid hypotension in HRS, and vasoconstrictors are used to increase MAP."},
  {topic:"Kidney Disease", q:"What is the protein requirement for a patient with AKI on CRRT?",
   opts:["1.8-2.5 g/kg","0.8 g/kg","1.0 g/kg","3.0 g/kg"],
   ans:0, expl:"Patients on CRRT require 1.8-2.5 g/kg protein due to losses during continuous therapy."},
  {topic:"Kidney Disease", q:"Which is an indication for parenteral nutrition in AKI?",
   opts:["Short gut syndrome","Mild dehydration","Normal GI function","None of the above"],
   ans:0, expl:"Parenteral nutrition is indicated for short gut syndrome (60 cm small bowel with colon or 120 cm without colon), high-output fistula, or inability to place enteral access."},
  {topic:"Kidney Disease", q:"In AKI parenteral nutrition, glucose infusions should be limited to:",
   opts:["3 mg/min/kg","10 mg/min/kg","1 mg/min/kg","5 mg/min/kg"],
   ans:0, expl:"Glucose infusions are limited to a maximum of 3 mg/min/kg of ideal body weight in critically ill AKI patients."},
  {topic:"Kidney Disease", q:"What is the maximum vitamin C (ascorbic acid) allowed daily in AKI parenteral nutrition?",
   opts:["200 mg/day","500 mg/day","100 mg/day","1 g/day"],
   ans:0, expl:"Vitamin C is limited to 200 mg/day to avoid accumulation of oxalate, which can worsen AKI."},
  {topic:"Kidney Disease", q:"KDIGO recommends initiating RRT for AKI at stage:",
   opts:["2 (AKIN)","1","3","4"],
   ans:0, expl:"KDIGO recommends RRT initiation at stage 2 AKI as defined by AKIN (creatinine doubled and urine output <0.5 mL/kg/hr)."},
  {topic:"Kidney Disease", q:"Which is a limitation of the RIFLE criteria for AKI?",
   opts:["Requires a baseline creatinine that may not be known","Requires only urine output","Is not used in adults","Cannot detect CKD"],
   ans:0, expl:"A limitation of RIFLE is that it requires a baseline creatinine which may not be known."},
  {topic:"Kidney Disease", q:"Which is a limitation of the AKIN criteria for AKI?",
   opts:["Requires two serum creatinine levels within a 48-hour time frame","Cannot detect early AKI","Overdetects CKD","Cannot be used in the ICU"],
   ans:0, expl:"AKIN requires two serum creatinine levels within a 48-hour time frame and does not identify AKI in levels drawn >48 hours apart."},
  {topic:"Kidney Disease", q:"What is the primary driver of the renin-angiotensin-aldosterone system in prerenal AKI?",
   opts:["Decreased renal perfusion / hypotension","Increased GFR","High urine output","Excess sodium intake"],
   ans:0, expl:"Decreased renal perfusion triggers renin release, activating the RAAS to cause sodium/water reabsorption and vasoconstriction."}
];

// ============================================================
// CKD COMPLICATIONS (anemia, mineral-bone) - from Mometrix guide
// ============================================================
const EXTRA_CKD_QUESTIONS = [
  {topic:"CKD Complications", q:"The primary cause of anemia in CKD is:",
   opts:["Erythropoietin deficiency","Iron deficiency","Vitamin B12 deficiency","Blood loss"],
   ans:0, expl:"The primary cause of anemia in CKD is erythropoietin deficiency, since the kidneys produce 90% of erythropoietin."},
  {topic:"CKD Complications", q:"In CKD, the red blood cell life span is reduced to approximately:",
   opts:["60-90 days","120 days","30 days","150 days"],
   ans:0, expl:"Normal RBC life span is 120 days, but in CKD it is reduced to 60-90 days."},
  {topic:"CKD Complications", q:"According to KDIGO, anemia in adults is defined by Hgb less than:",
   opts:["13 g/dL in males, 12 g/dL in females","10 g/dL in all adults","12 g/dL in all adults","14 g/dL in males"],
   ans:0, expl:"Anemia is defined as Hgb <13 g/dL in males and <12 g/dL in females."},
  {topic:"CKD Complications", q:"What transferrin saturation is considered iron-deficiency anemia?",
   opts:["<16%",">50%","<5%",">80%"],
   ans:0, expl:"A serum transferrin saturation <16% is considered iron-deficiency anemia."},
  {topic:"CKD Complications", q:"KDIGO recommends starting ESA therapy when Hgb is at or below:",
   opts:["10 g/dL",">12 g/dL","11 g/dL","13 g/dL"],
   ans:0, expl:"KDIGO recommends beginning ESA therapy when Hgb is 10 g/dL or lower after considering individual risks."},
  {topic:"CKD Complications", q:"ESA therapy should be reduced or stopped when Hgb reaches:",
   opts:["12 g/dL","14 g/dL","10 g/dL","15 g/dL"],
   ans:0, expl:"Once Hgb reaches 12 g/dL, ESA therapy should be reduced or stopped to prevent side effects."},
  {topic:"CKD Complications", q:"Which is a rare but serious complication of long-term ESA therapy?",
   opts:["Pure RBC aplasia","Hyperkalemia","Osteoporosis","Iron overload"],
   ans:0, expl:"Pure RBC aplasia is a rare, serious transfusion-dependent anemia affecting patients on ESA therapy for >8 weeks."},
  {topic:"CKD Complications", q:"A patient is considered hyporesponsive to ESA therapy if there is no Hgb increase after:",
   opts:["4 weeks","1 week","8 weeks","3 months"],
   ans:0, expl:"No increase in Hgb after 4 weeks indicates hyporesponsiveness to ESA therapy."},
  {topic:"CKD Complications", q:"For a patient on dialysis, which route of iron is generally considered?",
   opts:["IV iron","Oral iron only","Transfusion only","No iron"],
   ans:0, expl:"IV iron should be considered for patients on dialysis, while a trial of oral iron is considered for those not on dialysis."},
  {topic:"CKD Complications", q:"Secondary hyperparathyroidism in CKD is primarily caused by:",
   opts:["Hyperphosphatemia and vitamin D abnormalities","Calcium excess","Low PTH","Excess dietary protein"],
   ans:0, expl:"Reduced phosphate excretion leads to hyperphosphatemia, which decreases calcium and stimulates increased PTH."},
  {topic:"CKD Complications", q:"High-bone-turnover disease in CKD is also known as:",
   opts:["Osteitis fibrosa","Adynamic bone disease","Osteomalacia","Osteoporosis"],
   ans:0, expl:"High-bone-turnover disease is osteitis fibrosa, resulting from secondary hyperparathyroidism."},
  {topic:"CKD Complications", q:"Low-bone-turnover disease (adynamic bone disease) is most commonly seen in:",
   opts:["Patients with ESRD on dialysis","Early-stage CKD","Children","Patients not yet on dialysis"],
   ans:0, expl:"Low-bone-turnover disease is common in CKD but mainly seen in patients with ESRD on dialysis."}
];

// ============================================================
// HEMODIALYSIS questions (from Mometrix guide)
// ============================================================
const EXTRA_HD_QUESTIONS = [
  {topic:"Hemodialysis", q:"What is the primary mechanism by which hemodialysis removes small waste molecules like urea and creatinine?",
   opts:["Ultrafiltration","Diffusion","Osmosis","Adsorption"],
   ans:1, expl:"Diffusion is the movement of solutes from an area of higher concentration to lower concentration across the semipermeable membrane. This is how small molecules like urea are removed."},
  {topic:"Hemodialysis", q:"Fluid is removed during HD primarily by which process?",
   opts:["Diffusion","Convection","Ultrafiltration (UF)","Osmosis"],
   ans:2, expl:"Fluid is removed during HD by ultrafiltration (UF), the transfer of fluid from the blood to the dialysate, dependent on transmembrane pressure."},
  {topic:"Hemodialysis", q:"Clearance in HD refers to:",
   opts:["The volume of blood a solute is removed from over time within the dialyzer","The patient's blood volume","The dialysate flow rate","The membrane thickness"],
   ans:0, expl:"Clearance is the volume of blood that a solute is removed from over time within the dialyzer, e.g., urea clearance."},
  {topic:"Hemodialysis", q:"The efficiency of a dialyzer refers to its ability to remove small molecules and is measured in:",
   opts:["mL/min","mmHg","daltons","L/kg"],
   ans:0, expl:"Efficiency measures small-molecule removal in mL/min. Low efficiency is <450 mL/min, high efficiency is >700 mL/min."},
  {topic:"Hemodialysis", q:"Backfiltration, which can carry endotoxins from dialysate into the blood, can occur with:",
   opts:["Low-flux dialyzers only","High-flux dialyzers","All dialyzers","No dialyzer"],
   ans:1, expl:"Backfiltration is the movement of fluid from dialysate back to blood and can occur with high-flux dialyzers. Ultrapure dialysate minimizes the risk."},
  {topic:"Hemodialysis", q:"The venous drip chamber and air detector are important because they:",
   opts:["Increase blood flow","Trap air and trigger an alarm to prevent air from entering the patient","Measure conductivity","Remove potassium"],
   ans:1, expl:"The venous drip chamber traps air and sits in an air detector that senses air and stops the blood pump to prevent air embolism."},
  {topic:"Hemodialysis", q:"A progressive rise in venous pressure during HD most likely indicates:",
   opts:["Air in the line","Clotting within the circuit","Low blood flow","Patient dehydration"],
   ans:1, expl:"Venous pressure monitors coagulation within the blood circuit; a progressive rise is the first sign of clotting."},
  {topic:"Hemodialysis", q:"The recommended dialysate pH range is:",
   opts:["4.5-5.5","6.9-7.6","8.0-9.0","7.0-8.0"],
   ans:1, expl:"The recommended dialysate pH range is 6.9-7.6 per AAMI."},
  {topic:"Hemodialysis", q:"Dialysate conductivity should be between:",
   opts:["6-8 mS/cm","12-16 mS/cm","20-25 mS/cm","30-35 mS/cm"],
   ans:1, expl:"Conductivity should be 12-16 millisiemens per centimeter; it reflects the electrolyte concentration of the dialysate."},
  {topic:"Hemodialysis", q:"A dialysate temperature above 42 C can cause:",
   opts:["Shivering","Hemolysis and protein denaturation","Clotting","Hypotension"],
   ans:1, expl:"A dialysate temperature that is too high (>42 °C) can cause hemolysis and protein denaturation."},
  {topic:"Hemodialysis", q:"What is the most common buffer used to correct acid-base balance in US HD?",
   opts:["Acetate","Lactate","Bicarbonate","Citrate"],
   ans:2, expl:"Bicarbonate is the most common buffer used for acid-base balance in US HD."},
  {topic:"Hemodialysis", q:"The most common dialysate sodium concentration used in HD is:",
   opts:["110-120 mEq/L","135-145 mEq/L","150-160 mEq/L","90-100 mEq/L"],
   ans:1, expl:"The most frequent dialysate sodium concentration is 135-145 mEq/L, matching the normal plasma sodium range."},
  {topic:"Hemodialysis", q:"Why should serum potassium NOT be removed too rapidly during HD?",
   opts:["It causes hypotension","It can affect the QT interval and cause dysrhythmias","It causes cramping","It causes hypoxemia"],
   ans:1, expl:"Rapid potassium removal can affect the QT interval; 0 and 1 mEq/L potassium baths should only be used with cardiac monitoring."},
  {topic:"Hemodialysis", q:"A patient taking digitalis should be dialyzed against a potassium bath of:",
   opts:["0 K","1 K","2 K","3 K"],
   ans:3, expl:"Patients taking digitalis should be dialyzed on a 3 K dialysate bath."},
  {topic:"Hemodialysis", q:"The most common complication during HD treatment is:",
   opts:["Intradialytic hypotension","Muscle cramping","Fever","Dysrhythmia"],
   ans:0, expl:"The most common complication during HD is intradialytic hypotension, most often due to UF-induced hypovolemia and decreased PVR."},
  {topic:"Hemodialysis", q:"The most common cause of intradialytic hypotension is:",
   opts:["Cardiac disease","A decrease in peripheral vascular resistance and rapid blood volume decrease","High UF coefficient","Increased dialysate temperature"],
   ans:1, expl:"Intradialytic hypotension is most commonly caused by decreased PVR and a rapid decrease in blood volume."},
  {topic:"Hemodialysis", q:"KDOQI recommends what Kt/V for patients dialyzing three times per week?",
   opts:["1.0","1.2","1.4","2.3"],
   ans:2, expl:"In 2015 KDOQI recommended a spKt/V of 1.4 per treatment for patients who dialyze three times a week."},
  {topic:"Hemodialysis", q:"Muscle cramping during HD most often occurs:",
   opts:["At the start of treatment","During the second half of HD treatment","Only after treatment","During the dialysate priming"],
   ans:1, expl:"Cramping most often occurs during the second half of HD treatment when fluids and electrolytes shift to extremes."},
  {topic:"Hemodialysis", q:"A type A (allergic) reaction during HD is mediated through:",
   opts:["Complement","Immunoglobulin E","Histamine release only","Neutrophils"],
   ans:1, expl:"Type A reactions are progressive and usually mediated through immunoglobulin E (IgE). Type B are complement-mediated."},
  {topic:"Hemodialysis", q:"If a severe type A or type B allergic reaction occurs during HD, the nurse should:",
   opts:["Rinse back the blood quickly","Stop treatment and DO NOT rinse back the blood","Increase the blood flow","Give IV fluids only"],
   ans:1, expl:"For a severe reaction, stop treatment immediately and do NOT rinse back the patient's blood. Activate 911 in outpatient settings."},
  {topic:"Hemodialysis", q:"Pyrogenic fevers during HD typically occur:",
   opts:["Within the first 30-60 minutes","After 4 hours","The next day","Never with proper dialysis"],
   ans:0, expl:"Pyrogenic fevers occur within the first 30-60 minutes of HD, especially if the patient was asymptomatic before HD."},
  {topic:"Hemodialysis", q:"Which of the following is a cause of pyrogenic reactions during HD?",
   opts:["Bacterial contamination of the water supply","Too much anticoagulation","High dialysate temperature","Excess potassium"],
   ans:0, expl:"Pyrogenic reactions come from bacterial contamination of the water or colonization in the dialysis water treatment system."},
  {topic:"Hemodialysis", q:"When a severe reaction or pyrogenic event is suspected, the nurse should NOT rinse back blood but should:",
   opts:["Return blood to prevent blood loss","Obtain cultures (dialysate, water, blood) and notify the nephrologist","Increase dialysate flow","Administer more heparin"],
   ans:1, expl:"Do not rinse back blood; obtain inlet/outlet dialysate cultures and water cultures, notify the nephrologist, and give antibiotics/antipyretics as ordered."},
  {topic:"Hemodialysis", q:"The pre-pump arterial pressure reading during HD is typically:",
   opts:["Positive","Negative","Zero","Equal to venous pressure"],
   ans:1, expl:"The pre-pump arterial pressure is measured between the blood pump and patient; it is a negative pressure reading (below zero)."},
  {topic:"Hemodialysis", q:"Which type of membrane is considered the LEAST biocompatible and its use is discouraged?",
   opts:["Polysulfone","Unmodified cellulose","Cellulose triacetate","Polyacrylonitrile"],
   ans:1, expl:"Unmodified cellulose is poorly biocompatible and its use is discouraged; it is the most potent complement activator."},
  {topic:"Hemodialysis", q:"A blood leak detector works by:",
   opts:["Measuring pressure","Using a photoelectric cell to monitor dialysate clarity for blood","Measuring conductivity","Measuring temperature"],
   ans:1, expl:"The blood leak detector uses a photoelectric cell in the dialysate outflow line; blood absorbs light and triggers the alarm."},
  {topic:"Hemodialysis", q:"If a blood leak is detected in the dialysate, the nurse should:",
   opts:["Return the blood to the patient","Not return the blood due to the risk of mixing dialysate with blood","Increase blood flow","Continue the treatment"],
   ans:1, expl:"If a blood leak is found, the blood should not be returned because of the potential for mixing dialysate with the patient's blood."},
  {topic:"Hemodialysis", q:"For a pre-dialysis serum sodium <130 mEq/L, correction must be gradual because rapid correction can cause:",
   opts:["Osmotic demyelination syndrome","Hyperkalemia","Pulmonary edema","Hemolysis"],
   ans:0, expl:"Rapid correction of low sodium can cause osmotic demyelination syndrome (dysphagia, dysarthria, altered mental status, quadriplegia)."},
  {topic:"Hemodialysis", q:"Which dialysate calcium concentration is associated with twice the risk of sudden cardiac death?",
   opts:["3.5 mEq/L or greater","Less than 2.5 mEq/L","2.5-3 mEq/L","4.0 mEq/L"],
   ans:1, expl:"Dialysate calcium <2.5 mEq/L is associated with twice the risk of sudden cardiac death; 3.5+ is linked to all-cause mortality."},
  {topic:"Hemodialysis", q:"What is the definition of dry weight?",
   opts:["The patient's heaviest weight","The weight at which the patient is normotensive, not edematous, and without adverse symptoms","The predialysis weight","The ideal body weight"],
   ans:1, expl:"Dry weight is the weight at which the patient is normotensive, not edematous, and does not experience adverse symptoms during treatment."}
];

// ============================================================
// PERITONEAL DIALYSIS questions (from Mometrix guide)
// ============================================================
const EXTRA_PD_QUESTIONS = [
  {topic:"Peritoneal Dialysis", q:"What material are most PD catheters made from today?",
   opts:["Polyurethane","Silicone","PVC","Polyethylene"],
   ans:1, expl:"Most PD catheters are made from silicone. Polyurethane production ceased in 2010 due to vulnerability to mupirocin."},
  {topic:"Peritoneal Dialysis", q:"The cuff of the PD catheter is made from:",
   opts:["Silicone","Dacron polyester fiber","Teflon","Nylon"],
   ans:1, expl:"The PD catheter cuff is made from Dacron polyester fiber, and can be single or double cuffed."},
  {topic:"Peritoneal Dialysis", q:"Which catheter organization recommends double-cuff PD catheters?",
   opts:["ANNA","ISPD (International Society for Peritoneal Dialysis)","KDIGO","AAMI"],
   ans:1, expl:"ISPD recommends double-cuff catheters because the extra cuff may prevent organisms from entering the peritoneal cavity."},
  {topic:"Peritoneal Dialysis", q:"PD catheters should be placed at least how long before PD is initiated?",
   opts:["48 hours","2 weeks","1 month","6 hours"],
   ans:1, expl:"PD catheters should be placed at least 2 weeks before PD to allow tissue ingrowth and prevent leaks."},
  {topic:"Peritoneal Dialysis", q:"Urgent-start PD is initiated within how long of catheter placement?",
   opts:["24 hours","72 hours","1 week","2 weeks"],
   ans:1, expl:"Urgent-start PD is initiated within 72 hours of catheter placement, using low fill volumes of 0.5-1.5 L."},
  {topic:"Peritoneal Dialysis", q:"The most commonly added osmotic agent in PD dialysate to increase ultrafiltration is:",
   opts:["Icodextrin","Dextrose (glucose)","Amino acids","Mannitol"],
   ans:1, expl:"Dextrose is the most commonly added osmotic agent used to increase UF. Standard concentrations are 1.5%, 2.5%, 3.5%, 4.25%."},
  {topic:"Peritoneal Dialysis", q:"Icodextrin 7.5% solution is used in PD for:",
   opts:["Patients with excessive UF","Patients with insufficient UF or high transporters","Low transporters only","All patients"],
   ans:1, expl:"Icodextrin is considered for patients with insufficient UF, high transporters, and those needing to limit glucose exposure."},
  {topic:"Peritoneal Dialysis", q:"A major metabolic concern of icodextrin use is that it:",
   opts:["Causes hyperkalemia","Interferes with serum amylase testing","Increases glucose degradation","Causes hypernatremia"],
   ans:1, expl:"Icodextrin interferes with serum amylase testing, so serum lipase should be drawn when assessing for pancreatitis."},
  {topic:"Peritoneal Dialysis", q:"In CAPD, daytime exchanges usually last:",
   opts:["30-60 minutes","4-6 hours","8-10 hours","12-16 hours"],
   ans:1, expl:"In CAPD, daytime exchanges usually last 4-6 hours and the overnight exchange lasts 8-10 hours."},
  {topic:"Peritoneal Dialysis", q:"In continuous cycling PD (CCPD), the overnight dwell time for each exchange is generally:",
   opts:["15-30 minutes","90-120 minutes","6 hours","30 minutes"],
   ans:1, expl:"In CCPD, dwell time is generally 90-120 minutes for each exchange."},
  {topic:"Peritoneal Dialysis", q:"PD solution should be warmed:",
   opts:["Long before use in an incubator","Only to body temperature and shortly before use","In a microwave","Only to room temperature"],
   ans:1, expl:"PD fluid should be warmed only to body temperature shortly before use. Microwaving and water baths are not recommended."},
  {topic:"Peritoneal Dialysis", q:"Which warming method is NOT recommended for PD solution?",
   opts:["Incubator","Heating cabinet","Water bath","Dry heating"],
   ans:2, expl:"Water baths are not recommended because water is contaminated with microorganisms and can contaminate the system."},
  {topic:"Peritoneal Dialysis", q:"The most common symptom of peritonitis is:",
   opts:["Fever","Cloudy peritoneal fluid","Hypotension","Bleeding"],
   ans:1, expl:"Patients often present with cloudy peritoneal fluid, rebound abdominal pain, nausea, vomiting, diarrhea, and fever."},
  {topic:"Peritoneal Dialysis", q:"Peritonitis is diagnosed by at least two of which criteria?",
   opts:["Clinical presentation, WBC >100/uL, positive culture","Fever, pain, diarrhea","Positive culture alone","Cloudy fluid only"],
   ans:0, expl:"Diagnosis requires at least two: clinical presentation (cloudy fluid, abdominal pain), effluent WBC >100/μL, or positive culture."},
  {topic:"Peritoneal Dialysis", q:"A neutrophil count of what percentage in the PD effluent indicates peritonitis?",
   opts:["10%","25%","50% or more","75%"],
   ans:2, expl:"A neutrophil count of 50% or more indicates peritonitis."},
  {topic:"Peritoneal Dialysis", q:"ISPD recommends empiric antibiotic therapy for peritonitis be started:",
   opts:["After culture results","As soon as cloudy effluent is seen","After 48 hours","Only if fever develops"],
   ans:1, expl:"ISPD recommends starting antibiotics as soon as cloudy effluent is seen; do not delay for cell count or Gram stain results."},
  {topic:"Peritoneal Dialysis", q:"Which route of antibiotic administration is more effective for peritonitis?",
   opts:["IV","Intraperitoneal (IP)","Oral","Intramuscular"],
   ans:1, expl:"IP administration is more effective than IV dosing for peritonitis."},
  {topic:"Peritoneal Dialysis", q:"The most common type of hernia in PD patients is:",
   opts:["Inguinal","Umbilical","Incisional","Hiatal"],
   ans:1, expl:"The most common type of hernia in PD patients is an umbilical hernia."},
  {topic:"Peritoneal Dialysis", q:"A pleural cavity leak (hydrothorax) from PD typically occurs:",
   opts:["On the right side","On the left side","Bilaterally","In the lower abdomen"],
   ans:0, expl:"A pleural cavity leak usually leaks into one pleural cavity, typically the right side."},
  {topic:"Peritoneal Dialysis", q:"The first and most common symptom of a pleural cavity leak (hydrothorax) is:",
   opts:["Chest pain","Dyspnea","Hemoptysis","Cough"],
   ans:1, expl:"Dyspnea occurs immediately after dialysis initiation and gradually increases; it is the first and most common symptom."},
  {topic:"Peritoneal Dialysis", q:"Encapsulating peritoneal sclerosis (EPS) is most associated with:",
   opts:["Short time on PD","Length of time on PD (longer duration)","Low transporter status","Young age"],
   ans:1, expl:"The largest known risk factor for EPS is the length of time on PD; ISPD suggests considering risk after 3-5 years."},
  {topic:"Peritoneal Dialysis", q:"Which medication is widely used worldwide to treat EPS?",
   opts:["Prednisolone","Tamoxifen","Cyclophosphamide","Azathioprine"],
   ans:1, expl:"Prednisolone is first-line in Japan, but tamoxifen is more widely used worldwide for EPS."},
  {topic:"Peritoneal Dialysis", q:"Peritoneal membrane failure (UF failure) is defined by failure to achieve at least how much net ultrafiltrate in a 4-hour dwell with 4.25% dextrose?",
   opts:["200 mL","400 mL","600 mL","1000 mL"],
   ans:1, expl:"UF failure is failure to achieve at least 400 mL of net ultrafiltrate in a 4-hour dwell using 4.25% dextrose (rule of four)."},
  {topic:"Peritoneal Dialysis", q:"Hypokalemia is more commonly seen in which patient group?",
   opts:["HD patients","PD patients","Both equally","Children"],
   ans:1, expl:"Hypokalemia affects approximately 30% of PD patients, more than in HD patients, partly due to insulin-driven potassium uptake."}
];

// ============================================================
// TRANSPLANT questions (from Mometrix guide)
// ============================================================
const EXTRA_TRANSPLANT_QUESTIONS = [
  {topic:"Transplant", q:"Which organ is typically removed first during deceased donor organ recovery?",
   opts:["Kidneys","Heart and/or lungs","Pancreas","Liver"],
   ans:1, expl:"The heart and/or lungs are removed first, then the pancreas and/or liver. Kidneys are removed last and flushed in situ with cold preservation solution."},
  {topic:"Transplant", q:"The most commonly used method of organ preservation is:",
   opts:["Cold storage","Hypothermic pulsatile perfusion","Warm storage","Cryopreservation"],
   ans:0, expl:"Cold storage is the most commonly used method. Hypothermic pulsatile storage allows longer storage time."},
  {topic:"Transplant", q:"After how long a warm ischemia time does the risk of delayed function or nonfunction increase significantly?",
   opts:["5 minutes","20 minutes","1 hour","2 hours"],
   ans:1, expl:"After a 20-minute warm ischemia time, the risk of delayed function or nonfunction increases significantly."},
  {topic:"Transplant", q:"The kidney donor profile index (KDPI):",
   opts:["Estimates the risk of posttransplant kidney failure from a deceased donor","Measures kidney size","Predicts rejection type","Determines immunosuppression dose"],
   ans:0, expl:"KDPI estimates the risk of posttransplant kidney failure from a deceased donor. Higher scores indicate lower donor quality."},
  {topic:"Transplant", q:"A contraindication for deceased organ donation is:",
   opts:["Presence of malignancy (except some skin cancers or brain tumors)","Brain death","Heart-beating donor","Informed consent from family"],
   ans:0, expl:"For deceased donation, there must be no malignancy (except some skin cancers or brain tumors), no transmissible disease, no uncontrolled hypertension."},
  {topic:"Transplant", q:"Which is a contraindication to kidney transplantation?",
   opts:["Current or recent malignancy (except noninvasive skin cancer)","Noncompliance resolved","Well-controlled infection","Stable psychiatric status"],
   ans:0, expl:"Any current or recent malignancy is a contraindication except noninvasive skin cancers. Untreated infection and active autoimmune disease also exclude."},
  {topic:"Transplant", q:"Hyperacute rejection can occur:",
   opts:["Months after transplant","Minutes to up to 3 days after transplant","Years after transplant","Only after dialysis"],
   ans:1, expl:"Hyperacute rejection occurs minutes after transplant or can be delayed up to 3 days. It is not treatable and requires transplant nephrectomy."},
  {topic:"Transplant", q:"Hyperacute rejection is prevented by:",
   opts:["Crossmatch testing before surgery","Higher steroid doses","More dialysis","Plasmapheresis"],
   ans:0, expl:"Performing crossmatch testing before surgery can prevent hyperacute rejection."},
  {topic:"Transplant", q:"Accelerated rejection occurs between:",
   opts:["24 hours and 7 days after transplant","Minutes after transplant","Months after transplant","1 year after transplant"],
   ans:0, expl:"Accelerated rejection occurs between 24 hours and 7 days following transplant due to preformed antidonor antibodies."},
  {topic:"Transplant", q:"The most common form of early rejection is:",
   opts:["Cell-mediated T cell acute rejection","Hyperacute rejection","Chronic rejection","Antibody-mediated rejection"],
   ans:0, expl:"The most common form of early rejection is cell-mediated T cell acute rejection, occurring in 15-25% of patients in the first 3 months."},
  {topic:"Transplant", q:"Acute cellular rejection is treated with:",
   opts:["Increased glucocorticoids","Anticoagulants","Antiviral therapy","Transplant nephrectomy"],
   ans:0, expl:"Acute cellular rejection is treated with increased glucocorticoids."},
  {topic:"Transplant", q:"Which agent is used to treat antibody-mediated acute rejection?",
   opts:["IVIG, plasma exchange, and anti-CD20 B cell antibody","Glucocorticoids alone","Antibiotics","Heparin"],
   ans:0, expl:"Antibody-mediated acute rejection can be treated with plasma exchange, IVIG, and anti-CD20 (rituximab)."},
  {topic:"Transplant", q:"The most common cause of long-term kidney transplant loss is:",
   opts:["Interstitial fibrosis/tubular atrophy","Hyperacute rejection","Acute rejection","Infection"],
   ans:0, expl:"Interstitial fibrosis and tubular atrophy is the most common cause of long-term kidney transplant loss."},
  {topic:"Transplant", q:"Which immunosuppressant is preferred over cyclosporine in kidney transplant?",
   opts:["Tacrolimus","Azathioprine","Sirolimus","Mycophenolate"],
   ans:0, expl:"Tacrolimus is preferred because it shows a larger reduction in acute rejection and better graft survival than cyclosporine."},
  {topic:"Transplant", q:"A common side effect of tacrolimus is:",
   opts:["Diabetes, hypertension, neurotoxicity, alopecia","Gingival hyperplasia","Hirsutism","Hyperlipidemia only"],
   ans:0, expl:"Tacrolimus can cause diabetes, hypertension, glucose intolerance, neurotoxicity, and alopecia."},
  {topic:"Transplant", q:"Cyclosporine is associated with:",
   opts:["Hirsutism and gingival hyperplasia","Alopecia","Peripheral neuropathy","Pancreatitis"],
   ans:0, expl:"Cyclosporine can cause hypertension, hyperlipidemia, hirsutism, and gingival hyperplasia."},
  {topic:"Transplant", q:"Which medication carries a risk of miscarriage and congenital malformations in the first trimester?",
   opts:["Mycophenolate (CellCept)","Tacrolimus","Prednisone","Belatacept"],
   ans:0, expl:"Mycophenolate carries an increased risk of miscarriage and congenital malformations; patients of childbearing potential must be counseled."},
  {topic:"Transplant", q:"Patients taking sirolimus or everolimus (mTOR inhibitors) must avoid:",
   opts:["Grapefruit and grapefruit juice","Green tea","Dairy","High-fiber foods"],
   ans:0, expl:"Patients on sirolimus/everolimus must avoid grapefruit and grapefruit juice due to medication interactions."},
  {topic:"Transplant", q:"Belatacept (Nulojix) should NOT be given to patients who are:",
   opts:["Epstein-Barr virus IgG negative","Young","Diabetic","Hypertensive"],
   ans:0, expl:"Belatacept should not be given to EBV IgG negative patients due to increased risk of posttransplant lymphoproliferative disease."},
  {topic:"Transplant", q:"Which is the first-line treatment for BK nephropathy?",
   opts:["Leflunomide","Tacrolimus","Cidofovir","Acyclovir"],
   ans:0, expl:"Leflunomide is first-line for BK nephropathy because it is not nephrotoxic and has immunosuppressive and antiviral qualities."},
  {topic:"Transplant", q:"CMV is most serious in which scenario?",
   opts:["Donor CMV-positive, recipient CMV-negative (primary CMV)","Donor and recipient both negative","Recipient positive","Donor negative"],
   ans:0, expl:"Primary CMV (donor positive, recipient negative) is the most serious and can be life-threatening."},
  {topic:"Transplant", q:"The most life-threatening infection in kidney transplant patients is:",
   opts:["Bacterial pneumonia","P. jiroveci pneumonia","CMV","UTI"],
   ans:0, expl:"Bacterial pneumonia is the most life-threatening infection for kidney transplant patients, though PJP is also dangerous."},
  {topic:"Transplant", q:"Which medication can be used to prevent P. jiroveci pneumonia?",
   opts:["Bactrim (single-strength) or dapsone","Acyclovir","Vancomycin","Aspirin"],
   ans:0, expl:"PJP is usually preventable with prophylactic antibiotics such as Bactrim, pentamidine, or dapsone."},
  {topic:"Transplant", q:"Malignancy rates are how much higher in transplant patients than the general population?",
   opts:["Two to four times higher","Ten times higher","Slightly higher","No higher"],
   ans:0, expl:"Malignancy rates are two to four times higher in transplant patients than in the regular population."},
  {topic:"Transplant", q:"A kidney transplant recipient who desires pregnancy should wait at least how long after transplant?",
   opts:["1 year","3 months","6 months","3 years"],
   ans:0, expl:"Patients should wait at least 1 year following transplant surgery and until creatinine is <2 mg/dL."}
];

// ============================================================
// ACUTE THERAPIES (CRRT/SLED) questions (from Mometrix guide)
// ============================================================
const EXTRA_ACUTE_QUESTIONS = [
  {topic:"Acute Therapies", q:"Which method is best for removing midsized to large molecules like beta-2 microglobulin?",
   opts:["Diffusion","Convection","Adsorption","Osmosis"],
   ans:1, expl:"Convection is the best way to remove midsized to large molecules, using a pressure gradient (TMP) to move plasma and solutes across the membrane."},
  {topic:"Acute Therapies", q:"Diffusion works best for which type of molecules?",
   opts:["Large molecules","Small molecules like urea","Protein-bound toxins","Albumin"],
   ans:1, expl:"Diffusion works best for small molecules such as urea, moving solutes from higher to lower concentration."},
  {topic:"Acute Therapies", q:"CRRT is primarily used in critically ill patients who are:",
   opts:["Hemodynamically unstable / hypotensive","Stable and euvolemic","On oral intake","Ambulatory"],
   ans:0, expl:"CRRT is used in critical care for hemodynamically unstable patients who cannot tolerate the rapid fluid shifts of intermittent HD."},
  {topic:"Acute Therapies", q:"Slow low-efficiency dialysis (SLED) differs from standard HD in that it:",
   opts:["Runs at low blood flow rates for a longer time","Uses higher blood flow","Removes fluid rapidly","Uses no dialysate"],
   ans:0, expl:"SLED runs at low blood flow rates for a longer time (up to 12 hours), removing fluid and solutes with fewer hypotension episodes."},
  {topic:"Acute Therapies", q:"Slow continuous UF (SCUF) is used for:",
   opts:["Solute control","Volume control in diuretic-resistant fluid overload","Both fluid and solute removal","Toxin removal"],
   ans:1, expl:"SCUF achieves volume control but minimal solute clearance, making it poor for solute control."},
  {topic:"Acute Therapies", q:"Continuous venovenous hemofiltration (CVVH) removes solutes by which mechanism?",
   opts:["Diffusion only","Convection only","Adsorption only","Osmosis only"],
   ans:1, expl:"CVVH uses convection only, driven by a TMP gradient to produce ultrafiltrate which is replaced with crystalloid."},
  {topic:"Acute Therapies", q:"Continuous venovenous hemodialysis (CVVHD) achieves clearance primarily by:",
   opts:["Diffusion","Convection","Adsorption","Ultrafiltration only"],
   ans:0, expl:"CVVHD uses dialysate running countercurrently; clearance occurs primarily via diffusion."},
  {topic:"Acute Therapies", q:"CVVHDF (hemodiafiltration) removes solutes by:",
   opts:["Diffusion only","Convection only","Both diffusion and convection","Neither"],
   ans:2, expl:"CVVHDF adds a sterile replacement solution, allowing solute removal via both diffusion and convection."},
  {topic:"Acute Therapies", q:"SLED/CRRT initiation is recommended when blood pH falls below:",
   opts:["7.2","7.0","7.4","6.8"],
   ans:0, expl:"SLED/CRRT initiation is recommended when pH falls below 7.2 or serum bicarbonate below 12-15 mmol/L."},
  {topic:"Acute Therapies", q:"For overdose/toxin removal, HD is preferred over CRRT because:",
   opts:["HD clears toxins faster","CRRT is safer for all patients","HD is always available","CRRT cannot remove drugs"],
   ans:0, expl:"For overdose, the goal is rapid clearance, so HD is preferred even in hemodynamically unstable patients."},
  {topic:"Acute Therapies", q:"KDIGO recommends what effluent volume for AKI patients on CRRT?",
   opts:["10-15 mL/kg/hr","20-25 mL/kg/hr","30-40 mL/kg/hr","50 mL/kg/hr"],
   ans:1, expl:"KDIGO recommends an effluent volume of 20-25 mL/kg/hr for AKI patients on CRRT."},
  {topic:"Acute Therapies", q:"KDIGO recommends the prescribed CRRT effluent volume be increased by what percent to account for dialyzer clogging?",
   opts:["10%","25%","50%","5%"],
   ans:1, expl:"KDIGO recommends increasing the prescribed effluent volume by 25% to account for the discrepancy between prescribed and delivered dose."},
  {topic:"Acute Therapies", q:"Which buffer is most commonly recommended by KDIGO for CRRT in critically ill patients?",
   opts:["Acetate","Lactate","Bicarbonate","Citrate"],
   ans:2, expl:"Bicarbonate is most commonly used and recommended by KDIGO because it maintains hemodynamic stability and corrects acidosis."},
  {topic:"Acute Therapies", q:"Which anticoagulant has become the anticoagulant of choice for AKI patients on CRRT?",
   opts:["Heparin","Citrate","Warfarin","Enoxaparin"],
   ans:1, expl:"Citrate has become the anticoagulant of choice because heparin has questionable safety in critically ill patients."},
  {topic:"Acute Therapies", q:"Heparin is the most common anticoagulant in CRRT because:",
   opts:["It is highly protein-bound and not readily removed","It is cheap","It has no side effects","It is the only option"],
   ans:0, expl:"Heparin is highly protein bound, so it is not readily removed during the process, making it a common anticoagulant."},
  {topic:"Acute Therapies", q:"The heparin bolus for CRRT is given how long before initiation?",
   opts:["5 minutes before","1 hour before","Immediately at start","24 hours before"],
   ans:0, expl:"A bolus of 10-30 U/kg is administered 5 minutes prior to SLED or CRRT initiation to heparinize the systemic circulation."},
  {topic:"Acute Therapies", q:"Patients who have experienced HIT must not receive heparin because of the risk of:",
   opts:["White clot syndrome","Bleeding","Anaphylaxis","Hyperkalemia"],
   ans:0, expl:"In HIT, heparin causes decreased platelets and a potentially deadly clot called white clot syndrome."},
  {topic:"Acute Therapies", q:"When citrate is used for anticoagulation in CRRT, the dialysate must NOT contain:",
   opts:["Calcium","Potassium","Magnesium","Sodium"],
   ans:0, expl:"The dialysate must not contain calcium for citrate to be effective, since citrate binds ionized calcium."},
  {topic:"Acute Therapies", q:"With citrate anticoagulation, ionized calcium levels should be monitored:",
   opts:["Every 30-60 minutes initially","Once daily","Weekly","Monthly"],
   ans:0, expl:"Ionized calcium must be tested every 30-60 minutes per hospital policy, and after any circuit or dosing change."},
  {topic:"Acute Therapies", q:"For CRRT, a temporary non-tunneled HD catheter can be used for up to:",
   opts:["3 weeks","1 week","6 months","24 hours"],
   ans:0, expl:"A temporary non-tunneled HD catheter can be used for CRRT for up to 3 weeks, then a cuffed tunneled catheter should be placed."},
  {topic:"Acute Therapies", q:"The preferred site for a CRRT dialysis catheter is:",
   opts:["Right internal jugular vein","Left subclavian","Femoral","Left internal jugular"],
   ans:0, expl:"The right internal jugular vein is preferred because it has fewer complications, is easier to place, and gets better blood flow."},
  {topic:"Acute Therapies", q:"Which dialysis access is generally NOT appropriate for CRRT?",
   opts:["AV fistula/graft","Temporary catheter","Tunneled catheter","Non-tunneled catheter"],
   ans:0, expl:"AV fistulas and grafts are generally not appropriate for CRRT/SLED due to risk of needle dislodgement and access damage."},
  {topic:"Acute Therapies", q:"The primary cause of AKI in the critical care unit is:",
   opts:["Sepsis","Nephrotoxins","Obstruction","Hypovolemia"],
   ans:0, expl:"Sepsis is the primary cause of AKI in the ICU; nearly 50% of critically ill patients with sepsis develop AKI."},
  {topic:"Acute Therapies", q:"CRRT is preferred over HD to correct which electrolyte slowly to prevent neurologic problems?",
   opts:["Sodium","Potassium","Calcium","Chloride"],
   ans:0, expl:"Sodium is better corrected with CRRT because the plasma sodium can be manipulated more slowly to avoid cerebral edema."},
  {topic:"Acute Therapies", q:"Hypernatremia should be corrected at what rate with CRRT?",
   opts:["Less than 0.5 mEq/L/hr","2 mEq/L/hr","5 mEq/L/hr","10 mEq/L/hr"],
   ans:0, expl:"Hypernatremia should be corrected at <0.5 mEq/L/hr with a maximum of 12 mEq/L in 24 hours to avoid cerebral edema."},
  {topic:"Acute Therapies", q:"Which type of molecules are NOT removed by CRRT because they are too large?",
   opts:["Drugs larger than 15,000 daltons","Drugs smaller than 2,000 daltons","Urea","Creatinine"],
   ans:0, expl:"Drugs larger than 15,000 daltons are too large to cross the dialyzer membrane and will not be removed via CRRT."},
  {topic:"Acute Therapies", q:"Citrate toxicity can occur in patients with:",
   opts:["Liver disease or inadequate perfusion","Hyperkalemia","Excess calcium","Normal liver function"],
   ans:0, expl:"Liver disease, inadequate perfusion, and dialyzer clotting can lead to citrate toxicity where citrate accumulates in the peripheral circulation."},
  {topic:"Acute Therapies", q:"For a MAP below 60 mmHg during CRRT/SLED, the nurse should:",
   opts:["Stop UF and give a normal saline bolus as ordered","Increase the UF rate","Increase heparin","Stop the treatment permanently"],
   ans:0, expl:"For MAP <60 mmHg, UF should be stopped and a normal saline bolus given as ordered; lower dialysate temperature may help."},
  {topic:"Acute Therapies", q:"When citrate is used, citrate and calcium IV infusions must be stopped immediately whenever:",
   opts:["The blood pump is stopped","The patient eats","The treatment finishes","The temperature drops"],
   ans:0, expl:"Citrate and calcium infusions must stop immediately whenever the blood pump is stopped to prevent bolus administration."},
  {topic:"Acute Therapies", q:"Which dialysis solution buffer also provides anticoagulant properties?",
   opts:["Citrate","Acetate","Lactate","Bicarbonate"],
   ans:0, expl:"Citrate in the dialysate provides anticoagulant properties and metabolizes in the liver to bicarbonate."}
];

// ============================================================
// MERGE all extended question banks into the main QUESTIONS array
// ============================================================
QUESTIONS.push(
  ...(typeof EXTRA_KIDNEY_QUESTIONS !== 'undefined' ? EXTRA_KIDNEY_QUESTIONS : []),
  ...(typeof EXTRA_CKD_QUESTIONS !== 'undefined' ? EXTRA_CKD_QUESTIONS : []),
  ...(typeof EXTRA_HD_QUESTIONS !== 'undefined' ? EXTRA_HD_QUESTIONS : []),
  ...(typeof EXTRA_PD_QUESTIONS !== 'undefined' ? EXTRA_PD_QUESTIONS : []),
  ...(typeof EXTRA_TRANSPLANT_QUESTIONS !== 'undefined' ? EXTRA_TRANSPLANT_QUESTIONS : []),
  ...(typeof EXTRA_ACUTE_QUESTIONS !== 'undefined' ? EXTRA_ACUTE_QUESTIONS : [])
);
