// BATCH 4: NEW questions from ANNA Module 5 (Transplant).
// Verified against module text. obj: 2=interventions, 5=CKD complications, 1=pathology.
const NEW_QUESTIONS_MOD5 = [
  {"topic":"Transplant","q":"Which statement best describes the survival benefit of kidney transplantation compared to dialysis?","opts":["Patients on dialysis live longer than transplant recipients","Patients with a successful kidney transplant live longer and report better quality of life than those on dialysis","There is no survival difference between transplant and dialysis","Transplant patients require more diet and fluid restrictions"],"ans":1,"expl":"Studies show patients with a successful kidney transplant live longer than those treated with dialysis, and many report better quality of life, including returning to work and traveling without diet/fluid restrictions.","obj":2},
  {"topic":"Transplant","q":"In the workup before a kidney transplant, a negative crossmatch with a deceased donor means:","opts":["The patient cannot receive the organ","The recipient's serum does not react against the donor's cells, so the organ may be accepted","The donor has pre-formed antibodies","Tissue typing was not performed"],"ans":1,"expl":"A negative crossmatch indicates the recipient's serum does not have pre-formed antibodies against the donor's cells, permitting transplantation. A positive crossmatch risks hyperacute rejection.","obj":2},
  {"topic":"Transplant","q":"Which type of rejection is triggered by a primary humoral B-cell response from prior sensitization, occurs within minutes to 24 hours, and is very rare?","opts":["Acute T-cell rejection","Hyperacute rejection","Chronic allograft nephropathy","Accelerated rejection"],"ans":1,"expl":"Hyperacute rejection is caused by a primary humoral B-cell response from the recipient's prior sensitivity to donor tissue. Onset is minutes to 24 hours, with abrupt loss of renal function, and it is very rare. Treatments include transplant nephrectomy.","obj":1},
  {"topic":"Transplant","q":"A patient develops fever, profound oliguria, and rapid loss of kidney function days after transplant, from pre-formed cytotoxic antibodies. This is BEST described as:","opts":["Hyperacute rejection","Accelerated rejection","Acute rejection","Chronic rejection"],"ans":1,"expl":"Accelerated rejection is caused by pre-formed cytotoxic antibodies (similar to hyperacute) and occurs over days. It presents with profound oliguria, fever, rapid loss of function, edema, graft tenderness, and hypertension. Treatment includes plasmapheresis, IVIG, or transplant nephrectomy.","obj":1},
  {"topic":"Transplant","q":"Which is the most common form of early rejection following kidney transplant?","opts":["Hyperacute rejection","Chronic allograft nephropathy","Acute T-cell (cell-mediated/ cellular) rejection","Humoral antibody rejection alone"],"ans":2,"expl":"Acute T-cell (cell-mediated, cellular) rejection is the most common form of early rejection. It occurs days to weeks post-transplant. If donor-specific antibody is present, treatment may require plasma exchange.","obj":1},
  {"topic":"Transplant","q":"Which type of rejection is the most common cause of long-term allograft loss, also called interstitial fibrosis and tubular atrophy (IFTA)?","opts":["Hyperacute rejection","Chronic allograft nephropathy","Accelerated rejection","Superacute rejection"],"ans":1,"expl":"Chronic allograft nephropathy (chronic rejection or IFTA) is the most common cause of long-term allograft loss. It has an onset of months to years, with proteinuria, rising creatinine, hypertension, and edema. Diagnosis is by renal biopsy.","obj":1},
  {"topic":"Transplant","q":"The gold standard for diagnosing most transplant rejection is:","opts":["Serum creatinine trend","Renal biopsy","Renal ultrasound","Urine protein measurement"],"ans":1,"expl":"Renal transplant biopsy is the gold standard for diagnosing rejection. It can differentiate causes of renal deterioration, hematuria, or proteinuria in the transplanted kidney.","obj":2},
  {"topic":"Transplant","q":"Which immunosuppressive agent is a polyclonal antibody that depletes T-cell lymphocytes, given at induction and requiring pre-medications to reduce infusion-related reactions?","opts":["Tacrolimus","Thymoglobulin (ATG)","Mycophenolate mofetil (Cellcept)","Belatacept"],"ans":1,"expl":"Thymoglobulin (ATG) is a polyclonal antibody acting on T-cell surface receptors causing lymphocyte depletion. Doses are based on IBW, divided over 3-4 days, with pre-medications (acetaminophen, diphenhydramine, methylprednisolone) to reduce infusion reactions.","obj":2},
  {"topic":"Transplant","q":"A transplant patient on tacrolimus reports tingling in the hands and feet and elevated blood glucose. These are consistent with which class of immunosuppressant?","opts":["Antiproliferative agents","Calcineurin inhibitors","Corticosteroids","Monoclonal antibodies"],"ans":1,"expl":"Tacrolimus is a calcineurin inhibitor. Its side effects include nephrotoxicity, neurotoxicity, hypertension, and hyperkalemia, plus tacrolimus-specific tingling in hands/feet and hyperglycemia. Cyclosporine (also CNI) causes hirsutism and gingival hyperplasia.","obj":2},
  {"topic":"Transplant","q":"Which immunosuppressant is associated with delayed wound healing and hyperlipidemia, and is a TOR inhibitor?","opts":["Mycophenolate (Cellcept)","Azathioprine (Imuran)","Sirolimus (Rapamune)","Cyclosporine"],"ans":2,"expl":"Sirolimus (Rapamune) is a TOR inhibitor [sic — mechanistic target of rapamycin/mTOR inhibitor] with side effects of delayed wound healing and hyperlipidemia. Cellcept causes bone marrow suppression and GI issues; azathioprine causes liver dysfunction and alopecia.","obj":2},
  {"topic":"Transplant","q":"The nurse knows a major nursing implication when giving calcineurin inhibitors is to:","opts":["Encourage concurrent NSAID use for pain","Monitor drug levels plus kidney/liver function and avoid NSAIDs","Avoid monitoring blood glucose","Give with grapefruit juice"],"ans":1,"expl":"For calcineurin inhibitors (tacrolimus, cyclosporine), nursing implications include monitoring side effects, drug levels, kidney/liver function, and avoiding NSAIDs (which worsen nephrotoxicity).","obj":2},
  {"topic":"Transplant","q":"Hyperacute rejection is diagnosed by which combination of findings?","opts":["Slowly rising creatinine over months","Sharp, immediate decrease in renal function with abrupt cessation of urine output, swollen cyanotic kidney","Proteinuria and hypertension over years","Fever and elevated WBC days later"],"ans":1,"expl":"Hyperacute rejection presents with a sharp and immediate decrease in renal function, abrupt cessation of renal output, pain over the graft site, and a swollen and cyanotic kidney, within minutes to 24 hours. Diagnosis is by renal biopsy, renal scan, or surgical exploration.","obj":1},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD5};
