// BATCH 13: NEW questions from ANNA Module 2 (diuretics, mineral, acid-base).
// Verified against module text.
const NEW_QUESTIONS_MOD2C = [
  {"topic":"Kidney Disease","q":"Which diuretic class acts on the loop of Henle and remains often effective in advanced CKD compared to other diuretic classes?","opts":["Thiazide diuretics","Loop diuretics","Potassium-sparing diuretics","Carbonic anhydrase inhibitors"],"ans":1,"expl":"Loop diuretics alter water and sodium reabsorption from the loop of Henle, are often still effective in advanced CKD, and are used in heart failure. They include furosemide, bumetanide, torsemide, and ethacrynic acid.","obj":2},
  {"topic":"Kidney Disease","q":"Which of the following is a recognized adverse effect of loop diuretics?","opts":["Hypercalcemia","Hypokalemia, hypocalcemia, hyperuricemia, and hypomagnesemia","Hypernatremia","Metabolic alkalosis as the main effect"],"ans":1,"expl":"Loop diuretics can cause hypokalemia, hypocalcemia, hyperuricemia, and hypomagnesemia, and are associated with acute interstitial nephritis (AIN). They are also sulfa-cross-reactive (except ethacrynic acid).","obj":2},
  {"topic":"Kidney Disease","q":"Which loop diuretic does NOT share sulfa cross-reactivity in a patient with a sulfa allergy?","opts":["Furosemide","Bumetanide","Ethacrynic acid","Torsemide"],"ans":2,"expl":"Loop diuretics have cross-reactivity in those with sulfa allergy, with the exception of ethacrynic acid.","obj":2},
  {"topic":"Kidney Disease","q":"Which diuretic class can cause gynecomastia and menstrual changes along with hyperkalemia?","opts":["Thiazide diuretics","Aldosterone antagonists (e.g., spironolactone)","Loop diuretics","Carbonic anhydrase inhibitors"],"ans":1,"expl":"Aldosterone antagonists (spironolactone, eplerenone) prevent aldosterone binding in the distal tubule/collecting duct. Adverse effects include hyperkalemia and, for spironolactone, menstrual changes and gynecomastia. They can be combined with ACEi/ARBs and aid in reducing albuminuria.","obj":2},
  {"topic":"Kidney Disease","q":"The KDIGO 2022 recommended nonsteroidal mineralocorticoid receptor antagonist (ns-MRA) available in the US is:","opts":["Spironolactone","Eplerenone","Finerenone","Acetazolamide"],"ans":2,"expl":"Finerenone is the available ns-MRA in the US and is currently the recommended agent by KDIGO (2022), used to reduce albuminuria and slow progression in diabetic CKD with HTN.","obj":2},
  {"topic":"Kidney Disease","q":"Which of the following is an adverse effect of thiazide diuretics?","opts":["Hypocalcemia and hypouricemia","Hypokalemia, hypercalcemia, hyperuricemia, hyperglycemia, hyperlipidemia, and hypomagnesemia","Hypernatremia","Reduced risk of AIN"],"ans":1,"expl":"Thiazide diuretics can cause hypokalemia, hypercalcemia, hyperuricemia, hyperglycemia, hyperlipidemia, and hypomagnesemia, and are associated with AIN. They act in the distal convoluted tubule.","obj":2},
  {"topic":"Kidney Disease","q":"Which thiazide-like diuretic is often used in combination with a loop diuretic and may be useful even in advanced CKD stages 4-5?","opts":["Hydrochlorothiazide","Chlorthalidone","Metolazone","Chlorothiazide"],"ans":2,"expl":"Metolazone (thiazide-like) is often used in combination with a loop diuretic. Other thiazide agents are generally not useful in stages 4-5, but metolazone is the exception.","obj":2},
  {"topic":"Kidney Disease","q":"Potassium-sparing diuretics such as amiloride and triamterene can cause which adverse effect?","opts":["Hypokalemia","Hyperkalemia, hyponatremia, and metabolic alkalosis","Hypercalcemia","Hyperglycemia"],"ans":1,"expl":"Potassium-sparing diuretics (amiloride, triamterene) increase potassium reabsorption and can cause hyperkalemia, hyponatremia, and metabolic alkalosis. They produce less diuresis than thiazides and loops.","obj":2},
  {"topic":"Kidney Disease","q":"Carbonic anhydrase inhibitors are used to treat edema with metabolic alkalosis and which other condition?","opts":["Hyperkalemia","Open-angle or narrow-angle glaucoma and uric acid kidney stones","Gout exclusively","Hypertension with hypokalemia"],"ans":1,"expl":"Carbonic anhydrase inhibitors (acetazolamide, methazolamide) decrease bicarbonate/sodium reabsorption in the proximal tubule. They treat edema with metabolic alkalosis, open/narrow-angle glaucoma, and uric acid kidney stones.","obj":2},
  {"topic":"Kidney Disease","q":"A CKD patient on an ACEi and an aldosterone antagonist should be closely monitored for which complication?","opts":["Hypokalemia","Hyperkalemia (enhanced potassium-risking combination)","Hypernatremia","Metabolic acidosis"],"ans":1,"expl":"Both ACEi/ARBs and aldosterone antagonists (spironolactone/eplerenone) raise potassium; using them together increases the risk of hyperkalemia. Monitor potassium and kidney function, especially with dose changes.","obj":2},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD2C};
