// BATCH 10: NEW questions from ANNA Module 3 Part 2 (Hemodialysis vascular access).
// Verified against module text. obj: 3=phys/tech, 6=infection control.
const NEW_QUESTIONS_MOD3C = [
  {"topic":"Hemodialysis","q":"Which hemodialysis vascular access tends to last the longest and has the lowest rate of infection, thrombosis, and hospitalization?","opts":["Arteriovenous graft (AVG)","Arteriovenous fistula (AVF)","Central venous catheter (CVC)","Temporary non-tunneled catheter"],"ans":1,"expl":"The AVF has prolonged initial patency, lower infection/thrombosis/hospitalization, and tends to last the longest. However, it takes longer to mature and may have a higher initial failure rate.","obj":3},
  {"topic":"Hemodialysis","q":"An arteriovenous graft (AVG) is BEST described as:","opts":["A direct surgical connection between an artery and vein that matures over months","A surgically created connection of artery and vein using a soft synthetic tube (e.g., ePTFE), maturing in about 2-3 weeks","A large tube placed into a central vein","A temporary femoral catheter"],"ans":1,"expl":"An AVG is a surgically created connection of artery and vein using a soft tube, typically synthetic ePTFE/Teflon or composite polyurethane. It matures within 2-3 weeks but has higher rates of stenosis, thrombosis, and infection, and a shorter use life than an AVF.","obj":3},
  {"topic":"Hemodialysis","q":"The 'Rule of 6's' is used to evaluate maturation of an AV fistula. Which values are NOT part of this rule?","opts":["Access flow greater than 600 mL/min","Depth less than 6 mm","Diameter greater than 6 mm, length greater than 6 cm","Blood flow rate greater than 450 mL/min always"],"ans":3,"expl":"The rule of 6's for fistula maturation: access flow >600 mL/min, depth <6 mm, diameter >6 mm, length >6 cm. Maturation is evaluated within 6 weeks. Blood flow >450 is not part of the rule.","obj":3},
  {"topic":"Hemodialysis","q":"During assessment of an AV fistula, a continuous low-pitched sound heard over the access from turbulence is called a:","opts":["Thrill","Bruit","Pulse","Steal"],"ans":1,"expl":"A bruit is a low-pitched sound heard over the access from turbulence; it should be strong and continuous. A thrill is the sensation (purring/vibration) felt from turbulence of high-pressure arterial blood entering the low-pressure venous system.","obj":3},
  {"topic":"Hemodialysis","q":"The nurse identifies a 'thrill' over a hemodialysis AV fistula as:","opts":["A continuous low-pitched sound","A purring/vibration sensation created by turbulence of high-pressure arterial blood merging into the low-pressure venous system, with no strong pulse","A strong bounding pulse","A cold pale hand"],"ans":1,"expl":"A thrill is the purring/vibration felt from the turbulence created when high-pressure arterial blood merges into the low-pressure venous system. It should be strong and continuous with no strong pulse.","obj":3},
  {"topic":"Hemodialysis","q":"Which dialysis access complication results from diversion of blood from the peripheral circulation, causing pain, a cold/pale hand, and poor capillary refill?","opts":["Venous stenosis","Steal syndrome","High output cardiac failure","Pseudoaneurysm"],"ans":1,"expl":"Steal syndrome is caused by diversion of blood from the peripheral circulation. Risk factors include elderly, PVD, diabetes, and multiple access surgeries. It presents with pain distal to the anastomosis, cold/pale hand, impaired function, and poor capillary refill. Mild cases use a mitten, hand exercise, and massage; severe cases need surgery/ligation.","obj":3},
  {"topic":"Hemodialysis","q":"A dialysis patient presents with outflow stenosis evidenced by bruit/thrill changes and decreased blood flow rate. Which is a recognized intervention?","opts":["Ligation of the access","Balloon angioplasty and/or stent placement or surgical revision","Immediate access removal","Restrict fluid intake only"],"ans":1,"expl":"Venous stenosis (narrowing of the lumen) is diagnosed by presentation of signs/symptoms and US detection. Interventions include balloon angioplasty, stent placement, and surgical revision.","obj":3},
  {"topic":"Hemodialysis","q":"Which statement about an aneurysm of a dialysis access is TRUE?","opts":["It is caused by a wall defect from excessive pressure","It is an abnormal blood-filled dilation of the vessel wall, associated with repetitive cannulation, outflow stenosis, and hypertension","It only occurs in grafts","It requires no intervention"],"ans":1,"expl":"An aneurysm is an abnormal blood-filled dilation of the vessel wall, caused by repeated cannulation to the same area, outflow stenosis/occlusion, or persistent hypertension. Signs include out-pouched areas and thinning (shiny, tight) with possible bleeding/infection/ulceration. Surgical repair (plication or stenting) may be needed.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a common finding and cause related to central venous stenosis in a dialysis patient?","opts":["Occurs without any prior line history","A history of central venous catheters, compression by surrounding structures, or pacemaker/ICD wires, causing arm swelling and collateral veins","Never causes symptoms","Only related to high blood pressure"],"ans":1,"expl":"Central venous stenosis is caused by a history of CVCs, arterialized high flow in central veins, compression, or pacemaker/ICD wires. It presents with swelling, collateral veins, and discomfort that increases during dialysis. Treatment includes angioplasty with possible stent.","obj":3},
  {"topic":"Hemodialysis","q":"A non-tunneled central venous catheter should be used for no more than what duration?","opts":["6 months","3 months","2 weeks","1 year"],"ans":2,"expl":"Non-tunneled catheters are used no more than 2 weeks. Tunneled cuff catheters are used for longer term while waiting for AVF/AVG or PD catheter placement/maturation or a live donor, or when not a candidate for AVF/AVG.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a disadvantage of the femoral dialysis catheter site?","opts":["It is the preferred site for transplant candidates","It has the highest infection rates and should be avoided in transplant candidates","It causes no complications","It has the lowest infection risk"],"ans":1,"expl":"The femoral site has the highest infection rates and should be avoided in transplant candidates. The right internal jugular is preferred. Subclavian is to be avoided unless all sites are exhausted (risk of central stenosis).","obj":6},
  {"topic":"Hemodialysis","q":"Which statement describes the buttonhole cannulation technique?","opts":["Use different sites each time (rope ladder)","Fistulas only, using the same holes each time to create a scar tunnel, enabling faster less painful cannulation with blunt needles","Grafts only, with a 45-degree angle","Requires no special needles"],"ans":1,"expl":"Buttonhole cannulation is for fistulas only, using the same holes each time to create a tunnel of scar tissue (like a pierced earring). Blunt needles prevent tissue damage and allow faster cannulation with less pain. Rope ladder uses different sites to reduce aneurysm/tearing risk.","obj":3},
  {"topic":"Hemodialysis","q":"A patient develops swelling, pain, and bruising at the access site during dialysis because the needle is no longer in the access. This is called:","opts":["Steal syndrome","Infiltration","Thrombosis","High output failure"],"ans":1,"expl":"Infiltration occurs when the needle is no longer in the access (before, during, or after dialysis), causing edema, pain, and bruising. Treatment is immediate ice application for 24 hours, warm compresses, and possible rest.","obj":3},
  {"topic":"Hemodialysis","q":"Which is the FIRST-line management a nurse applies to an access infiltration?","opts":["Warm compression immediately","Immediate ice application for 24 hours","Start anticoagulation","Surgical revision"],"ans":1,"expl":"For an infiltration, treatment is immediate ice application for 24 hours, then warm compresses and possible rest. Ice limits swelling; warm compresses promote resolution later.","obj":3},
  {"topic":"Hemodialysis","q":"Which access complication is more associated with fistulas, high-flow access, and increased preload, presenting with tachycardia, tachypnea, and pulmonary changes?","opts":["Steal syndrome","High output cardiac failure","Pseudoaneurysm","Central venous stenosis"],"ans":1,"expl":"High output cardiac failure is more associated with fistulas with high flow and increased preload. It presents with tachycardia, increased pulse pressure, tachypnea, SOB, and pulmonary changes, and is aggravated by preexisting anemia or CVD. Intervention includes surgical reduction/banding and cardiac pharmacology.","obj":3},
  {"topic":"Hemodialysis","q":"The preferred initial needle gauge for AV fistula cannulation, according to the module, is:","opts":["17G back-eye","15G","19G front","21G"],"ans":0,"expl":"Initial AVF cannulation uses a 17G back-eye needle, selected based on visualizing and feeling. Fistulas are cannulated with a tourniquet for every fistula; grafts use a 45-degree angle.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD3C};
