// BATCH 11: NEW questions from ANNA Module 3 Part 2 (Hemodialysis complications).
// Verified against module text. obj: 3=phys/tech (complications/interventions), 6=infection.
const NEW_QUESTIONS_MOD3D = [
  {"topic":"Hemodialysis","q":"Which is the most common acute complication of hemodialysis, presenting early with warmth, dizziness, and pallor, and late with nausea, diaphoresis, and tachycardia?","opts":["Intradialytic hypertension","Hypotension","Muscle cramps","Disequilibrium syndrome"],"ans":1,"expl":"Hypotension is a common HD complication. Early signs: feeling warm, dizziness, weakness, pallor, visual disturbances. Late: N/V, diaphoresis, altered mental status, increased HR, SOB, cramping. Advanced: seizures, angina, arrythmia, loss of consciousness.","obj":3},
  {"topic":"Hemodialysis","q":"Which is an appropriate intervention for intradialytic hypotension?","opts":["Increase the ultrafiltration rate","Reduce the ultrafiltration rate, reposition the patient, give oral fluids or normal saline, and supplemental O2","Increase dialysate temperature","Discontinue all antihypertensives permanently"],"ans":1,"expl":"For HD hypotension, treatment includes reducing the UFR, repositioning, oral fluid replacement, O2, NS replacement, and osmotic agents. Prevention includes reassessment, monitoring trends, med timing, and midodrine use.","obj":3},
  {"topic":"Hemodialysis","q":"The nurse recognizes which of the following as a treatment-related cause of intradialytic hypotension?","opts":["Carnitine deficiency","Increased body temperature or acetate dialysate","Posture changes","Sepsis"],"ans":1,"expl":"Treatment-related causes of HD hypotension include increased body temperature, acetate dialysate, and treatment emergencies. Carnitine deficiency, posture changes, sepsis, and medications are patient-related causes.","obj":3},
  {"topic":"Hemodialysis","q":"A patient develops sudden, painful muscle cramps localized to the extremities during hemodialysis. Which is a recognized cause or management strategy?","opts":["Rapid ultrafiltration and hypoosmolality; manage by reducing UFR and pre-stretching exercises","High dialysate sodium and warm dialysate","Overhydration","Increased blood flow rate"],"ans":0,"expl":"Muscle cramps are caused by rapid UF, hypotension, hypoosmolality, electrolyte disturbances, or vitamin C/carnitine deficiency. Management includes reducing UFR, pre-stretching exercises, dialysate temperature adjustment, Hct-based BVM, and gabapentin.","obj":3},
  {"topic":"Hemodialysis","q":"A patient dialyzing for severe uremia develops blurred vision, hypertension, restlessness, and a severe headache, consistent with dialysis disequilibrium syndrome (DDS). What is the primary cause?","opts":["Hypersensitivity to the dialyzer membrane","Rapid lowering of blood urea creating an osmotic gradient that pulls water into the brain faster than urea can be removed","High dialysate calcium","Volume overload"],"ans":1,"expl":"DDS occurs when urea is removed from the blood faster than from the brain, creating an osmotic gradient that pulls water into the brain. It is more common in severe uremia and risk factors include children and those with head injury/stroke/acidosis.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a risk factor for dialysis disequilibrium syndrome?","opts":["A well-nourished, chronically dialyzed patient","Children or patients with a history of head injury, stroke, subdural hematoma, or severe acidosis","Diabetes with good control","Low parathyroid hormone"],"ans":1,"expl":"Risk factors for DDS include children and those with a history of head injury, stroke, subdural hematoma, or severe acidosis. It is more common in severe uremia.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a management strategy for dialysis disequilibrium syndrome?","opts":["Speed up the dialysis and increase BFR","Reduce blood flow rate/dialysate flow rate and ultrafiltration rate, use osmotic agents, and discontinue treatment if severe","Increase dialysate temperature","Administer prophylactic muscle relaxants"],"ans":1,"expl":"DDS management is prevention, symptom treatment, and reducing BFR/dialysate flow rate and UFR, using osmotic agents, and discontinuing treatment if severe or progressive.","obj":3},
  {"topic":"Hemodialysis","q":"Which best distinguishes a Type A from a Type B allergic reaction to the dialyzer?","opts":["Type A occurs within 30 minutes and is usually IgE-mediated and more serious; Type B occurs later and is complement-mediated","Type A always causes cardiac arrest; Type B only causes cramps","Type A is complement-mediated; Type B is IgE-mediated","They are identical"],"ans":0,"expl":"Type A dialyzer reaction occurs within 30 minutes, usually IgE-mediated and more serious (warmth, chills, pruritus, urticaria, SOB, hypotension, cardiac arrest). Type B occurs later, is complement-mediated, with N/V, back pain, and chest pain.","obj":3},
  {"topic":"Hemodialysis","q":"A dialysis patient develops fever, chills, and involuntary shaking with nausea. Which is a likely cause?","opts":["Access infection or pyrogenic reaction, or a dialysate temperature/body temperature mismatch","High blood pump speed","Dietary indiscretion","Stopping antihypertensives"],"ans":0,"expl":"Fever/chills in dialysis are caused by dialysis access infections, pyrogenic reactions, or a dialysate/body temperature mismatch. Management: assess source, trend VS, adjust dialysate temp, obtain blood cultures, and give antibiotics/antipyretics.","obj":6},
  {"topic":"Hemodialysis","q":"The nurse understands that catheters are associated with about how many times the risk of bacteremia compared to AV access?","opts":["2 times","Up to 10 times","50 times","No difference"],"ans":1,"expl":"CVCs are associated with up to 10 times the risk for bacteremia compared to AV access (fistula/graft). Prevention includes education, aseptic technique, antibiotic lock, and closed neutral-valve systems.","obj":6},
  {"topic":"Hemodialysis","q":"Which finding indicates central venous catheter dysfunction during hemodialysis?","opts":["Blood flow rate less than 300 mL/min or venous pressure greater than 200 mmHg","Blood flow rate above 400 mL/min","Arterial pressure less negative than -250 mmHg","A drop in serum sodium"],"ans":0,"expl":"Catheter malfunction is suggested by BFR <300 mL/min, a drop in clearance (URR <65%, Kt/V <1.2), venous pressure >200 mmHg, or arterial pressure more negative than -250 mmHg. Interventions include flushing, thrombolytics, and line reversal (temporary).","obj":3},
  {"topic":"Hemodialysis","q":"Which is a recognized intervention for a thrombosed/fibrin-sheathed central venous catheter?","opts":["Immediate removal and no further action","Flush the catheter, administer thrombolytics, line reversal (temporary fix), or catheter exchange","Increase the heparin dose in dialysate only","Surgical ligation"],"ans":1,"expl":"Catheter dysfunction from thrombosis/fibrin sheath is managed by flushing, thrombolytics, line reversal (temporary), and catheter exchange. Types of thrombus include fibrin sheath/tail, intraluminal, and mural thrombus.","obj":3},
  {"topic":"Hemodialysis","q":"Which is an early warning sign of intradialytic hypotension that the alert nurse identifies?","opts":["Sudden cardiac arrest","Feeling warm, dizziness, weakness, pallor, or visual disturbances","Severe muscle twitching","Pulmonary edema"],"ans":1,"expl":"Early signs of HD hypotension include feeling warm, dizziness, weakness, pallor, and visual disturbances. Recognizing these EARLY allows intervention before late (N/V, diaphoresis, altered MS, tachycardia) or advanced (seizures, arrhythmia) stages.","obj":3},
  {"topic":"Hemodialysis","q":"A dialysis patient develops itching that occurs ONLY during the treatment. What should the nurse consider first?","opts":["Uremic neuropathy alone","An allergic response/sensitivity to the dialyzer membrane","Liver disease","Hyperphosphatemia as an isolated cause"],"ans":1,"expl":"Itching during dialysis has many causes (hypercalcemia, hyperphosphatemia, inflammation, neuropathy, liver disease, uremia). However, itching during treatment ONLY suggests an allergic response/sensitivity to the dialyzer membrane.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a prevention priority for sudden cardiac death during hemodialysis?","opts":["Avoid high ultrafiltration rates, use blood volume monitoring, reassess target weight, and provide longer or more frequent HD sessions","Maximize the dialysate sodium","Discontinue all cardiac meds","Increase blood flow rate"],"ans":0,"expl":"Sudden cardiac death prevention centers on avoiding high UFR, using BVM, reassessing target weight, and providing more frequent/longer HD sessions or isothermic dialysate. Cardiac stunning, caused by prolonged transient myocardial ischemia, is managed by these preventive measures.","obj":3},
  {"topic":"Hemodialysis","q":"A patient on dialysis reports chest pain with cold, clammy skin and a feeling of impending doom. Which is an appropriate initial nursing management?","opts":["Increase the ultrafiltration rate","Report the chest pain, decrease UFR, reposition, give O2 and nitroglycerin, and initiate cardiac monitoring; discontinue treatment if severe","Give a fluid bolus of 1 liter","Discontinue all antihypertensives"],"ans":1,"expl":"For chest pain/angina: report, decrease UFR, reposition, O2, nitroglycerin, cardiac monitoring. If severe, discontinue treatment and initiate CPR. Causes include decreased O2, ischemia, anemia, hypotension, and rapid BFR increase.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD3D};
