// BATCH 16: NEW questions from ANNA Module 3 Part 2 (home HD, water disinfection).
// Verified against module text.
const NEW_QUESTIONS_MOD3E = [
  {"topic":"Hemodialysis","q":"Which statement about water treatment system disinfection is correct?","opts":["Chemical disinfection is done daily","Heat disinfection may be daily or weekly, chemical disinfection at least monthly, and culture/endotoxin testing taken BEFORE disinfection","Disinfection is optional on modern systems","Ozone can only be used for dialysate"],"ans":1,"expl":"Routine disinfection prevents bacterial growth. Heat disinfection may be daily or weekly; chemical disinfection at least monthly (ISO). Culture and endotoxin testing must be taken BEFORE disinfection, and documentation is required. Ozone can be used for water or bicarbonate systems.","obj":3},
  {"topic":"Hemodialysis","q":"Which best describes a 'conventional' home hemodialysis schedule?","opts":["Once weekly","Three times per week","Seven nights per week","Every day for 2 hours"],"ans":1,"expl":"Conventional HHD is 3X/week. HHD also includes every-other-day (avoiding a 2-day gap), more frequent (4-5X/week, shorter times, slower flow), and nocturnal (3-7X/week).","obj":3},
  {"topic":"Hemodialysis","q":"Nocturnal home hemodialysis is characterized by:","opts":["Short daytime runs of 2 hours","Longer nightly treatments (6-8 hours) with lower dialysate flow (100-200 mL/min) and lower blood flow (300-350 mL/min), requiring anticoagulation","Once weekly 4-hour sessions","High dialysate flow rates only"],"ans":1,"expl":"Nocturnal HHD uses longer nightly treatments of 6-8 hours, 3-7X/week, with lower dialysate flow (100-200 mL/min) and lower blood flow (300-350 mL/min), and requires anticoagulation.","obj":3},
  {"topic":"Hemodialysis","q":"In selecting a home hemodialysis candidate, the nurse should assess which of the following?","opts":["Only the patient's age","Motivation to learn and ability to provide safe/effective HHD, commitment to compliance, health/physical/mental status, vascular access, and availability of a care partner","Insurance status alone","Number of prior dialyses"],"ans":1,"expl":"HHD patient selection assesses motivation to learn, ability to provide safe/effective HHD, commitment to compliance, health status, physical/mental status, vascular access, home environment, and availability of a care partner. Contraindications include inability of patient/partner to perform and lack of appropriate space.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a listed home hemodialysis machine approved for use per the module?","opts":["Only Fresenius 2008K","NxStage System One with PureFlow SL, Fresenius 2008K@Home, Quanta SC+, and Tablo Hemodialysis System","Only NxStage","No machines are approved for home"],"ans":1,"expl":"Four machines are approved for HHD: NxStage System One with PureFlow SL, Fresenius 2008K@Home, Quanta SC+, and Tablo Hemodialysis System. Equipment requirements are the same as in-center HD.","obj":3},
  {"topic":"Hemodialysis","q":"A key reason to schedule home hemodialysis every other day (rather than a 2-day gap) is to:","opts":["Reduce cost","Avoid a 2-day intradialytic period","Reduce machine wear","Increase fluid intake"],"ans":1,"expl":"The 'every other day' HHD schedule is used to avoid a 2-day intradialytic (no-dialysis) period. More frequent scheduling (4-5X/week) also provides general shorter treatment times with slower flow rates.","obj":3},
  {"topic":"Hemodialysis","q":"Regarding dialysate delivery, the machine's proportioning unit mixes which components?","opts":["Only water and acid","Treated water, bicarbonate, and acid in chambers, continuously monitoring conductivity, temperature, pH, and flow","Only bicarbonate and water","Electrolytes and anticoagulant"],"ans":1,"expl":"The proportioning unit mixes treated water, bicarbonate, and acid in chambers. The machine continuously monitors conductivity, temperature, pH, flow rate, and presence of blood (post-dialyzer).","obj":3},
  {"topic":"Hemodialysis","q":"The module lists which as an important part of home HD patient training?","opts":["Vascular access management, infection control, anticoagulation/med administration, and emergency/complication management","Only machine operation","No training is required","Only documentation"],"ans":0,"expl":"HHD training covers infection control, vascular access management, vital signs, HD fundamentals (theory/equipment/procedures), the dialysis prescription, anticoagulation/med administration, complications/management, documentation, supply inventory, equipment maintenance, travel, and backup resources.","obj":3},
  {"topic":"Hemodialysis","q":"Water treatment system disinfection documentation and post-disinfection monitoring are important primarily because:","opts":["It reduces dialysis cost","It protects patient safety by confirming safe disinfection and preventing bacterial growth","It speeds up dialysis","It is not required"],"ans":1,"expl":"Monitoring levels during and post disinfection is critical for patient safety, and documentation is required. Routine disinfection prevents the growth of bacteria that could be delivered to patients.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a true statement about dialysate preparation for home hemodialysis?","opts":["Patients make their own water from tap","Dialysate preparation uses a water purification system and dialysate concentrate, with water testing/alarms, equipment installation, maintenance, and disinfection","No disinfection is needed at home","Only pre-mixed bags are used, never water purification"],"ans":1,"expl":"HHD dialysate preparation uses a water purification system/dialysate concentrate, with water testing/alarms, equipment installation, maintenance, and disinfection. Equipment requirements are the same as in-center HD.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD3E};
