// BATCH 8: NEW questions — Diabetes + CKD / DKD content (Module 8, applicable to RN-level CNN).
// Verified against module text. obj: 2=medications, 5=CKD complications, 1=pathology.
const NEW_QUESTIONS_MOD8B = [
  {"topic":"CKD Complications","q":"A type 2 diabetic with CKD has an eGFR of 35 ml/min/1.73m². According to KDIGO and FDA guidance, what is the status of metformin therapy?","opts":["Contraindicated and must be stopped","Dose should be reduced (not started new), and eGFR monitored; discontinue if eGFR falls below 30","Full dose is always safe","No monitoring of kidney function is needed"],"ans":1,"expl":"Metformin is contraindicated with eGFR <30 ml/min/1.73m². Starting it at eGFR 30-45 is not recommended. For those already on it, assess benefits/risks when eGFR <45 and discontinue if it falls <30. The 2022 KDIGO guideline allows use with eGFR ≥30.","obj":2},
  {"topic":"CKD Complications","q":"Which class of diabetes medication is thought to slow progression of DKD by decreasing fibrosis, inflammation, and hyperfiltration, and also reduces cardiovascular risk?","opts":["SGLT-2 inhibitors","Sulfonylureas","Thiazolidinediones","Insulin analogs"],"ans":0,"expl":"SGLT-2 inhibitors are thought to slow DKD progression by decreasing fibrotic changes, inflammation, and hyperfiltration, and reduce risk of atherosclerotic CVD and heart failure. Risks include genital/UTI infections, DKA, and possible lower-limb amputation.","obj":2},
  {"topic":"CKD Complications","q":"The 2022 KDIGO guideline recommends treating type 2 diabetic CKD patients with an SGLT-2 inhibitor at what eGFR threshold?","opts":["eGFR ≥ 45 ml/min/1.73m²","eGFR ≥ 20 ml/min/1.73m²","eGFR ≥ 60 ml/min/1.73m²","eGFR ≥ 90 ml/min/1.73m²"],"ans":1,"expl":"KDIGO 2022 recommends SGLT-2 inhibitor treatment when eGFR ≥20 ml/min/1.73m². An initial reduction in eGFR may occur that should reverse, and use may be reasonable to continue even below 20.","obj":2},
  {"topic":"CKD Complications","q":"Which side effects should the nurse teach a patient starting an SGLT-2 inhibitor to watch for?","opts":["Dry mouth and constipation","Genital yeast infections, urinary tract infections, and diabetic ketoacidosis","Hair loss and liver toxicity","Bradycardia and hypotension"],"ans":1,"expl":"SGLT-2 inhibitor risks include genital yeast infections, urinary tract infections, and diabetic ketoacidosis. Expected effects include weight loss, volume contraction, and BP reduction. One study noted concern for lower-limb amputation.","obj":2},
  {"topic":"Kidney Disease","q":"A patient is found to have diabetic kidney disease. The nurse expects that the classic biopsy finding in DKD is which of the following?","opts":["IgA deposits in the mesangium","Kimmelstiel-Wilson nodules and glomerular basement membrane thickening","Crescent formation in Bowman's space","Minimal change disease on electron microscopy"],"ans":1,"expl":"Classic DKD biopsy findings include glomerulosclerosis, mesangial expansion (diffuse or nodular — Kimmelstiel-Wilson nodules), glomerular basement membrane thickening, and absence of GBM deposits. There is no pathology difference between DKD from type 1 vs type 2.","obj":1},
  {"topic":"Kidney Disease","q":"Which statement is correct regarding diabetic retinopathy and diabetic kidney disease?","opts":["Retinopathy is rare in DKD","Over 95% of patients with DKD from type 1 DM have concurrent retinopathy","Retinopathy only develops after kidney transplant","Retinopathy indicates the renal disease is not diabetic"],"ans":1,"expl":"In type 1 DM DKD, over 95% of patients have concurrent retinopathy (estimated >95%); in type 2 DM, up to 60% will have retinopathy. Retinopathy supports, rather than excludes, a diabetic cause of kidney disease.","obj":1},
  {"topic":"CKD Complications","q":"When titrating RAASi (ACEi/ARB) therapy in a CKD patient, the nurse understands the dose may be increased if:","opts":["Serum potassium is elevated","Serum potassium is normal with a serum creatinine increase of less than 30%","Creatinine rises by more than 50%","The patient develops hyperkalemia"],"ans":1,"expl":"If serum potassium remains within normal limits with a concurrent increase in serum creatinine <30%, the ACEi/ARB dose may be increased to the maximally tolerated dose. A rise in creatinine ≥30% or hyperkalemia warrants caution.","obj":2},
  {"topic":"Kidney Disease","q":"Which is the leading concern when combining a mineralocorticoid receptor antagonist (e.g., spironolactone) with an ACEi or ARB in CKD?","opts":["Hypokalemia","Hyperkalemia and decreased eGFR","Hypotension only","Metabolic alkalosis"],"ans":1,"expl":"Adding a mineralocorticoid receptor antagonist (spironolactone, finerenone) to an ACEi/ARB carries a concurrent risk for hyperkalemia, and these agents can cause a decrease in eGFR. Monitor potassium and kidney function.","obj":2},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD8B};
