// PILOT: NEW questions generated from ANNA Module 3 (Hemodialysis) curriculum.
// Original application-based questions, grounded in the module content.
// Format matches content.js: {topic, q, opts[4], ans(index), expl, obj}
// obj = NNCC objective number (1-7). Hemodialysis content typically maps to obj 2 (KRT principles) or 3.
// REVIEW by Oliver before merging into content.js
const NEW_QUESTIONS_MOD3 = [
  {"topic":"Hemodialysis","q":"A patient undergoing hemodialysis develops acute hemolysis. Which water contaminant should the nurse suspect as the cause?","opts":["Aluminum","Chloramines and copper","Fluoride","Sulfate"],"ans":1,"expl":"Hemolysis during HD points to chloramines, copper, or nitrate contamination of the water/dialysate. Aluminum causes anemia, bone disease, and encephalopathy, not acute hemolysis.","obj":2},
  {"topic":"Hemodialysis","q":"Why is municipal (tap) drinking water NOT safe as a direct source for hemodialysis treatment?","opts":["It has too low a sodium concentration","It contains additives and contaminants that are toxic to HD patients due to high exposure across the membrane","It is hypotonic and causes fluid overload","It lacks bicarbonate for buffer"],"ans":1,"expl":"HD patients are exposed to ~360 L of water per week directly across a semipermeable membrane, versus ~14 L/wk for an average person. Additives and contaminants that are safe to drink become toxic at dialysis doses of exposure.","obj":2},
  {"topic":"Hemodialysis","q":"Which maximum allowable level for dialysis water would be MOST concerning if it rose above the standard for aluminum?","opts":["0.01 mg/L","0.1 mg/L","2.0 mg/L","70 mg/L"],"ans":0,"expl":"The maximum allowable aluminum for dialysis water is 0.01 mg/L. Concentrations above ~0.06 mg/L are associated with toxicity, causing anemia and bone disease.","obj":2},
  {"topic":"Hemodialysis","q":"A hemodialysis patient develops progressive neuro-deterioration (encephalopathy). Which dialysate water contaminant is the most likely cause?","opts":["Chloramines","Copper","Aluminum","Nitrate"],"ans":2,"expl":"Aluminum is associated with neuro-deterioration/encephalopathy and bone disease. Aluminum toxicity can also cause a microcytic anemia unresponsive to EPO and osteomalacia.","obj":2},
  {"topic":"Hemodialysis","q":"The nephrology nurse understands that which contaminant-related patient problem is best correlated with hypertension in the dialysis patient?","opts":["Chloramines causing anemia","Excess calcium or sodium in dialysate","Aluminum causing bone disease","Endotoxin contamination"],"ans":1,"expl":"Hypertension during dialysis can be caused by excess calcium or sodium in the dialysate. Anemia, bone disease, and encephalopathy map to aluminum/chloramines; hypotension maps to bacteria, endotoxin, or nitrates.","obj":2},
  {"topic":"Hemodialysis","q":"Which component of the water treatment system protects the reverse osmosis (RO) membrane from scaling by exchanging sodium for calcium and magnesium?","opts":["Sediment filter","Water softener (brine tank)","Deionizer (DI) tanks","Ultraviolet (UV) light"],"ans":1,"expl":"The water softener exchanges sodium for calcium and magnesium to protect the RO membrane from scaling. The RO system does the primary purification; DI tanks and UV are downstream purification steps.","obj":2},
  {"topic":"Hemodialysis","q":"Per AAMI/ISO standards, what is the acceptable maximum total viable bacteria count (TVC) for dialysis WATER?","opts":["<10 CFU/ml","<100 CFU/ml","<200 CFU/ml","<500 CFU/ml"],"ans":1,"expl":"Per ISO 23500-5, dialysis water must have total viable bacteria <100 CFU/ml (action level 50 CFU/ml). Dialysate allows <100 CFU/ml too in modern standards, but 'drinking water' may allow up to 500; never the case for dialysis.","obj":2},
  {"topic":"Hemodialysis","q":"The nurse recognizes that a dialysis water system is composed of purification AND distribution components. Which pair correctly lists one of each?","opts":["Reverse osmosis (RO) and storage tank","Distribution pump and deionizer","Ultraviolet light and sediment filter","Booster pump and brine tank"],"ans":0,"expl":"Purification components are the RO system, deionization (DI), UV light, and submicron/ultrafilter. Distribution components are the distribution pump, storage tank(s), and distribution loop. RO is purification; storage tank is distribution.","obj":2},
  {"topic":"Hemodialysis","q":"A patient reports nausea and vomiting during dialysis. Which water/dialysate contaminant is a possible cause?","opts":["Aluminum","Fluoride","Chloramine (low level)","Bacteria, endotoxin, or copper, or low pH, or magnesium, or nitrate, or sulfate, or zinc"],"ans":3,"expl":"Nausea/vomiting is associated with bacteria, calcium, copper, endotoxin, low pH, magnesium, nitrates, sulfates, and zinc. Aluminum is linked to anemia, bone disease, and encephalopathy rather than GI upset.","obj":2},
  {"topic":"Hemodialysis","q":"Which regulatory body's ESRD regulations direct dialysis facilities to follow AAMI recommendations?","opts":["EPA","Centers for Medicare & Medicaid Services (CMS)","FDA","ANNA"],"ans":1,"expl":"CMS's ESRD regulations (updated 2008) direct outpatient dialysis facilities to follow AAMI recommendations for water/dialysate quality. AAMI sets device/safety standards; ISO is international; EPA sets municipal drinking-water limits.","obj":2},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD3};
