// BATCH 17: NEW questions from ANNA Module 3 Part 1 (water/dialysate treatment, QAPI).
// Verified against module text.
const NEW_QUESTIONS_MOD3F = [
  {"topic":"Hemodialysis","q":"Which post-water-treatment component destroys microorganisms and may be used after deionization (DI) or in bicarbonate distribution systems?","opts":["Endotoxin retentive filter","Ultraviolet (UV) irradiation","Deionization tank","Carbon tanks"],"ans":1,"expl":"Ultraviolet irradiation destroys microorganisms, is used post-DI, and may be used in bicarbonate distribution systems, though it may increase endotoxin levels.","obj":3},
  {"topic":"Hemodialysis","q":"Endotoxin retentive filters are needed for ultrapure water and serve to:","opts":["Remove organic chemicals only","Remove endotoxin; they follow DI tanks and may be after the RO or in the dialysate line for each machine","Add minerals to the water","Warm the dialysate"],"ans":1,"expl":"Endotoxin retentive (ultrafine) filters remove endotoxin and are needed for ultrapure water. They must follow DI tanks and may be placed after the RO or in the dialysate line for each machine.","obj":3},
  {"topic":"Hemodialysis","q":"Regarding distribution piping for product water after the reverse osmosis (RO) unit, the module states:","opts":["Brass and copper are preferred","No brass, lead, or copper post-RO, and no dead legs; a return loop keeps water moving","Lead is required for strength","Dead legs are acceptable if short"],"ans":1,"expl":"Distribution piping post-RO should have no brass, lead, or copper, and no dead legs. A return loop keeps water moving. The water storage tank should fill from the top, empty from the lowest point (conical), and be tightly sealed.","obj":3},
  {"topic":"Hemodialysis","q":"Where should water samples for culture and endotoxin be collected?","opts":["Only at the RO","At the beginning and end of the water system, water storage tank, water source for mixing bicarbonate, and reuse equipment","Only from the dialysis machine","Only from the faucet"],"ans":1,"expl":"Collect water samples at the beginning and end of the water system, the water storage tank, the water source for mixing bicarbonate, and reuse equipment. Samples are done monthly before disinfection of the system.","obj":3},
  {"topic":"Hemodialysis","q":"The module emphasizes that dialysate should be treated as a medication, remembering the five rights. It further states:","opts":["Anyone can spike the dialysate","All concentrates in a facility must be of the same mixing ratio to prevent harm, and dialysate samples for culture/endotoxin are drawn on a proportion of machines monthly","Mixing ratios do not matter","Bicarbonate mixed by staff needs no pH or conductivity check"],"ans":1,"expl":"Dialysate is a medication (five rights). All concentrates in a facility must be of the same mixing ratio to prevent harm. Bicarbonate mixed by staff needs proper pH, conductivity, and specific gravity. Dialysate culture/endotoxin samples are drawn on a proportion of machines monthly; spiking should only be done by trained professionals.","obj":3},
  {"topic":"Hemodialysis","q":"Who is ultimately responsible for patient safety regarding water and dialysate, as reported in QAPI?","opts":["The nephrology nurse","The Medical Director (MD)","The dialysis technician","The facility administrator"],"ans":1,"expl":"The Medical Director is responsible for patient safety. The MD should review in QAPI: water treatment logs, culture/endotoxin results, dialysate and acid mixing logs, machine maintenance records, and any errors or interruptions in water supply.","obj":3},
  {"topic":"Hemodialysis","q":"Which of the following should be avoided in the design of a water storage tank to reduce the risk of bacterial growth?","opts":["Conical shape that empties from the lowest point","Filling from the top","Tightly sealing","A flat-bottomed tank that holds standing water"],"ans":3,"expl":"To reduce bacterial growth, the water storage tank should have a conical shape that empties from the lowest point, fill from the top, and be tightly sealed. A flat-bottomed tank that holds standing water increases the risk.","obj":3},
  {"topic":"Hemodialysis","q":"Per the module, culture and endotoxin testing of the water treatment system should be taken:","opts":["After disinfection only","Before disinfection","Only when contamination is suspected","Anytime without documentation"],"ans":1,"expl":"Culture and endotoxin testing must be taken BEFORE disinfection, and documentation of disinfection is required. Monitoring during and post disinfection is critical for patient safety.","obj":3},
  {"topic":"Hemodialysis","q":"Which is a common source of microbiological contamination in dialysis product water?","opts":["Only the city water supply","City water, pre-treatment components, deionization, the distribution system, or an inadequate disinfection cycle","Only the RO membrane","Only the dialyzer"],"ans":1,"expl":"Microbiological contaminants in product water can originate from city water, pre-treatment components, DI, the distribution system, or an inadequate disinfection cycle.","obj":3},
  {"topic":"Hemodialysis","q":"A dialysis facility uses several different concentrate mixing ratios (e.g., 35X square vs 45X triangle). Why is this a concern?","opts":["It affects dialysate temperature only","All concentrates in a facility must be of the same mixing ratio to prevent potential harm to patients","It increases dialysis efficiency","It is not a concern"],"ans":1,"expl":"All concentrates used in a facility must be of the same mixing ratio (e.g., 35X, 36.83X, 45X) to prevent potential harm to patients. The machine manufacturer's manual specifies the required concentrate type.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD3F};
