// BATCH 18: NEW questions from ANNA Module 8 Part 2 (electrolyte control in HD).
// Verified against module text. obj: 3=phys/tech, 5=CKD complications, 2=interventions.
const NEW_QUESTIONS_MOD8C = [
  {"topic":"CKD Complications","q":"A dialysis patient develops hyperkalemia. Which potassium-lowering strategy does the module advise AVOIDING because of the risk of colonic necrosis?","opts":["Patiromer","Sodium-zirconium cyclosilicate","Polystyrene sulfonate (Kayexalate)","Insulin with glucose"],"ans":2,"expl":"The module advises considering K-exchange ions (patiromer or sodium-zirconium cyclosilicate) and AVOIDING polystyrene sulfonate because of the risk for colonic necrosis. Also allow time on HD for intravascular potassium to be replaced from intracellular stores and assess for EKG changes.","obj":5},
  {"topic":"CKD Complications","q":"Rapid correction of hyperkalemia can cause which serious complication?","opts":["Hypernatremia","Arrhythmias and sudden cardiac death, more common in patients on digoxin or those prone to arrhythmia","Hypoglycemia","Metabolic alkalosis"],"ans":1,"expl":"Rapid correction of hyperkalemia can cause harm: arrhythmias and sudden cardiac death, more common in patients on digoxin and/or those prone to arrhythmia. Consider inpatient care/monitoring and assess for EKG changes.","obj":5},
  {"topic":"CKD Complications","q":"Which best describes the potassium 'rebound' after hemodialysis?","opts":["Potassium stays low for days","Potassium levels rebound as potassium shifts out of the cells up to about 6 hours after dialysis","Potassium never changes after HD","Rebound only occurs in the first 10 minutes"],"ans":1,"expl":"Up to 6 hours after dialysis, potassium levels rebound as potassium shifts out of the cells. Hence allow time on HD for intravascular potassium to be replaced from intracellular stores rather than overcorrecting.","obj":5},
  {"topic":"CKD Complications","q":"When managing hypokalemia in a dialysis patient, the nurse should consider which contributing factor or approach?","opts":["GI losses and rapid/overcorrection of prior hyperkalemia","Increase potassium in the dialysate with each treatment","Use polystyrene sulfonate","Withhold all potassium-rich foods"],"ans":0,"expl":"For hypokalemia, consider GI losses and recent rapid/overcorrection of hyperkalemia. Consider inpatient monitoring and assess for EKG changes. If chronic, use mineralocorticoid antagonists, potassium supplements, and diet adjustment.","obj":5},
  {"topic":"Hemodialysis","q":"The goal pre-hemodialysis serum calcium is approximately:","opts":["8.5-10.1 mg/dL","12-14 mg/dL","7-8 mg/dL","5-6 mg/dL"],"ans":0,"expl":"The goal pre-HD serum calcium is 8.5-10.1 mg/dL. Most dialysate calcium concentrations are 2-3.5 mEq/L and will almost always deliver calcium to patients. Higher calcium dialysate increases calcification risk; lower calcium increases hypotension risk.","obj":5},
  {"topic":"Hemodialysis","q":"The goal mid-week pre-hemodialysis serum bicarbonate (total buffer) level is:","opts":["10-15 mEq/L","18-23 mEq/L","27-33 mEq/L","35-40 mEq/L"],"ans":1,"expl":"The goal mid-week pre-HD serum bicarbonate is 18-23 mEq/L. Both chronic acidosis (<18) and alkalosis (>27) in HD patients are associated with higher mortality. Adjust the HD prescription to 30-40 mEq/L total buffer.","obj":5},
  {"topic":"Hemodialysis","q":"In hemodialysis, dialysates are buffered by bicarbonate or its precursors. Which of the following is a bicarbonate precursor converted in the body?","opts":["Sodium chloride","Citrate, acetate, or lactate","Glucose","Urea"],"ans":1,"expl":"Dialysates are buffered by bicarbonate or its precursors — citrate, acetate, and lactate — which are converted in the body to bicarbonate. Prescribe based on total buffering capability and read the labels.","obj":3},
  {"topic":"Hemodialysis","q":"Which statement about sodium control in hemodialysis is correct per the module?","opts":["Dialysate sodium should always be lower than plasma to pull sodium out","Dialysate sodium should always be higher than plasma, but avoid acute sodium changes, aiming for isotonic hemodialysis without depleting or loading sodium","Sodium is never affected by dialysis","Dialysate sodium should equal zero"],"ans":1,"expl":"Aim for isotonic hemodialysis — do not deplete or load dialysis patients with sodium. Dialysate sodium should always be higher than plasma (due to removal of osmolytes like urea and sodium), while avoiding acute sodium changes. Goal pre-HD sodium is 135-145 mmol/L.","obj":3},
  {"topic":"Hemodialysis","q":"Higher calcium dialysate in hemodialysis increases the risk of:","opts":["Hypotension","Calcification","Hypernatremia","Hyperkalemia"],"ans":1,"expl":"Higher calcium dialysate increases the risk for calcification. Lower calcium dialysate increases the risk for hypotension. Adjust dialysate calcium to target pre-dialysis calcium and blood pressure goals.","obj":3},
  {"topic":"Hemodialysis","q":"Which has a strong impact on acid-base status for an ESKD patient?","opts":["The amount of dialysis machine tubing","Diet — protein produces acids, since ESKD kidneys are not making bicarbonate to buffer","The dialyzer pore size","Blood pump speed"],"ans":1,"expl":"Diet strongly impacts acid-base status in ESKD, because protein produces acids and the failed kidneys are not making bicarbonate to buffer. Dialysis makes a small impact on overall acid-load removal, so diet is a major factor.","obj":5},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD8C};
