// BATCH 12: NEW questions from ANNA Module 2 (CKD staging, eGFR, albuminuria, mineral-bone).
// Verified against module text.
const NEW_QUESTIONS_MOD2B = [
  {"topic":"Kidney Disease","q":"Per the KDIGO 2013 definition, chronic kidney disease (CKD) requires abnormalities of kidney structure or function present for how long?","opts":["7 days","3 months","6 months","1 year"],"ans":1,"expl":"CKD is defined by abnormalities of kidney structure or function present for 3 or more months, with implications for health. It is classified by cause, eGFR category, and albuminuria category.","obj":1},
  {"topic":"Kidney Disease","q":"A patient has an eGFR of 25 mL/min/1.73m². This corresponds to which KDIGO GFR category?","opts":["G3a (45-59)","G3b (30-44)","G4 (15-29), severely decreased","G5 (<15)"],"ans":2,"expl":"Per KDIGO: G1 ≥90, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29 (severely decreased), G5 <15 (kidney failure). An eGFR of 25 is G4.","obj":1},
  {"topic":"Kidney Disease","q":"Which is the BEST overall index of kidney function and the ability of the kidneys to filter blood?","opts":["Serum creatinine alone","Estimated glomerular filtration rate (eGFR)","Urine output","Blood urea nitrogen"],"ans":1,"expl":"eGFR is considered the best overall index of kidney function and the kidneys' ability to filter blood. Normal GFR varies by age, gender, and body size, and GFR normally declines with age.","obj":1},
  {"topic":"Kidney Disease","q":"The recommended eGFR formula for adults per the module is:","opts":["Cockcroft-Gault","CKD-EPI Creatinine (2021)","MDRD","Bedside Schwartz (2009)"],"ans":1,"expl":"The recommended formula for adults is CKD-EPI Creatinine (2021), taking into account age (18+), gender, and serum creatinine. The Bedside Schwartz formula (2009) is for pediatric patients ages 1-17.","obj":1},
  {"topic":"Kidney Disease","q":"Which eGFR formula is used for pediatric patients age 1-17 years?","opts":["CKD-EPI Creatinine (2021)","MDRD","Bedside Schwartz formula (2009)","CKD-EPI Cystatin C (2012)"],"ans":2,"expl":"The Bedside Schwartz formula (2009) is recommended for ages 1-17, utilizing serum creatinine and height. Formulas using cystatin-C (2012) are also available.","obj":1},
  {"topic":"Kidney Disease","q":"Serum Cystatin C may be a more accurate measure of kidney function than creatinine because it is:","opts":["More influenced by muscle mass","Less influenced by gender, age, and muscle mass","Cheaper and widely available","Unaffected by glucocorticoids"],"ans":1,"expl":"Cystatin C is considered more accurate as it is less influenced by gender, age, and muscle mass than creatinine. However, it is more expensive, may not be readily available, and glucocorticoids may increase its levels.","obj":1},
  {"topic":"Kidney Disease","q":"In which situation may Cystatin C-based eGFR be especially helpful?","opts":["An otherwise healthy middle-aged adult","When creatinine-only eGFR formulas may be inaccurate, such as the elderly, obesity, increased musculature, or extreme diets","A patient in renal failure on dialysis","A young athlete with normal labs"],"ans":1,"expl":"Cystatin C blood testing is helpful when kidney function evaluation is inconclusive, or when creatinine-only formulas are inaccurate — e.g., the elderly, increased musculature, obesity, or extreme diets.","obj":1},
  {"topic":"Kidney Disease","q":"What is considered a rapid progression of CKD in terms of GFR decline?","opts":["A decline from baseline eGFR by 25%","A persistent decrease in GFR of greater than 5 mL/min/1.73m²/year","Any single dip in eGFR","A GFR drop to below 15"],"ans":1,"expl":"Rapid progression of CKD shows a persistent decrease in GFR greater than 5 mL/min/1.73m²/year. A 25% decline from baseline eGFR is a cause for concern, and slight fluctuations are common.","obj":1},
  {"topic":"Kidney Disease","q":"What is the earliest indicator of glomerular disease that can present before a decrease in GFR or elevated creatinine?","opts":["Hyperkalemia","Albuminuria","Anemia","Edema"],"ans":1,"expl":"Albuminuria is the earliest indicator of glomerular diseases and can be present before a decrease in GFR or an elevated creatinine. It is a common finding and an established marker for CKD.","obj":1},
  {"topic":"Kidney Disease","q":"Which is TRUE regarding urine albumin-to-creatinine ratio (ACR) categories?","opts":["A1 is severely increased (>300 mg/g)","A2 (moderately increased) is an albumin-to-creatinine ratio of 30-300 mg/g","A3 is 'normal to mildly increased'","ACR category is irrelevant to prognosis"],"ans":1,"expl":"KDIGO albuminuria categories: A1 <30 mg/g (normal/mildly increased), A2 30-300 mg/g (moderately increased), A3 >300 mg/g (severely increased). A UACR ≥30 mg/g correlates with a urine albumin excretion rate ≥30 mg/24h.","obj":1},
  {"topic":"Kidney Disease","q":"A patient's spot urine ACR is 45 mg/g. This represents which albuminuria category?","opts":["A1 - normal to mildly increased","A2 - moderately increased","A3 - severely increased","Not classified"],"ans":1,"expl":"An ACR of 45 mg/g falls in the A2 (moderately increased) category, which is 30-300 mg/g. A1 is <30, A3 is >300.","obj":1},
  {"topic":"Kidney Disease","q":"When should a urine albumin-to-creatinine (ACR) spot test be AVOIDED?","opts":["First morning void","After strenuous exercise within the past 24 hours, during a UTI/fever, or while menstruating","After fasting","Midday collection"],"ans":1,"expl":"ACR testing should be avoided when the patient has strenuously exercised within 24 hours, has a urinary tract infection and/or fever, or is menstruating, as these can alter results.","obj":1},
  {"topic":"Kidney Disease","q":"Which class of phosphate binder is linked to aluminum accumulation causing anemia, bone disease, and encephalopathy?","opts":["Calcium-based binders","Aluminum-based binders","Sevelamer","Ferric citrate"],"ans":1,"expl":"Aluminum-based binders carry concern for anemia, bone disease, and encephalopathy due to systemic accumulation of aluminum. Calcium-based binders can contribute to hypercalcemia. Others (sevelamer, ferric citrate, lanthanum, sucroferric) are non-calcium/non-aluminum.","obj":2},
  {"topic":"Kidney Disease","q":"Which drug is a new phosphate absorption inhibitor FDA-approved in October 2023, blocking NHE3 in the GI tract?","opts":["Cinacalcet","Tenapanor (Xphozah)","Sevelamer","Calcitriol"],"ans":1,"expl":"Tenapanor (Xphozah) is a phosphate absorption inhibitor that blocks local inhibition of NHE3 in the GI tract, reducing paracellular phosphate absorption. It is add-on or monotherapy for phosphorus lowering in CKD on dialysis.","obj":2},
  {"topic":"Kidney Disease","q":"Before initiating therapy with vitamin D analogs for CKD-MBD, which value should be near normal?","opts":["Serum phosphorus","Serum sodium","Hemoglobin","Albumin"],"ans":0,"expl":"Before initiating vitamin D analog therapy, phosphorus levels should be near normal. Monitor calcium and phosphorus before and during treatment. Do not use in hypercalcemia; do not use if PTH is below 100-150 (risk of adynamic bone disease).","obj":2},
  {"topic":"Kidney Disease","q":"Which agent decreases intact PTH secretion by increasing parathyroid gland sensitivity to extracellular calcium, and is available orally in 30, 60, and 90 mg doses?","opts":["Etelcalcetide","Cinacalcet","Calcitriol","Paricalcitol"],"ans":1,"expl":"Cinacalcet (a calcimimetic) decreases intact PTH secretion by increasing parathyroid gland sensitivity to calcium. It is oral (30/60/90 mg), for secondary or primary hyperparathyroidism. Etelcalcetide is IV, given 3x/week.","obj":2},
  {"topic":"Kidney Disease","q":"Active vitamin D analogs such as calcitriol should be used with caution because they can increase:","opts":["Serum sodium","Both serum calcium and phosphate (more common with calcitriol)","Hemoglobin","Serum potassium"],"ans":1,"expl":"Active vitamin D can increase both serum calcium and phosphate, more commonly with calcitriol. Hence the need to monitor calcium and phosphorus and avoid use in hypercalcemia.","obj":2},
  {"topic":"Kidney Disease","q":"Which is a consideration in using ACE inhibitor/ARB therapy in a CKD patient with anemia of renal disease?","opts":["They worsen anemia significantly","Important to monitor renal function and serum potassium, and they may cause a moderate rise in creatinine that typically improves","They are contraindicated in all CKD","They cause hypokalemia"],"ans":1,"expl":"ACEi/ARBs require monitoring of renal function and serum potassium. Serum creatinine can increase with initiation/dose increase and typically improves; generally not discontinued for <30% creatinine rise in the absence of volume depletion/hypotension. They carry a hyperkalemia risk.","obj":2},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD2B};
