// BATCH 2: NEW questions from ANNA Module 2 (Concepts of Renal Disease).
// Original application-based questions, verified against module text.
// obj convention: Kidney Disease pathophysiology=1, medications/KRT=2, CKD complications=5.
const NEW_QUESTIONS_MOD2 = [
  {"topic":"Kidney Disease","q":"The nephrology nurse recalls that the juxtaglomerular apparatus is a communication between which structures?","opts":["Macula densa cells and afferent arteriole cells","Glomerular capillary and Bowman's capsule","Loop of Henle and vasa recta","Distal tubule and collecting duct"],"ans":0,"expl":"The juxtaglomerular apparatus is the communication between macula densa cells (in the initial distal tubule) and afferent arteriole cells. It maintains systemic blood pressure and glomerular (intraglomerular) filtration pressure.","obj":1},
  {"topic":"Kidney Disease","q":"Which portion of the kidney receives approximately 90% of renal blood flow and houses the glomeruli?","opts":["Medulla","Cortex","Calyx","Pyramid"],"ans":1,"expl":"The cortex is the outer portion of the kidney, receives ~90% of renal blood flow, and contains the glomeruli, proximal/distal tubules, cortical collecting tubules, and peritubular capillaries. The medulla contains the loops of Henle and collecting tubules.","obj":1},
  {"topic":"Kidney Disease","q":"In the absence of antidiuretic hormone (ADH), the nurse would expect what change in the collecting tubule?","opts":["Increased water reabsorption","Minimal water absorption with dilute urine","Concentrated urine output","Sodium retention"],"ans":1,"expl":"Water permeability of the collecting tubule is ADH-dependent. Without ADH, minimal water is absorbed and dilute urine is produced; with ADH, water is absorbed and urine becomes concentrated.","obj":1},
  {"topic":"Kidney Disease","q":"A patient's urine composition is considered fixed and unchanged once it passes through which structure?","opts":["Proximal tubule","Loop of Henle","Papilla","Cortex"],"ans":2,"expl":"Urine composition is unchanged once it passes through the papilla (the tapered end of the pyramid where urine enters the minor and major calyces).","obj":1},
  {"topic":"Kidney Disease","q":"How much of the cardiac output do the kidneys normally receive?","opts":["5%-10%","20%-25%","40%-50%","1%-3%"],"ans":1,"expl":"The kidneys receive 20%-25% of cardiac output, about 1200 mL/min renal blood flow, despite representing only about 0.5% of total body weight.","obj":1},
  {"topic":"Kidney Disease","q":"A patient with CKD is found to have erythropoietin deficiency causing anemia. The nurse understands the kidneys produce approximately what percentage of erythropoietin?","opts":["About 50%","About 70%","About 90%","About 100%"],"ans":2,"expl":"Erythropoietin deficiency is the primary cause of anemia in CKD — the kidneys produce about 90% of erythropoietin. Anemia is frequent in CKD stages 3-5.","obj":5},
  {"topic":"Kidney Disease","q":"When would the nurse expect a provider to initiate erythropoiesis-stimulating agent (ESA) therapy for a CKD patient's anemia, per the module guidance?","opts":["Hemoglobin ≤ 12 g/dL","Hemoglobin ≤ 10 g/dL","Hemoglobin ≤ 8 g/dL","Any hemoglobin with symptoms"],"ans":1,"expl":"ESA therapy is initiated when hemoglobin is ≤10 g/dL, with a target hemoglobin around 11 g/dL. There is an increased risk of cardiovascular events and CVA when hemoglobin is ≥11.0 g/dL.","obj":5},
  {"topic":"Kidney Disease","q":"A patient on an ESA develops a sudden rapid drop in hemoglobin of about 0.5-1 g/dL per week with a normal platelet and WBC count and a reticulocyte count below 10,000/µL. This presentation is most consistent with:","opts":["Iron deficiency anemia","Pure red cell aplasia","Acute blood loss","B12 deficiency"],"ans":1,"expl":"Pure red cell aplasia can occur after >8 weeks of ESA use, caused by an antibody-mediated response against erythropoietin. It presents with a sudden rapid Hgb drop and low reticulocyte count. Consideration is given to discontinuing the ESA.","obj":5},
  {"topic":"Kidney Disease","q":"The nurse administering intravenous iron dextran would observe the patient for at least how long after the first dose?","opts":["15 minutes","30 minutes","60 minutes","90 minutes"],"ans":2,"expl":"With IV iron dextran use, monitor the patient for at least 60 minutes after the first dose due to risk of infusion reaction.","obj":5},
  {"topic":"Kidney Disease","q":"Which best describes the mechanism by which ACE inhibitors (ACEi) lower blood pressure and protect the kidney?","opts":["They block angiotensin II receptors directly","They block conversion of angiotensin I to angiotensin II, causing vasodilation and dilating the efferent arteriole","They increase aldosterone secretion","They constrict the afferent arteriole"],"ans":1,"expl":"ACEi block conversion of angiotensin I to angiotensin II, lowering BP via vasodilation. They are renal protective because they dilate the efferent arteriole, decreasing intraglomerular pressure and reducing protein/albumin leakage. ARBs block the angiotensin II receptor.","obj":2},
  {"topic":"Kidney Disease","q":"A patient newly started on an ACE inhibitor develops a chronic dry cough. What is the appropriate nursing understanding of this side effect?","opts":["It requires immediate discontinuation of all antihypertensives","It occurs with ACEi use and is managed by switching to an ARB","It indicates anaphylaxis","It is harmless and requires no change"],"ans":1,"expl":"A chronic cough can develop with ACEi use. The module advises that this is addressed by changing to an ARB (angiotensin II receptor blocker).","obj":2},
  {"topic":"Kidney Disease","q":"When initiating or changing the dose of an ACEi or ARB, the nurse expects serum potassium and creatinine to be reassessed within what general timeframe?","opts":["24 hours","2-4 weeks","6 months","1 year"],"ans":1,"expl":"Guidelines generally recommend evaluating serum potassium and creatinine within 2-4 weeks of initiating or changing the dose of an ACEi/ARB, given the risk of hyperkalemia and AKI.","obj":2},
  {"topic":"Kidney Disease","q":"For a patient with CKD who may be prone to acute kidney injury, when should consideration be given to holding nephrotoxic agents?","opts":["eGFR below 90 ml/min/1.73m²","eGFR below 60 ml/min/1.73m²","eGFR below 30 ml/min/1.73m²","Only when on dialysis"],"ans":1,"expl":"Consideration to hold potentially nephrotoxic agents and/or renally excreted drugs is advised when there is concern for AKI in those with eGFR <60 ml/min/1.73m².","obj":2},
  {"topic":"Kidney Disease","q":"According to the module, which diuretic class is NOT part of the standard diuretic categories used in CKD?","opts":["Loop diuretics","Thiazide and thiazide-like","Aldosterone antagonists","Carbonic-anhydrase-type ACE inhibitors"],"ans":3,"expl":"The module lists loop diuretics, aldosterone antagonists, thiazides/thiazide-like, potassium-sparing, and carbonic anhydrase inhibitors as diuretic types. 'Carbonic-anhydrase-type ACE inhibitors' is not a real class (carbonic anhydrase inhibitors are diuretics; ACE inhibitors are not diuretics).","obj":2},
  {"topic":"Kidney Disease","q":"Which of the following is a Black Box Warning associated with the HIF-prolyl hydroxylase inhibitors (e.g., daprodustat) used for anemia of CKD?","opts":["Acute liver failure","Increased risk of death, myocardial infarction, stroke, venous thromboembolism, and thrombosis of vascular access","Severe hypoglycemia","Pulmonary fibrosis"],"ans":1,"expl":"HIF-prolyl hydroxylase inhibitors (daprodustat/Jesduvroq) carry a Black Box Warning of increased risk of death, MI, stroke, VTE, and thrombosis of vascular access. They increase endogenous erythropoietin and are for those on dialysis at least 4 months.","obj":5},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD2};
