// BATCH 20: NEW questions from ANNA Module 8 Part 2 ("pearls": PD, home HD, transplant, CRRT).
// Verified against module text.
const NEW_QUESTIONS_MOD8E = [
  {"topic":"Peritoneal Dialysis","q":"Which statement about peritoneal dialysis adequacy is correct per the module?","opts":["KT/V target is 1.2 regardless of symptoms","KT/V > 1.7 (CMS target) AND control of symptoms, BP, and electrolytes, adding residual kidney function","KT/V does not matter in PD","Only symptoms matter"],"ans":1,"expl":"PD adequacy is KT/V >1.7 (CMS target) AND control of symptoms, BP, and electrolytes, with residual kidney function (RKF) added and protected (RAAS blockade, avoid dehydration).","obj":3},
  {"topic":"Peritoneal Dialysis","q":"Which is a classic PD dialysate characteristic the nurse should recall?","opts":["Always contains potassium","Potassium-free, almost all are lactate buffered, and UF is based on osmolality (dextrose or icodextrin)","Sodium-free","Bicarbonate-buffered only"],"ans":1,"expl":"PD dialysate is potassium-free, almost all are lactate buffered, and ultrafiltration is based on osmolality (dextrose or icodextrin). PD catheter care focuses on infection prevention and optimal placement.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"To protect the peritoneal membrane, the nurse should avoid which practice?","opts":["Using the lowest osmolar dialysate that works","Prolonged exposure to higher dextrose-content dialysates","Performing PET to prescribe by membrane type","Monitoring for membrane (UF) failure"],"ans":1,"expl":"Protect the peritoneal membrane by avoiding prolonged exposure to higher dextrose-content dialysates and by monitoring for membrane failure as UF failure (e.g., 2-4 hour dwell with 4.25% giving <400 mL UF). Prescribe based on membrane type via PET.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"Up to what percentage of PD peritonitis cases may be sterile (negative cultures)?","opts":["50%","Up to 15%","2%","75%"],"ans":1,"expl":"Up to 15% of PD peritonitis cases may be sterile peritonitis. If cultures are negative or positive with a normal cell count, consider repeating; consider fungal/mycobacterial cultures if still negative. Peritonitis is 2 of 3: clinical symptoms, WBC >100/µL with >50% PMN, or positive culture.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"A PD patient with peritonitis is started on IP antibiotics. What adjunctive measure should the nurse ensure to prevent fungal infection?","opts":["Oral nystatin or fluconazole for fungal prevention while on antibiotics","IV amphotericin","Discontinue all antibiotics","No prophylaxis needed"],"ans":0,"expl":"Provide empiric IP antibiotics pending culture and provide fungal prevention with antibiotics — oral nystatin/fluconazole. This prevents fungal peritonitis during antibiotic therapy.","obj":6},
  {"topic":"Hemodialysis","q":"Which best describes adequacy for other (non-CMS) home hemodialysis schedules per the module?","opts":["Standard KT/V > 2.1 (prefer > 2.3) volumes per week, adding residual kidney function","KT/V of 1.0 weekly","No adequacy target for home HD","KT/V is not applicable at home"],"ans":0,"expl":"For non-CMS home HD schedules (not reported to CMS), standard adequacy is KT/V >2.1 (prefer >2.3) volumes per week, adding RKF. TIW is the same as in-center. Prevent attrition: monitor for burnout, offer respite care, and assess home HD ability continually.","obj":3},
  {"topic":"Transplant","q":"In the transplanted patient, any increase in serum creatinine of what magnitude warrants urgent attention?","opts":["5%","10%","20%-25%","50%"],"ans":2,"expl":"Any increase in creatinine by 20%-25% warrants urgent attention — evaluate for AKI versus rejection and consider kidney biopsy. Transplant is a CKD state; monitor for stable creatinine, proteinuria, and post-transplant complications.","obj":2},
  {"topic":"Acute Therapies","q":"Which statement is TRUE about continuous renal replacement therapy (CRRT)?","opts":["CRRT is 24 hours of intermittent HD","CRRT provides superior volume management to intermittent therapies, uses a catheter (not AVF/AVG), and KDIGO recommends regional citrate anticoagulation","Access should be an AVF or AVG","No anticoagulation is used with CRRT"],"ans":1,"expl":"CRRT pearls: it is not 24 hours of HD, provides superior volume management to intermittent therapies, uses a catheter (do NOT use AVF/AVG), and KDIGO recommends regional citrate anticoagulation. Citrate requires routine assessment of calcium, sodium, and acid-base, and electrolytes are monitored 2-4 times/day.","obj":3},
  {"topic":"Acute Therapies","q":"With CRRT using citrate anticoagulation, which labs require routine assessment?","opts":["Liver enzymes only","Calcium, sodium, and acid-base","Thyroid function","Amylase and lipase"],"ans":1,"expl":"Citrate anticoagulation requires routine assessment of calcium, sodium, and acid-base. Monitor electrolytes 2-4 times a day (and PRN) and replace as indicated. Antibiotics, nutrition, etc., must be adjusted while CRRT runs and after it stops.","obj":3},
  {"topic":"Acute Therapies","q":"Which is a pearl of CRRT that guides nursing care?","opts":["CRRT does not require access type consideration","Tip placement is key to prevent circuit failure, and antibiotics/nutrition must be adjusted when CRRT is running and when it stops","CRRT runs for a fixed 2 hours","AVF is the preferred CRRT access"],"ans":1,"expl":"CRRT: tip placement is key to prevent circuit failure, and medications (antibiotics) and nutrition must be adjusted both while CRRT is running and after it stops. Access is a catheter (not AVF/AVG). There is insufficient evidence for early vs late initiation.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD8E};
