// BATCH 3: NEW questions from ANNA Module 4 (Peritoneal Dialysis).
// Verified against module text. obj: 3=phys/tech, 6=infection control, 2=interventions.
const NEW_QUESTIONS_MOD4 = [
  {"topic":"Peritoneal Dialysis","q":"The nephrology nurse bases teaching on the understanding that the peritoneal membrane makes dialysis possible primarily because it is:","opts":["A one-way lymphatic drainage system","2-3 times body surface area in size","A semi-permeable, bi-directional membrane","Composed of several layers of mesothelial cells"],"ans":2,"expl":"The peritoneal membrane is a semi-permeable membrane that allows bi-directional transport. It allows diffusion of toxins/electrolytes into the dialysate and osmotic removal of fluid (ultrafiltration).","obj":3},
  {"topic":"Peritoneal Dialysis","q":"Which is an absolute contraindication to peritoneal dialysis?","opts":["Abdominal wall hernia","Obesity","Hypercatabolism, where PD cannot adequately remove uremic metabolites","Previous abdominal surgery"],"ans":2,"expl":"Absolute contraindications to PD include hypercatabolism (PD unable to adequately remove uremic metabolites) and inadequate transfer surface area due to adhesions/scarring. Hernia and obesity are surgical considerations, not absolute contraindications.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"The nurse explains that a peritoneal dialysis catheter cuff, usually made of Dacron polyester, serves which purposes?","opts":["Only to secure the catheter to the skin","To filter bacteria from the dialysate","To stabilize the catheter, limit outward movement, block microorganisms, and prevent fluid leaks","To increase dialysate flow rate"],"ans":2,"expl":"The catheter cuff provides material for tissue ingrowth that stabilizes the catheter and limits outward movement, provides a barrier against microorganisms, and prevents fluid leaks.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"During break-in of a new PD catheter, the initial small-volume exchanges are typically scheduled at which points?","opts":["Day 1 and Day 2","Day 7 and Day 14","Day 3 and Day 10","Day 30 and Day 60"],"ans":1,"expl":"Break-in procedures use small-volume exchanges (500 mL), usually done around day 7 and then day 14, to prevent colonization and promote healing. The surgical dressing is not changed for 5-10 days unless bleeding or infection.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"Which dialysate solution can sustain ultrafiltration during a long dwell by using corn starch as its osmotic agent?","opts":["1.5% dextrose","2.5% dextrose","Extraneal (Icodextrin)","4.25% dextrose"],"ans":2,"expl":"Extraneal/Icodextrin is a non-dextrose base solution whose osmotic agent is Icodextrin (corn starch). It sustains ultrafiltration with long dwell (8-16 hours), recommended once per day. Only glucose-specific blood sugar monitors/strips should be used with it.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"A patient on Extraneal (Icodextrin) needs blood glucose monitoring. The nurse's most important instruction is:","opts":["Use any standard glucose monitor","Use only glucose-specific blood sugar monitors and test strips","Check glucose only when symptomatic","Use a blood gas analyzer"],"ans":1,"expl":"With Icodextrin/Extraneal, ONLY glucose-specific blood sugar monitors and test strips should be used, because maltose in the solution interferes with glucose dehydrogenase-based monitors.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"During PD kinetics teaching, the nurse explains that solute transport across the peritoneal membrane is influenced by which factors?","opts":["Only molecular size","Only concentration in the dialysate","The size and charge of the molecule, whether protein-bound, and the concentration gradient between blood and solution","Only the osmotic agent strength"],"ans":2,"expl":"Diffusion of solutes across the peritoneal membrane is influenced by surface area, permeability, molecular size, concentration gradient, solute characteristics, peritoneal blood flow, solution volume, and temperature.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"In peritoneal dialysis, which agent provides the osmotic pull that removes fluid from the body?","opts":["Folate","Chloride","Dextrose","Bicarbonate"],"ans":2,"expl":"Dextrose is the osmotic agent in standard PD solution. The higher the dextrose strength, the higher the osmotic pull. Fluid removal is fastest at the beginning of each exchange when the concentration gradient is highest.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"A patient reports poor fluid (ultrafiltration) removal toward the end of a long dwell. The nurse explains this occurs because:","opts":["The membrane lost its permeability","Reabsorption of water occurs if the dialysate dwells past osmotic equilibrium","The catheter requires rest","Ultrafiltration only works in the first hour"],"ans":1,"expl":"Reabsorption of water occurs if the dialysate is allowed to dwell past osmotic equilibrium. Fluid removal is fastest at the start of the exchange when the dextrose concentration gradient is highest.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"A patient's peritoneal equilibration test (PET) shows a high (fast) transporting membrane. On CAPD you would expect to see:","opts":["Good solute removal and good ultrafiltration","Good solute removal and poor ultrafiltration","Poor solute removal and good ultrafiltration","Poor solute removal and poor ultrafiltration"],"ans":1,"expl":"A high (fast) membrane has very efficient solute transport (good clearance) BUT poor ultrafiltration, because glucose is transported from dialysate to blood quickly, losing the osmotic gradient. These patients benefit from frequent short dwells (APD).","obj":3},
  {"topic":"Peritoneal Dialysis","q":"For a patient with a slow (low) transporting membrane, which is the BEST prescription consideration to maximize clearances?","opts":["Frequent short dwells (APD)","Longer dwell times (CAPD)","Higher dialysate temperatures","More rapid exchanges"],"ans":1,"expl":"Low transporters need longer dwell times (CAPD) to maximize clearances, because their glucose transport is slow, so they can maintain the osmotic gradient even with longer dwell. High transporters need frequent short dwells (APD).","obj":3},
  {"topic":"Peritoneal Dialysis","q":"Which is a characteristic of a healthy PD catheter exit site?","opts":["Exuberant granulation (proud flesh)","Purulent or cloudy drainage","No external drainage and crust is absent or small","Marked erythema and swelling"],"ans":2,"expl":"A healthy exit site has natural/darkened/light-pink surrounding skin, no external drainage, absent or small crust, dry sinus or small clear/thick drainage, and no exuberant granulation tissue.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"Chronic exit-site care for a healed PD catheter, per ISPD 2023, should be performed at what frequency?","opts":["Daily and after every shower","Twice weekly and after a shower","Once a month","Only when visibly dirty"],"ans":1,"expl":"ISPD 2023 recommends chronic exit-site care twice weekly and after a shower, and whenever the exit site becomes wet or dirty. Scabs/crusts should not be forcibly removed.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"A patient's PD effluent is cloudy and the lab shows a white blood cell count greater than 100/mm3 with over 50% polymorphonuclear cells. This is diagnostic of:","opts":["Simple colonization","Peritonitis","Hematuria","Catheter cuff extrusion"],"ans":1,"expl":"Peritonitis is defined by effluent WBC >100/mm3 with >50% PMN, often with abdominal pain and/or cloudy effluent (ISPD: two of three criteria). Classic symptoms are cloudy/turbid effluent and abdominal pain.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"Which organisms are most commonly responsible for PD peritonitis, related to normal skin and nasal flora?","opts":["Gram-negative Pseudomonas","Fungal organisms","Gram-positive organisms such as Staphylococcus epidermidis and S. aureus","Mycobacterium species"],"ans":2,"expl":"Gram-positive organisms cause about 75% of PD peritonitis, related to normal skin and nasal flora (Staphylococcus epidermidis, S. aureus, Enterococcus). Mixed gram-positive/gram-negative is almost always from a GI source.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"A PD patient develops peritonitis that fails to clear after 5 days of appropriate antibiotic therapy. This is classified as:","opts":["Relapsing peritonitis","Refractory peritonitis","Recurrent peritonitis","Catheter-related peritonitis"],"ans":1,"expl":"Refractory peritonitis is defined as symptoms that do not abate after 5 days of appropriate therapy. Relapsing recurs within 4 weeks with the same organism; recurrent occurs within 4 weeks with a different organism.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"The nurse reinforces that which of the following raises a patient's risk for PD peritonitis?","opts":["Frequent handwashing","Domestic pets and hypokalemia","Careful exchange technique","A healed, non-infected exit site"],"ans":1,"expl":"Risk factors for PD peritonitis include domestic pets, hypokalemia, and use of H2-receptor antagonists. Prevention includes meticulous handwashing, individualized training, and managing these risk factors.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"A patient's PD catheter drains poorly. Which is a possible and common cause of poor dialysate outflow?","opts":["Catheter tip in the true pelvis","Cold dialysis solution","Constipation","Short dwell, rapid exchanges"],"ans":2,"expl":"Common causes of a non-functioning PD catheter include constipation (a leading cause), mechanical kink, closed clamps, fibrin blockage, catheter migration, and omental wrap. Constipation is explicitly listed as a common cause of poor outflow.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"Which best explains why PD patients are at increased risk for developing a hernia?","opts":["High glucose content of the solution","Increased intra-abdominal pressure from the dialysate","Poor muscle tone due to inactivity","Altered posture from the solution"],"ans":1,"expl":"Peritoneal dialysis fluid increases intra-abdominal pressure, which is the primary mechanism predisposing PD patients to hernias. Activities that raise intra-abdominal pressure (lifting, Valsalva, coughing) further increase risk.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"A female PD patient reports blood-tinged effluent around the time of menstruation. What is the MOST appropriate nursing response?","opts":["Immediately stop all dialysis","Report as an emergency catheter rupture","Rule out peritonitis, reassure, and consider heparin or room-temperature dialysate to prevent clotting","Remove the catheter"],"ans":2,"expl":"Hemo-peritoneum is more common in females (menstruation/ovulation). Management is to rule out peritonitis, offer reassurance, and use heparin to prevent clotting or room-temperature dialysate.","obj":2},
  {"topic":"Peritoneal Dialysis","q":"Which is a serious, life-threatening complication of long-term PD characterized by fibrous encapsulation of the bowel and a mortality rate over 50%?","opts":["Tunnel infection","Sclerosing encapsulating peritonitis","Hemo-peritoneum","Hydrothorax"],"ans":1,"expl":"Sclerosing encapsulating peritonitis involves a thick fibrous layer encapsulating the bowel with many adhesions. It presents with decreased ultrafiltration/clearances, recurrent pain, and possible bowel obstruction; emergency laparotomy may be needed and mortality exceeds 50%.","obj":2},
  {"topic":"Peritoneal Dialysis","q":"The nurse instructs a PD patient that the dialysis solution should be warmed using:","opts":["A microwave oven for even heating","Hot water submersion of the bag","A warm, dry heating pad - never a microwave","Boiling water"],"ans":2,"expl":"Use warm, dry heat (e.g., a PD heating pad). NEVER microwave — uneven heating of dextrose can cause 1st/2nd degree burns to the peritoneum, and plastic leaching can cause chemical peritonitis.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD4};
