// BATCH 6: NEW questions from ANNA Module 8 (CNN-NP) — 
// selecting only content applicable to the RN-level CNN exam.
// Verified against module text. obj: 5=CKD complications, 2=interventions, 1=pathology.
const NEW_QUESTIONS_MOD8 = [
  {"topic":"Kidney Disease","q":"What are the two most common causes of ESKD requiring dialysis, together accounting for about 65% of newly diagnosed cases?","opts":["Glomerulonephritis and inherited disease","Diabetes mellitus and hypertension","Lupus nephritis and obstruction","Polycystic kidney disease and recurrent UTI"],"ans":1,"expl":"Per the module, Diabetes Mellitus (38% of newly diagnosed ESKD) and Hypertension (27%) together cause about 65% of ESKD cases. Glomerulonephritis is third (~15%).","obj":1},
  {"topic":"Kidney Disease","q":"Which is the third most common cause of CKD/ESKD, affecting the kidneys' filtering units?","opts":["Congenital malformations","Glomerulonephritis","Urinary tract infection","Kidney stones"],"ans":1,"expl":"Glomerulonephritis (diseases that damage the kidneys' filtering units) is the third most common cause at about 15%. Diabetes and hypertension are the two most common.","obj":1},
  {"topic":"Kidney Disease","q":"Which statement is TRUE regarding diabetic kidney disease (DKD)?","opts":["Hematuria is commonly seen early","Glomerular hyperfiltration and kidney hypertrophy are among the earliest changes","It rarely causes albuminuria","Biopsy findings differ between type 1 and type 2 diabetes"],"ans":1,"expl":"Hallmarks of DKD are progressive loss of kidney function and albuminuria; hematuria is not commonly seen. Glomerular hyperfiltration and kidney hypertrophy are among the earliest changes. There are no pathologic differences between DKD from type 1 vs type 2 DM.","obj":1},
  {"topic":"Kidney Disease","q":"In type 1 diabetes, DKD typically has its onset approximately how long after diabetes diagnosis?","opts":["1-2 years","5-10 years","15-20 years","Immediately at diagnosis"],"ans":2,"expl":"In type 1 DM, DKD typically has its onset 15-20 years after diagnosis. Within 25 years, about 25% develop overt DKD. In type 2, DKD can already be present at diagnosis of diabetes.","obj":1},
  {"topic":"Kidney Disease","q":"A patient with diabetic kidney disease is planned for a native kidney biopsy. Which labs should be evaluated BEFORE the procedure per the module?","opts":["Only serum glucose","CBC/platelet count, PT/INR, type and screen, and comprehensive metabolic panel","Only serum creatinine","Urine culture and blood gases"],"ans":1,"expl":"Prior to a kidney biopsy, evaluate medications that increase bleeding risk and obtain CBC/platelet count, PT/INR, type and screen, and a comprehensive metabolic panel. Percutaneous is the preferred technique.","obj":2},
  {"topic":"Kidney Disease","q":"Which of the following is an ABSOLUTE contraindication to a kidney biopsy?","opts":["Controlled hypertension","Solitary kidney or hydronephrosis","Mild anemia","Mild proteinuria"],"ans":1,"expl":"Contraindications to biopsy include uncontrolled hypertension, bleeding risk, skin infection at site, active pyelonephritis, renal abscess, hypotension, uncooperative patient, and solitary kidney. Solitary kidney and hydronephrosis are among those considered more serious/absolute.","obj":2},
  {"topic":"Kidney Disease","q":"The KDIGO Diabetes Work Group (2022) recommends metformin for a type 2 diabetic with CKD at what eGFR threshold?","opts":["eGFR ≥ 60 ml/min/1.73m²","eGFR ≥ 30 ml/min/1.73m²","eGFR ≥ 15 ml/min/1.73m²","eGFR any level"],"ans":1,"expl":"The 2022 KDIGO guideline recommends metformin in type 2 DM + CKD when eGFR ≥30 ml/min/1.73m². Because metformin is cleared by the kidneys, monitor eGFR; dose is reduced (50%) with eGFR <45, and there is a risk of lactic acidosis with reduced renal function.","obj":2},
  {"topic":"Kidney Disease","q":"A CKD patient using an ACEi or ARB is being titrated. The module advises NOT to combine an ACEi with which class of medication?","opts":["Thiazide diuretic concurrently","An ARB or a direct renin inhibitor","An SGLT2 inhibitor","A beta blocker"],"ans":1,"expl":"Do not use any combination of an ACEi and ARB at the same time, nor an ACEi/ARB with a direct renin inhibitor. A mineralocorticoid receptor antagonist (e.g., spironolactone) may be added. Monitor for hyperkalemia and decreased eGFR.","obj":2},
  {"topic":"Kidney Disease","q":"A CKD patient starting an ACEi or ARB should have serum creatinine and potassium checked within what timeframe after initiation or dose increase?","opts":["24 hours","2-4 weeks","3 months","6 months"],"ans":1,"expl":"Serum creatinine and potassium should be evaluated within 2-4 weeks after beginning or increasing the dose of an ACEi or ARB. If potassium is normal and creatinine rises <30%, the dose may be increased to the maximally tolerated dose.","obj":2},
  {"topic":"Kidney Disease","q":"Glomerulosclerosis is BEST described as:","opts":["Reversible scarring that resolves with hydration","Hardening and scarring of the glomerular blood vessels, with permanent damage","Infection of the renal tubules","Cyst formation in the medulla"],"ans":1,"expl":"Glomerulosclerosis is the hardening and scarring of blood vessels within the glomeruli. The damage is permanent, has multiple causes, affects children and adults, leads to proteinuria, and treatment aims at renal protection and preventing further damage.","obj":1},
  {"topic":"Kidney Disease","q":"A patient asks about kidney biopsy technique. The nurse explains the preferred technique is:","opts":["Open surgical biopsy","Percutaneous biopsy","Transvenous biopsy","Laparoscopic biopsy"],"ans":1,"expl":"Kidney biopsy can be done percutaneously (the preferred technique) or by non-percutaneous methods (laparoscopic, transvenous, open). It aids diagnosis and selection of therapy, and in transplant can differentiate causes of deterioration, hematuria, or proteinuria.","obj":2},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD8};
