// BATCH 19: NEW questions from ANNA Module 8 Part 2 (volume management, anticoagulation).
// Verified against module text.
const NEW_QUESTIONS_MOD8D = [
  {"topic":"CKD Complications","q":"Which ultrafiltration rate (UFR) is associated with the LOWEST mortality risk during hemodialysis?","opts":["Greater than 13 mL/kg/hour","Less than or equal to 10 mL/kg/hour","20 mL/kg/hour","15 mL/kg/hour"],"ans":1,"expl":"A UFR ≤10 mL/kg/hour is associated with the lowest risk, while >13 mL/kg/hour carries a higher mortality risk. Rapid UFR is also associated with a decline in residual kidney function. Older patients and those with vascular disease may be at higher risk.","obj":3},
  {"topic":"CKD Complications","q":"Which UFR is associated with a HIGHER mortality risk during hemodialysis?","opts":["Under 8 mL/kg/hour","Greater than 13 mL/kg/hour","10 mL/kg/hour","5 mL/kg/hour"],"ans":1,"expl":"A UFR >13 mL/kg/hour is associated with higher mortality risk, whereas ≤10 mL/kg/hour carries the lowest risk. Individualize the UFR (monitored as mL/kg/hour) and increase treatment time as needed.","obj":3},
  {"topic":"CKD Complications","q":"Which point-of-care ultrasound finding is used to assess volume status?","opts":["Inferior vena cava diameter (collapsible >50%, 13-21 mm), lung water, and echocardiography with ejection fraction","Carotid intimal thickness","Thyroid gland size","Bone density"],"ans":0,"expl":"POCUS for volume status includes inferior vena cava diameter (collapsible >50%, 13-21mm), lung water ultrasound, and echocardiography (elevated RVSP, ventricular filling volumes). Other tools include history, BP trends, physical exam, passive leg raise, orthostatic BPs, labs, and bioimpedance.","obj":3},
  {"topic":"CKD Complications","q":"The optimal 'estimated dry weight' (EDW) for a dialysis patient is BEST defined as:","opts":["The lowest weight the patient ever had","The weight at which the patient is asymptomatic with no exam evidence of hyper- or hypovolemia and controlled BP, used to target fluid removal during dialysis","A fixed weight set at initiation of dialysis and never changed","The patient's highest recorded weight"],"ans":1,"expl":"Estimated dry weight is the weight at which the patient is asymptomatic, with no physical exam evidence of hyper- or hypovolemia and controlled BP — the targeted weight to remove fluid during dialysis. It's 'probed' (adjusted) only when clinically indicated, e.g., long-term volume overload or rising BPs.","obj":3},
  {"topic":"CKD Complications","q":"Rapid ultrafiltration is associated with decline in what?","opts":["Serum albumin","Residual kidney function (RKF)","Hematocrit","Body temperature"],"ans":1,"expl":"Rapid UFR is associated with a decline in residual kidney function (RKF). Hence individualize UFR, monitor as mL/kg/hour, and support/use residual kidney function and diuretics as able.","obj":3},
  {"topic":"CKD Complications","q":"Which anticoagulant used in dialysis has a half-life of only about 45 minutes to 1 hour, is inexpensive and widely available, but carries a risk of heparin-induced thrombocytopenia (HIT)?","opts":["Unfractionated heparin","Citrate-based dialysate","Saline flush","Low molecular weight heparin"],"ans":0,"expl":"Unfractionated heparin has a half-life of 45 min to 1 hour, is inexpensive and widely available, but risks bleeding and heparin-induced thrombocytopenia (HIT). Low-molecular-weight heparin has a 3-4 hour half-life and is more expensive.","obj":3},
  {"topic":"CKD Complications","q":"Which dialysis anticoagulation option involves no systemic anticoagulant exposure but is cumbersome for staff and risks clotting/blood loss?","opts":["Unfractionated heparin","Saline flush","Citrate-based dialysate","Low molecular weight heparin"],"ans":1,"expl":"A saline flush has no exposure to anticoagulation but is cumbersome for staff and risks clotting/blood loss. Citrate-based dialysate is convenient and acetate-free, though it can cause hypocalcemia (rare) and often requires additional anticoagulation.","obj":3},
  {"topic":"CKD Complications","q":"Which is a potential adverse effect of citrate-based dialysate anticoagulation?","opts":["Hypercalcemia","Hypocalcemia (rare), and the dialysate often requires additional anticoagulation","Hyperkalemia","HIT"],"ans":1,"expl":"Citrate-based dialysate anticoagulation is convenient (dialysate-based, acetate-free), but risk includes hypocalcemia (rare) and the dialysate often requires additional anticoagulation.","obj":3},
  {"topic":"CKD Complications","q":"When managing a dialysis patient's volume, which nursing measure helps control volume overload?","opts":["Generous sodium and fluid intake","Low-salt diet, controlled volume intake, support/use residual kidney function, and maximize diuretics as able","Increasing dietary protein","Avoiding all diuretics"],"ans":1,"expl":"Volume control involves achieving EDW (or a range), low-salt diet, controlled volume intake, supporting/using residual kidney function, maximizing diuretics as able, and individualizing the ultrafiltration rate.","obj":3},
  {"topic":"CKD Complications","q":"Which lab trend is used to evaluate volume status, since dilution affects its concentration?","opts":["Serum sodium and albumin (dilution effect)","Hemoglobin A1c","Liver enzymes","Urine specific gravity"],"ans":0,"expl":"Labs using the dilution effect (such as serum sodium and albumin) help evaluate volume status. Other tools include history, weight, BP trends, physical exam, and imaging such as IVC/lung ultrasound and echocardiography.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD8D};
