// BLUEPRINT GAP FIX — NEW questions for the two starved objectives.
// Written by Claude Code 2026-09-24, NOT yet merged into content.js.
//
// WHY: the practice test claims blueprint weighting but Teaching/learning and
// Collaboration & QI are content-starved, so the backfill silently reallocates
// ~15 questions into KRT/pathophysiology. See the review notes.
//
// obj taxonomy (matches TEST_WEIGHTS in index.html):
//   4 = Teaching/learning        (blueprint 15%, needs 22 per exam)
//   7 = Collaboration & QI       (blueprint 13%, needs 20 per exam)
//
// These 15 are APPLICATION questions — they assess the domain itself
// (patient education, health literacy, teach-back, care coordination,
//  interdisciplinary referral, QI method, safety reporting, advocacy),
// NOT clinical recall re-filed under these objectives.
//
// REVIEW by Oliver before merging.
const NEW_OBJ4_OBJ7_QUESTIONS = [
  /* ================= OBJ 4 — TEACHING / LEARNING (6) ================= */
  {"topic":"Peritoneal Dialysis","q":"A nurse teaches a patient to perform a peritoneal dialysis exchange, then asks the patient to demonstrate the procedure and explain it in their own words. Which teaching principle does this best illustrate?","opts":["Teach-back, which verifies comprehension and corrects misunderstanding","Scaffolding, which builds new skills on previously mastered ones","Readiness to learn, which assesses motivation before teaching","Andragogy, which tailors content to adult learners"],"ans":0,"expl":"Having the patient demonstrate and restate in their own words is teach-back. It verifies true comprehension rather than assuming it because teaching was delivered, and it surfaces gaps while the nurse can still correct them.","obj":4},
  {"topic":"Hemodialysis","q":"A nurse is preparing written discharge instructions for a hemodialysis patient with limited health literacy. Which approach best supports learning?","opts":["Provide detailed instructions written at a 12th-grade reading level for accuracy","Use plain language at roughly a 5th-6th grade level, with pictures and the most important actions first","Give the patient the dialysis unit's printed infection-control policy","Rely on the family to explain the instructions to the patient later"],"ans":1,"expl":"Health-literacy guidance recommends plain language at about a 5th-6th grade level, limited to the most important actions, ideally with visual cues. Materials written above the patient's literacy level are unlikely to be read or acted on, and delegating teaching to family does not confirm the patient's own understanding.","obj":4},
  {"topic":"Acute Therapies","q":"A patient hospitalized with a first episode of acute kidney injury becomes tearful and says they cannot think about dialysis teaching right now. Which action by the nurse is most appropriate?","opts":["Proceed with the teaching plan because discharge is scheduled tomorrow","Give the full teaching packet to read later and document that education was provided","Acknowledge the patient's distress, address immediate concerns, and teach in short sessions once the patient is ready","Ask the provider to explain dialysis to the patient instead"],"ans":2,"expl":"Readiness to learn is a prerequisite for effective education; anxiety, shock, and pain block learning. Acknowledging the emotion and delivering brief, repeated teaching when the patient is receptive is more effective than content delivered on schedule. Handing over a packet documents delivery, not learning.","obj":4},
  {"topic":"Hemodialysis","q":"Which finding best demonstrates that a hemodialysis patient has achieved the learning outcome for self-cannulation of an arteriovenous fistula?","opts":["The patient correctly lists the steps of cannulation from memory","The patient verbalizes understanding of the infection risk","The patient independently performs the cannulation correctly using aseptic technique","The patient states they feel ready to try cannulation at home"],"ans":2,"expl":"When the outcome is a psychomotor skill, competence is demonstrated by correct independent performance, not verbalization. Listing steps or stating readiness reflects knowledge or confidence, neither of which confirms the skill itself.","obj":4},
  {"topic":"Hemodialysis","q":"Which statement by a hemodialysis patient best indicates that dietary teaching about fluid restriction has been effective?","opts":["'I drink as much as I want and let the machine take it off.'","'I keep my gain under about 2 to 3 kilograms between treatments and avoid salty foods.'","'I only count the water I drink, not soup or ice.'","'I stop drinking fluids the day before my treatment.'"],"ans":1,"expl":"Effective teaching shows up as a specific, accurate behavior: limiting interdialytic gain to roughly 2-3 kg and reducing sodium, which drives thirst. The other statements reveal misunderstandings. All fluids count, including soup and ice; large gains are dangerous rather than acceptable; and withholding fluids right before treatment does not reduce total gain.","obj":4},
  {"topic":"Peritoneal Dialysis","q":"A nurse planning to teach a newly diagnosed patient how to perform PD exchanges should first prioritize which action?","opts":["Assessing the patient's readiness, prior experience, and preferred learning style","Demonstrating a full exchange before any discussion","Providing the PD manual to the patient to review independently","Scheduling six consecutive hours of teaching in one day"],"ans":0,"expl":"Adult learning is most effective when the teacher first assesses readiness, baseline knowledge, and preferences, then paces teaching accordingly. Demonstrating or handing over materials without that assessment, or compressing all teaching into a single long session, works against retention and engagement.","obj":4},

  /* ============ OBJ 7 — COLLABORATION & QI (9) ============ */
  {"topic":"Peritoneal Dialysis","q":"A dialysis facility's PD peritonitis rate has risen above the national benchmark for two consecutive quarters. Which initial action by the nurse is most consistent with quality improvement principles?","opts":["Review the data and the contributing processes with the interdisciplinary team to identify root causes","Retrain every patient on PD exchange technique immediately","Discontinue PD for patients who developed peritonitis and switch them to hemodialysis","Report the rate to the governing body and take no further action until next quarter"],"ans":0,"expl":"QI begins with understanding the process and its variation before changing it, which means reviewing data with the interdisciplinary team to find root causes across patient technique, training, supplies, and staffing. Retraining or discontinuing therapy may be part of the eventual plan, but acting before causes are understood risks fixing the wrong problem.","obj":7},
  {"topic":"Kidney Disease","q":"A patient with CKD stage 5 is being discharged to a long-term care facility. Which nursing action best demonstrates care coordination?","opts":["Send the discharge summary to the receiving facility and document that the transfer is complete","Arrange direct communication with the receiving facility's team about dialysis schedule, dietary needs, and medication reconciliation","Provide the patient with a list of nephrology clinics to contact","Ask the patient to inform the receiving facility about their dialysis needs"],"ans":1,"expl":"Care coordination requires direct, closed-loop communication between teams to confirm schedule, diet, and medications. Simply transmitting a document, or shifting the responsibility to a patient who may be unable to advocate for themselves in a new setting, does not ensure continuity.","obj":7},
  {"topic":"CKD Complications","q":"Which member of the interdisciplinary team is the most appropriate referral for a patient struggling with the dietary demands of a new renal diet?","opts":["The nephrologist","The renal dietitian","The social worker","The dialysis technician"],"ans":1,"expl":"The renal dietitian holds the expertise in translating dietary restrictions into a plan that fits this patient's intake, culture, and medication schedule. Referring to the correct discipline is a core collaboration skill, since each team member has a distinct scope of practice.","obj":7},
  {"topic":"Hemodialysis","q":"A nurse discovers that a colleague administered the wrong dose of epoetin to a dialysis patient. Which action best reflects professional accountability and patient safety?","opts":["Correct the documentation so the record reflects the intended dose","Report the error through the facility's incident reporting system, and ensure the patient is assessed and the provider notified","Discuss the error privately with the colleague and agree to watch each other more closely in future","Wait to see whether the patient develops any symptoms before deciding whether to report"],"ans":1,"expl":"Patient safety and QI depend on accurate, non-punitive error reporting with a focus on system factors. Altering documentation conceals the event, a private agreement leaves the system unchanged, and waiting for harm turns a near-miss into a preventable injury. The patient must also be assessed and the provider informed.","obj":7},
  {"topic":"Hemodialysis","q":"A nurse wants to reduce catheter-related bloodstream infections in the hemodialysis unit. Which initial step best reflects an evidence-based approach?","opts":["Implement a checklist a colleague used at another facility","Review current evidence-based guidelines alongside the unit's own infection data to identify gaps before choosing an intervention","Increase the frequency of catheter dressing changes for all patients","Ask the medical director to issue a directive requiring stricter technique"],"ans":1,"expl":"Evidence-based practice combines the best available evidence with the unit's own data and patient circumstances. Acting on a colleague's checklist, an untargeted change, or a directive alone skips the assessment step and may not address the actual source of infection in this unit.","obj":7},
  {"topic":"CKD Complications","q":"Which action by the nephrology nurse best demonstrates participation in a facility's quality assurance and performance improvement (QAPI) program?","opts":["Collecting and tracking the unit's clinical outcome measures and presenting findings to the interdisciplinary team","Completing required annual competency training","Following the facility's infection control policy during every treatment","Documenting patient assessments thoroughly in the medical record"],"ans":0,"expl":"Following policy, completing training, and documenting well are essential baseline responsibilities. QAPI participation specifically means engaging with the measurement and analysis of outcomes and bringing that data to the team: the improvement cycle itself, not individual compliance alone.","obj":7},
  {"topic":"Transplant","q":"A potential living kidney donor asks the nurse questions about the risks of donation. Which action is most appropriate?","opts":["Answer the questions and reassure the donor that donation is safe","Refer the donor to the transplant team for an independent evaluation, and advocate that the decision be free of pressure from the recipient","Ask the recipient to explain the risks to the donor","Encourage the donor to proceed since the recipient's need is urgent"],"ans":1,"expl":"Living donors require an evaluation independent of the recipient's team and protection from coercion, which is a core ethical and advocacy responsibility in transplant. Reassurance, delegating the explanation to the recipient, or leveraging urgency all compromise the donor's ability to make a voluntary, informed decision.","obj":7},
  {"topic":"Hemodialysis","q":"During a handoff between dialysis shifts, which approach best ensures continuity and safety for a patient who became hypotensive mid-treatment?","opts":["A brief verbal summary of the most recent vital signs","A structured handoff covering the event, interventions given, current status, and what to watch for","A note in the chart that the patient had a hypotensive episode","A message left with the front desk for the oncoming nurse"],"ans":1,"expl":"Structured handoff communication, covering what happened, what was done, current status, and anticipated risks, is a recognized patient-safety practice. Brief verbal summaries, chart notes alone, or indirect messages omit the reasoning and contingencies the next nurse needs in order to act safely.","obj":7},
  {"topic":"Kidney Disease","q":"A patient on hemodialysis has repeatedly missed treatments. Which approach best reflects interdisciplinary collaboration?","opts":["The nurse documents each missed treatment and continues with the plan of care","The nurse discusses the pattern with the social worker and team to identify barriers such as transportation, housing, or depression","The nurse asks the nephrologist to discharge the patient from the unit","The nurse calls the patient after each missed treatment to remind them of the schedule"],"ans":1,"expl":"Missed treatments usually reflect barriers that a single discipline cannot resolve, such as transportation, housing instability, cost, depression, or substance use. Bringing the team and social worker in addresses the root cause, while documentation alone, discharge, or repeated reminders do not change the underlying problem.","obj":7},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_OBJ4_OBJ7_QUESTIONS};
