// BATCH 9: NEW questions from ANNA Module 5 (Transplant) — donors, matching, meds, complications.
// Verified against module text. obj: 2=interventions, 1=pathology, 4=teaching.
const NEW_QUESTIONS_MOD5B = [
  {"topic":"Transplant","q":"Which ABO blood type is the universal DONOR in kidney transplantation?","opts":["A","AB","B","O"],"ans":3,"expl":"O is the universal donor: an O recipient can only receive from O, but an O donor can donate to any blood type. AB is the universal recipient (can receive A, B, AB, or O).","obj":1},
  {"topic":"Transplant","q":"A candidate with blood type B is awaiting a transplant. From which donor blood types may they receive a kidney?","opts":["Only B","B or O","A, B, AB, or O","Only AB"],"ans":1,"expl":"A B recipient can only receive from a B or O donor. AB recipients can receive from any type; O recipients only from O; A recipients from A or O.","obj":1},
  {"topic":"Transplant","q":"Which best describes the function of Human Leukocyte Antigens (HLA) in transplantation?","opts":["They carry oxygen in the blood","They help the body recognize 'self' from 'non-self' and are easiest to isolate from lymphocytes (WBCs), with HLA loci on chromosome 6","They produce antibodies against the kidney","They regulate blood pressure"],"ans":1,"expl":"HLA are surface proteins on most cells, easiest to isolate from lymphocytes. They help the body distinguish self from non-self. HLA loci are on chromosome 6; there are 118 known antigens, six inherited (3 from each parent).","obj":1},
  {"topic":"Transplant","q":"A transplant candidate's blood is tested against a panel of random donors, and it reacts against 30 of 50 (60%). What is this test and what does the result indicate?","opts":["Crossmatch; the candidate can accept any donor","Panel Reactive Antibodies (PRA); a higher PRA means more hard-to-match, sensitized against foreign HLA","HLA typing; it identifies the donor's antigens","EPTS; it predicts survival"],"ans":1,"expl":"PRA (percent reactive antibody) tests the candidate's serum against a panel of random donors. Reacting to 30/50 = 60% PRA. A PRA >80% is 'highly sensitized'; the higher the PRA, the harder to find a match. PRA is for the candidate only.","obj":1},
  {"topic":"Transplant","q":"In a serum crossmatch, the candidate's serum is combined with the donor's lymphocytes. What does a POSITIVE crossmatch indicate?","opts":["The transplant will definitely succeed","The candidate has antibodies against the donor's antigens, so transplant is contraindicated","The donor is a universal donor","Tissue typing was incomplete"],"ans":1,"expl":"A positive crossmatch means the candidate's antibodies bind to and destroy the donor's cells, indicating pre-formed antibodies against the donor's antigens. A positive crossmatch is a contraindication to transplant.","obj":1},
  {"topic":"Transplant","q":"Which two scoring systems are used in the new kidney allocation system for deceased donors and candidates respectively?","opts":["KDPI for donors and EPTS for candidates","EPTS for donors and KDPI for candidates","PRA for donors and HLA for candidates","KDPI for both donors and candidates"],"ans":0,"expl":"KDPI (Kidney Donor Profile Index) scores deceased donors 0-100% (lower = more longevity). EPTS (Estimated Post Transplant Survival) scores candidates 0-100% (lower = expected to live longest). The system matches lower-KDPI donors with lower-EPTS candidates.","obj":2},
  {"topic":"Transplant","q":"A deceased donor kidney with a low KDPI score (closer to 0%) indicates:","opts":["A kidney with shorter expected function","A kidney likely to function longer after transplant","A donor who had hypertension","A kidney unsuitable for transplant"],"ans":1,"expl":"For deceased donors, lower KDPI scores are associated with more kidney longevity (longer expected function). KDPI is calculated from donor age, height, weight, ethnicity, HTN history, diabetes, cause of death, creatinine, HCV status, and DCD.","obj":2},
  {"topic":"Transplant","q":"Which is a contraindication to living kidney donation?","opts":["Age 30","BMI 25","Positive crossmatch or ABO incompatibility","Hypertension that is well controlled per center policy"],"ans":2,"expl":"Contraindications to living donation include ABO incompatibility, positive crossmatch, age <18, infectious disease, diabetes, significant medical/mental illness, psychosocial or financial risks. Some (BMI, HTN, GFR) are center-specific.","obj":2},
  {"topic":"Transplant","q":"UNOS guidelines require transplant centers to provide every living donor with which safeguard?","opts":["A transplant coordinator only","An independent living donor advocate (ILDA), who provides non-biased counsel and is not involved in the candidate's care","A mandatory financial advisor","A second nephrologist"],"ans":1,"expl":"UNOS requires an independent living donor advocate (ILDA) to guide each living donor through evaluation and provide non-biased counsel. The ILDA has no role in the candidate's care and can be a social worker, nurse, chaplain, PCP, etc.","obj":2},
  {"topic":"Transplant","q":"Kidney Paired Donation (KPD) refers to:","opts":["Donating a kidney to a stranger without any relationship","Two or more incompatible living donor pairs swapping donors so each recipient gets a compatible kidney","Transferring a deceased donor kidney between centers","A single altruistic donation"],"ans":1,"expl":"KPD allows two or more incompatible living donor pairs to swap kidney donors with another incompatible pair, so each recipient gets a compatible kidney. It can be a two-pair swap or a chain, via internal programs or registries (NKR, Alliance, UNOS KPD).","obj":2},
  {"topic":"Transplant","q":"Which best describes a deceased donor by Donation after Circulatory Death (DCD)?","opts":["Death determined by neurologic criteria","Death determined by cardio-respiratory criteria","A donor who is still brain alive","A living related donor"],"ans":1,"expl":"Donation after brain death (DBD) uses neurologic criteria; Donation after circulatory death (DCD) uses cardio-respiratory criteria. Both are deceased donor categories.","obj":2},
  {"topic":"Transplant","q":"The most frequent cause of secondary bacteremia in a kidney transplant recipient is:","opts":["Pneumonia","Urinary tract infection (UTI)","Surgical site infection","Catheter-related bloodstream infection"],"ans":1,"expl":"UTIs are the most frequent cause of secondary bacteremia in a kidney transplant recipient. In the immediate post-transplant period, UTIs relate to surgical instrumentation and are encouraged by ureteral stenting and anatomic variations.","obj":1},
  {"topic":"Transplant","q":"Cytomegalovirus (CMV) infection after transplant is most likely to occur during which timeframe, and which type is most serious?","opts":["First 1-4 months; primary CMV (donor+ to recipient-)","First 24 hours; any CMV","First 2 years; CMV in the urine","Last 6 months; reactivation only"],"ans":0,"expl":"CMV has a higher incidence in the first 1-4 months post-transplant. Primary CMV infections (CMV donor+ kidney into a CMV- recipient) are the most serious. It is acquired from the donor kidney, reactivation of latent virus, or blood products.","obj":1},
  {"topic":"Transplant","q":"Which medication combination is used to PREVENT Pneumocystis jiroveci pneumonia (PJP) after transplant?","opts":["Trimethoprim/sulfamethoxazole (Bactrim), dapsone, inhaled pentamidine, or atovaquone","Acyclovir and valganciclovir","Clotrimazole and nystatin","Omeprazole and famotidine"],"ans":0,"expl":"PJP prophylaxis uses trimethoprim/sulfamethoxazole (Bactrim), dapsone, inhaled pentamidine, or atovaquone. Antivirals (acyclovir, ganciclovir) prevent CMV/herpes; antifungals (nystatin, clotrimazole) prevent thrush.","obj":2},
  {"topic":"Transplant","q":"Which immunosuppressant is CONTRAINDICATED in EBV-negative recipients due to increased risk of post-transplant lymphoproliferative disorder (PTLD)?","opts":["Tacrolimus","Belatacept (Nulojix)","Mycophenolate","Prednisone"],"ans":1,"expl":"Belatacept (Nulojix), a T-cell co-stimulation blocker, has an increased risk of PTLD and is therefore contraindicated in EBV-negative patients. It is given as IV infusions on POD 1 and 5, weeks 2,4,8,12, then monthly.","obj":2},
  {"topic":"Transplant","q":"A transplant patient develops hemorrhagic cystitis and alopecia while receiving treatment for rejection. Which medication is most likely responsible?","opts":["Rituximab","Cytoxan (cyclophosphamide)","Thymoglobulin","Oral prednisone"],"ans":1,"expl":"Cytoxan (cyclophosphamide) side effects include hemorrhagic cystitis, alopecia, and sterility. Other rejection treatments (Atgam, Thymoglobulin, Rituximab) cause flu-like symptoms, leukopenia, and opportunistic infections.","obj":2},
  {"topic":"Transplant","q":"Which statement characterizes the placement of a transplant kidney during surgery?","opts":["Placed in the iliac fossa outside the extraperitoneal space, with the renal artery to the external iliac artery","Placed in the upper abdomen within the peritoneum","Arterial anastomosis to the aorta","Ureter remains in situ"],"ans":0,"expl":"The donor kidney is placed in the iliac fossa outside the extraperitoneal space. The renal artery is anastomosed to the external iliac artery, the renal vein to the iliac vein, and the ureter is tunneled into the bladder or connected to the recipient ureter.","obj":2},
  {"topic":"Transplant","q":"The most common cause of long-term allograft loss, characterized by interstitial fibrosis and tubular atrophy, is:","opts":["Hyperacute rejection","Chronic allograft nephropathy (IFTA)","Acute cellular rejection","Polyoma virus nephropathy"],"ans":1,"expl":"Chronic allograft nephropathy (chronic rejection / IFTA) is the most common cause of long-term allograft loss. Onset is months to years with proteinuria, rising creatinine, and hypertension. Risk factors include donor age, prolonged ischemia, delayed graft function, CNI toxicity, non-adherence.","obj":1},
  {"topic":"Transplant","q":"A kidney transplant recipient develops fever, elevated WBC, myalgias, and a rising creatinine days to weeks after surgery. This most likely represents:","opts":["Hyperacute rejection","Acute (cell-mediated, T-cell) rejection","Chronic allograft nephropathy","Urinary tract infection only"],"ans":1,"expl":"Acute T-cell (cell-mediated) rejection is the most common form of early rejection, occurring days to weeks post-transplant, with fever, elevated WBC, malaise, rising creatinine/BUN, and decreased urine output. If donor-specific antibody is present, plasma exchange may be needed.","obj":1},
  {"topic":"Transplant","q":"In patient education, which is the MOST important content the nurse covers regarding immunosuppressive medications?","opts":["They can be stopped once the kidney functions","Name, dose, action, frequency, and side effects, plus signs/symptoms of rejection and follow-up","They cause no side effects","Diet is the only thing that matters"],"ans":1,"expl":"Patient education emphasizes medication name/dose/action/frequency/side effects (with a written schedule or app), signs and symptoms of rejection, follow-up tests/visits, and record-keeping (I&O, daily weight, temperature, BP, blood sugar).","obj":4},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD5B};
