// BATCH 5: NEW questions from ANNA Module 6 (Acute Therapies).
// Verified against module text. obj: 3=phys/tech, 1=pathophysiology.
const NEW_QUESTIONS_MOD6 = [
  {"topic":"Acute Therapies","q":"A patient on dialysis in an acute unit, who is critically ill requiring continuous monitoring, should receive what RN-to-patient ratio per the module?","opts":["1:4","1:3","1:1","1:2 in all acute settings"],"ans":2,"expl":"The acute unit uses a 1:2 RN-to-patient ratio, but the standard for the critically ill ICU population is 1:1. A 1:2 ratio is used for the general acute unit.","obj":3},
  {"topic":"Acute Therapies","q":"The nurse uses the mnemonic 'AEIOU' as a reminder of indications for emergent dialysis. The 'O' in AEIOU stands for:","opts":["Osmolarity","Overload (fluid overload / respiratory distress)","Oliguria","Obstruction"],"ans":1,"expl":"AEIOU: A-Acidosis (metabolic), E-Electrolyte imbalance (hyperkalemia), I-Ingestion/poisoning, O-Overload (fluid overload/respiratory distress), U-Uremia (pericarditis/encephalopathy).","obj":3},
  {"topic":"Acute Therapies","q":"Which of the following meets the KDIGO diagnostic criterion for acute kidney injury (AKI)?","opts":["Increase in SCr by 0.3 mg/dL within 48 hours","SCr increase to 1.1 times baseline","Urine volume of 1 mL/kg/h for 2 hours","Stable creatinine over 7 days"],"ans":0,"expl":"AKI is defined as an increase in SCr by 0.3 mg/dL (26.5 µmol/L) within 48 hours; OR an increase to 1.5 times baseline within 7 days; OR urine volume <0.5 mL/kg/h for 6 hours.","obj":1},
  {"topic":"Acute Therapies","q":"The most common cause of AKI is:","opts":["Post-renal obstruction","Prerenal (decreased renal blood flow)","Intrinsic acute tubular necrosis","Glomerulonephritis"],"ans":1,"expl":"Pre-renal AKI (a decrease in renal blood flow) is the most common cause of AKI. It reduces GFR but is reversible if the underlying cause of reduced perfusion is corrected.","obj":1},
  {"topic":"Acute Therapies","q":"A patient has damage to the renal parenchyma, with the most common cause being acute tubular necrosis (ATN). This is classified as which type of AKI?","opts":["Pre-renal","Intrinsic (intra-renal)","Post-renal","Prerenal obstruction"],"ans":1,"expl":"Intrinsic (intra-renal) AKI involves damage to the renal parenchyma. The most common causes are acute tubular necrosis (ATN), acute glomerulonephritis, and acute interstitial nephritis. ATN is the most common cause of intrinsic AKI.","obj":1},
  {"topic":"Acute Therapies","q":"Which acute renal replacement therapy is preferred for a hemodynamically UNSTABLE patient in the ICU?","opts":["Intermittent hemodialysis (IHD) with rapid fluid removal","Continuous kidney replacement therapy (CKRT)","Peritoneal dialysis in a hemodynamically unstable patient","Sustained low-efficiency dialysis (SLED) with high ultrafiltration"],"ans":1,"expl":"CKRT is continuous up to 24 hours or more and is used in the ICU for hemodynamically UNSTABLE patients. IHD removes fluid more rapidly and is used in more hemodynamically stable patients.","obj":3},
  {"topic":"Acute Therapies","q":"Which statement characterizes intermittent hemodialysis (IHD) compared to CKRT?","opts":["IHD is gentler on blood pressure and removes fluid slowly","IHD removes fluids and solutes more rapidly and is used in more hemodynamically stable patients","IHD runs continuously for 24 hours","IHD is preferred for unstable ICU patients"],"ans":1,"expl":"IHD removes fluids and solutes more rapidly, with an average prescribed time of 3-4 hours, and is used in a more hemodynamically stable population. CKRT is the choice for unstable patients.","obj":3},
  {"topic":"Acute Therapies","q":"What is the FIRST-choice vascular access for a patient requiring acute dialysis for AKI?","opts":["AV fistula","AV graft","Temporary non-tunneled central venous catheter","Tunneled cuffed catheter"],"ans":2,"expl":"For AKI, the first choice of vascular access is a temporary, non-tunneled central venous catheter. The goal of access is to get the patient on KRT promptly. Subclavian is a less desirable site.","obj":3},
  {"topic":"Acute Therapies","q":"Which is a benefit of acute peritoneal dialysis in the acute setting?","opts":["Requires a water treatment system","Lower cost and does not require a water source","Faster solute clearance than hemodialysis","Best for patients needing rapid fluid removal"],"ans":1,"expl":"Acute PD is underutilized, has lower costs, does not require a water source, offers flexibility, and is desirable for patients with poor vasculature. It does not remove fluid as rapidly as hemodialysis.","obj":3},
  {"topic":"Acute Therapies","q":"The nurse identifies that acute post-renal AKI is caused by:","opts":["Decreased cardiac output","Obstruction that affects urine flow (e.g., prostate issues), decreasing GFR","Nephrotoxin exposure","Acute tubular necrosis"],"ans":1,"expl":"Post-renal AKI is caused by obstruction affecting urine flow (such as prostate enlargement), which decreases GFR. Most patients with acute obstruction regain normal kidney function.","obj":1},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD6};
