// BATCH 7: NEW questions from ANNA Module 3 (Hemodialysis - principles & machine).
// Verified against module text. obj: 3=phys/tech principles.
const NEW_QUESTIONS_MOD3B = [
  {"topic":"Hemodialysis","q":"During hemodialysis, the passive movement of solute from an area of higher concentration to lower concentration across the semipermeable membrane is called:","opts":["Ultrafiltration","Diffusion","Convection","Osmosis"],"ans":1,"expl":"Diffusion is the movement of solute from higher to lower concentration down a concentration gradient, occurring across the dialyzer's semipermeable membrane until dynamic equilibrium is reached. Ultrafiltration is pressure-driven water removal.","obj":3},
  {"topic":"Hemodialysis","q":"In hemodialysis, which process is responsible for the removal of fluid (water) from the blood to the dialysate, driven by transmembrane pressure?","opts":["Diffusion","Ultrafiltration","Osmosis","Convective flux"],"ans":1,"expl":"Ultrafiltration (UF) is the process by which fluid is removed during dialysis, driven by hydrostatic or osmotic force (transmembrane pressure) across the membrane, and is controlled by the HD machine.","obj":3},
  {"topic":"Hemodialysis","q":"Which dialyzer membrane material is associated with better biocompatibility and fewer patient reactions?","opts":["Cellulose (plant-based fiber)","Modified cellulose","Synthetic membranes (polymers and plastic molecules)","All are equal in biocompatibility"],"ans":2,"expl":"Synthetic membranes (polymers and plastic molecules) have improved biocompatibility. Cellulose (plant-based) has many reactions noted; modified cellulose has better biocompatibility than cellulose but less than synthetic.","obj":3},
  {"topic":"Hemodialysis","q":"The nurse recognizes that arterial and venous pressure alarms during hemodialysis help detect complications. A HIGH venous pressure alarm is most likely caused by:","opts":["Hypotension","Kinking of the line between the access and the arterial monitor","Occlusion of the blood line/needle/CVC on the venous side","Wet transducer"],"ans":2,"expl":"High venous pressure alarm is caused by kinking between the monitoring site, malposition/infiltration of the venous needle, or occlusion on the venous side. Hypotension, arterial occlusion, and wet transducer cause LOW pressure alarms.","obj":3},
  {"topic":"Hemodialysis","q":"During hemodialysis, arterial pressure is BEST measured where?","opts":["Between the dialyzer and the venous return","Between the patient and the blood pump","After the venous line clamp","In the dialysate compartment"],"ans":1,"expl":"Arterial pressure is usually measured between the patient and the blood pump. Venous pressure is measured between the dialyzer and the return to the vascular access. Higher blood pump speeds raise both pressures.","obj":3},
  {"topic":"Hemodialysis","q":"Which safety device on the hemodialysis machine prevents inadvertent air from entering the bloodline and returning to the patient?","opts":["Transducer protector","Volumetric balancing chamber","Air detector","Proportioning unit"],"ans":2,"expl":"The air detector is a safety device that avoids inadvertent air getting into the bloodline and returning to the patient. The air detector and venous line clamps must be checked before every dialysis session.","obj":3},
  {"topic":"Hemodialysis","q":"The hemodialysis machine's proportioning unit is responsible for:","opts":["Measuring arterial pressure","Mixing treated water, bicarbonate, and acid in chambers to create dialysate","Delivering the blood to the dialyzer","Anticoagulating the blood"],"ans":1,"expl":"The proportioning unit mixes treated water, bicarbonate, and acid in chambers. The machine continuously monitors conductivity, temperature, pH, flow rate, and the presence of blood (post-dialyzer).","obj":3},
  {"topic":"Hemodialysis","q":"Volumetric balancing chambers in the dialysate system are used to:","opts":["Increase blood flow rate","Manage inflow and outflow of dialysate via flow sensors and allow programmable fluid removal","Warm the dialysate","Detect air in the circuit"],"ans":1,"expl":"Volumetric control systems allow programmable fluid removal and must be used with high-flux dialyzers. Balancing chambers are controlled by flow sensors to manage the inflow and outflow of dialysate.","obj":3},
  {"topic":"Hemodialysis","q":"The rate of solute diffusion across the dialysis membrane is influenced by all EXCEPT:","opts":["Molecular size and weight","Surface area of the membrane","Temperature of the dialysate","Patient's dietary potassium"],"ans":3,"expl":"Diffusion rate is affected by molecular size/weight, solute charge, pore size/number, membrane surface area, dialysate temperature, flux rate, and membrane thickness. The patient's diet is not a direct factor in membrane diffusion rate.","obj":3},
  {"topic":"Hemodialysis","q":"A patient's venous pressure alarm sounds LOW. Which is a potential cause?","opts":["Kinking between the monitoring site","Occlusion on the venous side","Infiltration of the venous needle","Hypotension or disconnection of the venous circuit (including needle dislodgment)"],"ans":3,"expl":"A low venous pressure alarm can be caused by hypotension, arterial occlusion or insufficient flow, or disconnection of the venous circuit including needle dislodgment. High-pressure causes include kinks, malposition, infiltration, and venous occlusion.","obj":3},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD3B};
