// BATCH 15: NEW questions from ANNA Module 5 (Transplant infections & malignancy).
// Verified against module text. obj: 6=infection control, 1=pathology, 2=interventions.
const NEW_QUESTIONS_MOD5C = [
  {"topic":"Transplant","q":"Which viral infection is most serious when a CMV-positive donor kidney is placed into a CMV-negative recipient (primary infection)?","opts":["Epstein-Barr virus","Cytomegalovirus (CMV)","BK virus","Herpes simplex virus"],"ans":1,"expl":"Primary CMV infections are the most serious — a CMV donor(+) kidney into a CMV(-) recipient is the highest-risk scenario and can be life-threatening. CMV causes fever, malaise, leukopenia, and can invade the allograft.","obj":6},
  {"topic":"Transplant","q":"CMV infection after transplant has its highest incidence during which timeframe?","opts":["First 24-48 hours","First 1-4 months","First year only","Anytime equally"],"ans":1,"expl":"CMV has a higher incidence in the first 1-4 months post-transplant. Primary CMV (D+/R-) is most serious; surveillance and prophylaxis (e.g., valganciclovir/Valcyte) are used according to donor/recipient CMV status.","obj":6},
  {"topic":"Transplant","q":"Which post-transplant viral infection is closely associated with post-transplant lymphoproliferative disease (PTLD)?","opts":["Cytomegalovirus (CMV)","BK virus (polyomavirus)","Epstein-Barr virus (EBV)","Varicella-zoster virus (VZV)"],"ans":2,"expl":"EBV, a gamma herpes virus, is closely associated with PTLD (abnormal B-cell proliferation). It typically causes infectious mononucleosis and is linked to several cancers. PTLD affects 1%-3% of transplant recipients.","obj":6},
  {"topic":"Transplant","q":"Which is the most common type of skin cancer in kidney transplant recipients and by what margin is it increased?","opts":["Basal cell carcinoma; 10-fold","Squamous cell carcinoma; 65-fold increase, most common and more aggressive","Melanoma; 3-to-5-fold","Kaposi sarcoma; 100-fold"],"ans":1,"expl":"Squamous cell carcinoma is the most common skin cancer in transplant recipients, with a 65-fold increase compared to the general population; it is more aggressive, occurs in sun-exposed skin, and risk increases with time since transplant.","obj":1},
  {"topic":"Transplant","q":"Which is a TRUE statement about malignancy in kidney transplant recipients?","opts":["Malignancy is rare after transplant","Overall risk of cancer is increased two-to-three-fold, with skin cancer and non-Hodgkin's lymphoma among the most common","Cancer risk decreases with age","Incidence of melanoma is 65-fold higher"],"ans":1,"expl":"Overall risk of cancer is increased 2-3 fold after transplant. Lung, liver, non-Hodgkin's lymphoma, kidney, and skin cancer are most common. Except for non-Hodgkin's lymphoma, incidence increases sharply with age, and there is higher incidence in males.","obj":1},
  {"topic":"Transplant","q":"What is the recommended strategy when a kidney transplant recipient reports any diarrhea?","opts":["Immediately give loperamide","Check stool for culture, C. diff, and O&P before giving anti-diarrheal medications","Restrict all fluids","Start antibiotics empirically"],"ans":1,"expl":"For any complaint of diarrhea post-transplant, check stool for culture, C. diff, and O&P before giving anti-diarrheal medications. C. diff is treated with oral vancomycin and metronidazole; to reduce incidence, limit antibiotic use.","obj":6},
  {"topic":"Transplant","q":"Which drug class is used to treat BK virus nephropathy because it is non-nephrotoxic with antiviral properties, unlike cidofovir?","opts":["Leflunomide","Ganciclovir","Valganciclovir","Acyclovir"],"ans":0,"expl":"Leflunomide has both antiviral and immunosuppressive properties and is not nephrotoxic, so it can be used to treat BK nephropathy. Cidofovir is limited by its nephrotoxic side effects. Treatment also involves reducing immunosuppressants.","obj":2},
  {"topic":"Transplant","q":"Pneumocystis jiroveci (formerly carinii) pneumonia after transplant carries the highest risk during which timeframe?","opts":["First 2-6 months post-transplantation","First 24 hours","After 2 years","Only in the last year"],"ans":0,"expl":"PCP carries the highest risk in the first 2-6 months post-transplantation. It is preventable with prophylaxis: TMP-SMX single strength; if sulfa-allergic and not G6PD-deficient, dapsone 100 mg PO daily; if G6PD-deficient, atovaquone or inhaled pentamidine.","obj":6},
  {"topic":"Transplant","q":"A transplant recipient who is seronegative for varicella-zoster virus (VZV) has a known exposure. What should the nurse anticipate?","opts":["No action needed","Give varicella-zoster immune globulin within 96 hours of exposure, and prophylactic oral Valtrex or acyclovir","Immediate IVIG only","Isolate with no treatment"],"ans":1,"expl":"All transplant candidates are screened for VZV. Seronegative patients should report any VZV exposure promptly. Give varicella-zoster immune globulin within 96 hours after exposure, and prophylactic oral Valtrex or acyclovir in confirmed exposure.","obj":6},
  {"topic":"Transplant","q":"Fungal (thrush) prophylaxis after transplant commonly uses which agents?","opts":["Amoxicillin and ciprofloxacin","Nystatin (swish and swallow), clotrimazole troches, or fluconazole daily for 1 month","Acyclovir and valganciclovir","TMP-SMX and dapsone"],"ans":1,"expl":"Thrush prophylaxis uses nystatin (swish and swallow), clotrimazole troches, or fluconazole daily for 1 month. It can recur during treatment for rejection (increased immunosuppression).","obj":6},
  {"topic":"Transplant","q":"Renal cell carcinoma in transplant recipients is notable because:","opts":["Mostly arises in transplanted kidneys","The majority is found in native kidneys (only ~9% in the transplanted kidney), with low-grade low-stage tumors and a good prognosis, and is 15-100 times higher than the general population","It is terminal in 5 years","Only occurs in the liver"],"ans":1,"expl":"The majority of renal cell carcinoma is found in native kidneys; only ~9% is in transplanted kidneys. It is 15-100 times higher than in the general population, has low-grade/low-stage tumors with good prognosis, usually within the first 5 years, and is screened with routine ultrasound the first 5 years.","obj":1},
  {"topic":"Transplant","q":"Which is a primary prevention for post-transplant malignancy?","opts":["Avoid sunlight and use sun precautions","Daily aspirin","Monthly IVIG","Increase immunosuppression"],"ans":0,"expl":"Prevention of post-transplant malignancy includes smoking cessation, routine self-exam of skin, sun precautions, and following American Cancer Society screening guidelines.","obj":2},
  {"topic":"Transplant","q":"BK virus (polyomavirus) nephropathy in kidney transplant patients is best characterized by:","opts":["Always symptomatic with flank pain","Often no symptoms, with possible slow rise in serum creatinine with no other explanation (e.g., rejection, CNI toxicity, dehydration)","Frequent gross hematuria","No impact on the allograft"],"ans":1,"expl":"BK nephropathy often has no symptoms; there may be a slow rise in serum creatinine with no other explanation. BKV reactivates in 10%-60% of renal transplant patients; 1%-5% develop nephropathy, half of whom reject the kidney.","obj":6},
  {"topic":"Transplant","q":"Which screening is recommended for renal cell carcinoma in transplant recipients?","opts":["Annual chest CT","Routine ultrasound the first 5 years post-transplant","Colonoscopy yearly","Annual MRI"],"ans":1,"expl":"Routine ultrasound screening is recommended the first 5 years post-transplant for renal cell carcinoma, given the increased risk and occurrence within the first 5 years.","obj":2},
  {"topic":"Transplant","q":"The treatment of choice for post-transplant lymphoproliferative disease (PTLD), in addition to reducing immunosuppression, often includes:","opts":["Acyclovir alone","Rituximab (Rituxan) and/or other chemotherapy depending on organs affected","Oral nystatin","Leflunomide"],"ans":1,"expl":"PTLD treatment involves reduction of immunosuppression plus Rituximab (Rituxan) and/or other chemotherapy depending on which organs are affected. Risk factors include EBV status (D+/R-), CMV co-infection, and intensity of immunosuppression.","obj":2},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD5C};
