// BATCH 14: NEW questions from ANNA Module 4 (PD) Q&A + peritonitis/catheter detail.
// Verified against module text.
const NEW_QUESTIONS_MOD4B = [
  {"topic":"Peritoneal Dialysis","q":"Which is a recognized reason a patient may need to stop peritoneal dialysis and transition to hemodialysis?","opts":["A well-healed exit site","Relapsing or refractory peritonitis, refractory exit site infection, fungal or mycobacterium peritonitis, or membrane/ultrafiltration failure","A functioning catheter with clear drainage","Patient preference for fewer daily exchanges"],"ans":1,"expl":"Reasons to transition off PD include relapsing/refractory peritonitis, refractory exit site infection, fungal/mycobacterium peritonitis not responding to treatment, a non-functioning catheter (migration/omental wrap), severe leaks, or membrane/ultrafiltration failure.","obj":2},
  {"topic":"Peritoneal Dialysis","q":"The standard dialysate concentration used to perform a Peritoneal Equilibration Test (PET) is:","opts":["1.5% dextrose","2.5% dextrose","4.25% dextrose","0.9% saline"],"ans":1,"expl":"The standard is to use 2.5% dialysate to perform PET. A modified PET to test for ultrafiltration failure uses 4.25% dialysate.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"A patient cannot use a powered warmer and asks how to warm PD dialysate. The nurse should advise:","opts":["Microwave the bag briefly","Soak the bag in hot water","Leave the bag in sunlight or sleep with it to warm, and NEVER soak it in hot/warm water","Use a boiling water bath"],"ans":2,"expl":"Without power, the patient can leave the bag in sunlight or sleep with it to warm. The key is NOT to soak it in hot or warm water. Room temperature dialysate is safe; warming is mainly for comfort and vessel dilation. Overheating can scald the peritoneum.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"When troubleshooting hemoperitoneum (bloody effluent), which dialysate approach may help?","opts":["Use 4.25% high dextrose","Use room temperature dialysate (vessel constriction)","Use very warm dialysate","Add heparin without changing temperature"],"ans":1,"expl":"Using room temperature dialysate is a way to troubleshoot hemoperitoneum because it causes vessel constriction. Warming dialysate causes vessel dilation. Also rule out peritonitis and consider heparin to prevent clotting.","obj":2},
  {"topic":"Peritoneal Dialysis","q":"Which statement about non-occlusive dressing and immobilization for a healed PD exit site is correct?","opts":["Sterile dressing is mandatory at all times","Once healed, dressing is optional and only immobilization is mandatory to prevent trauma","All four sides of gauze must always be taped","The site should be kept under an occlusive dressing"],"ans":1,"expl":"ISPD recommends non-occlusive dressing. Once the exit site is completely healed, dressing is optional—only immobilization is mandatory to prevent trauma. Moisture trapped by occlusive dressings can enhance bacterial growth.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"A patient asks whether swimming in a maintained pool is safe. The MOST important nursing guidance, per ISPD, is:","opts":["Swimming is always prohibited","Swimming should be restricted to well-maintained chlorinated pools/clean salt water, with immediate exit site care after swimming","Avoid all water contact permanently","Only private pools are ever allowed"],"ans":1,"expl":"Swimming should be restricted to well-maintained chlorinated pools and clean salt water, and exit site care should be done immediately after swimming. Avoid submerging the exit site in bathtubs, hot tubs, and whirlpools.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"For a patient with a LOW permeability (slow) peritoneal membrane, which approach BEST maximizes clearance?","opts":["Frequent short dwells","Longer dwell time with higher dialysate volume (e.g., CAPD-style longer dwells)","Reduced dialysate volume","More rapid exchanges"],"ans":1,"expl":"A low transporter needs longer dwell for each exchange and higher dialysate volume so the total 24-hour volume is higher. CAPD, with longer dwell times, often provides better dialysis for low transporters than frequent short-dwell APD.","obj":3},
  {"topic":"Peritoneal Dialysis","q":"What is the risk of adding potassium into the dialysate bag for a PD patient?","opts":["No risk if sterile technique is used","Higher risk of peritonitis from contamination, especially since it is done with every exchange, plus possible abdominal discomfort upon infusion","It causes hyperkalemia","It is the preferred route over oral supplements"],"ans":1,"expl":"Adding potassium to dialysate carries a risk of peritonitis if sterile technique is not practiced, and it is done continuously (every exchange), increasing contamination risk. Potassium IP can also cause abdominal discomfort/pain upon infusion. Oral or food supplementation is preferred.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"When should peritonitis be treated with antibiotics given via which route?","opts":["Only oral","Intraperitoneally, IV, or orally, with a treatment duration of 2-4 weeks","Only IV","Only intraperitoneally for 1 week"],"ans":1,"expl":"Peritonitis treatment uses antibiotics given intraperitoneally, IV, or orally, with a duration of 2-4 weeks. Diagnosis requires 2 of 3: abdominal pain/cloudy effluent, effluent WBC >100/mm3 with >50% PMN, or positive culture.","obj":6},
  {"topic":"Peritoneal Dialysis","q":"Which peritonitis definition matches 'symptoms do not abate after 5 days of appropriate therapy'?","opts":["Relapsing peritonitis","Refractory peritonitis","Recurrent peritonitis","Catheter-related peritonitis"],"ans":1,"expl":"Refractory peritonitis is defined as symptoms not abating after 5 days of appropriate therapy. Relapsing recurs within 4 weeks with the same organism; recurrent with a different organism.","obj":6},
];
if (typeof module !== 'undefined' && module.exports) module.exports = {NEW_QUESTIONS_MOD4B};
